### ISSUE TITLE
Strange syntax highlighting for embedded numbers on Installation page

### ISSUE THREAD

**Issue by stuartlangridge** [elementary/mvp#1000]
The shasum commands and command results on the Installation page have strange syntax highlighting:

![screenshot at 16-01-26 04 30 16](https://cloud.githubusercontent.com/assets/4356350/12572526/897098d2-c3e5-11e5-9905-353d4967404c.png)

This is pretty much a bug in highlightjs (filed as https://github.com/isagalaev/highlight.js/issues/1062), but it may be worth working around it in the docs (perhaps by not declaring these snippets to be bash).

**Comment by stuartlangridge** [comment]
Seems to be fixed upstream, so the website needs a new version of hljs.

**Comment by btkostner** [comment]
Seems like it fixed some of the highlighting, but it still highlights the 'cd' and 'fc' in the output. I updated the script in the [fix-1000](https://github.com/elementary/mvp/tree/fix-1000) branch.
