### ISSUE TITLE
Best to not do work in a JavaScript scroll handler

### ISSUE THREAD

**Issue by stuartlangridge** [elementary/mvp#1002]
A number of places in the elementary site do work in a scroll handler: examples include various `    $(document).on('scroll', function (event)` functions in `scripts/docs/main.js`. In general, it's best to not do actual work in a scroll handler, because slow devices (in particular mobiles) are likely to have jerky scrolling because of it. Instead, it's better to debounce; something like:

    var scrollDebounce;
    $(document).on('scroll', function (event) {
        clearTimeout(scrollDebounce);
        scrollDebounce = setTimeout(actuallyDoWork, 50);
    });

and then do the work in `actuallyDoWork()`. This prevents jerky scrolling in less-powerful devices.

**Comment by Csardelacal** [comment]
Personally I would have suggested adding a second timer / fallback to prevent the script from failing if the user drags the page slowly on a mobile device. Slow scrolling on them launches many handlers, which would cause your script to never actually redraw the page / execute the code.

Something along the lines of 
```js
(function() { //Always capture your scopes! Don't wanna have variables overriding each other
  var scrollDebounce = null;
  var timer;

  $(document).on('scroll', function (event) {
     //If the code was not executed in the last .5 seconds, don't debounce it
      if (timer && timer+ 500 < (+new Date()) ) { return; }

      scrollDebounce && clearTimeout(scrollDebounce);
      scrollDebounce = setTimeout(function() { 
          actuallyDoWork(); 
          timer = +new Date();
      }, 50);
  });
}())
```

I typed this live while I was having a coffee. It's untested ^^

**Comment by btkostner** [comment]
I was working on a new popover widget and decided to implement this:
```javascript
    var diff = new Date().getTime() - this.repositionedAt;

    if (this.repositionedAt == null || diff >= 500) {
      this.repositionedAt = new Date().getTime();
      var that = this;

      this.repositionTimer = setTimeout(function() {
        logic();
      }, 100)
    }
```
If you guys like what you see I'll implement it in all of our rapid event handlers

**Comment by Lukewh** [comment]
I've had success with something like (untested):
```javascript
var scrollPositionCache = window.scrollY;
function scrollFrame() {
  var newScrollPosition = window.scrollY;
  if (newScrollPosition !== scrollPositionCache) {
    // do stuff
  }
  scrollPositionCache = newScrollPosition;
  requestAnimationFrame(scrollFrame);
}

requestAnimationFrame(scrollFrame);
```

**Comment by danrabbit** [comment]
@stuartlangridge can you test the attached branch and see if it solves your issue?

**Comment by stuartlangridge** [comment]
Brief comment left on commit; other than that, LGTM.
