### ISSUE TITLE
Duplicate entry for workspace overview in german "learning the basics" site

### ISSUE THREAD

**Issue by mazienho** [elementary/mvp#1015]
In the topic "Workspaces" (german "Arbeitsflächen") there is a duplicate entry for the shortcut <SUPER>+S
https://elementary.io/de/docs/learning-the-basics#multitasking

**Comment by lewisgoddard** [comment]
The affected string has been re-queued in transifex, once a translator re-translates and we update our translations, you will see a fix.

**Comment by lewisgoddard** [comment]
Now there is a different duplicate. https://github.com/elementary/mvp/blob/master/lang/de/docs/learning-the-basics.json#L45

**Comment by lewisgoddard** [comment]
This has been repaired in Transifex.
