### ISSUE TITLE
Set smarter mobile web app title

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#102]
I don't think this is a good page title. Especially if we consider that this site will eventually host documentation and other links and not just the Freya download.

Mainly, where I'm experiencing this problem is with bookmarking this site. Especially using the "add to homescreen" function on my mobile. Having a homescreen icon with "elementary OS Freya" is weird.

I think simply "elementary" would be the most encompassing

**Comment by TuurDutoit** [comment]
Do you want me to change it to `elementary` or `elementary OS`?

**Comment by maliktunga** [comment]
[Apple isn't good with page titles either.](https://www.apple.com/osx/)

How about "Discover elementary OS"? :wink:

**Comment by cassidyjames** [comment]
@danrabbit if you're concerned with the name when added to a homescreen, both iOS and Android support a different short name for that (because they know the title in the browser isn't usually a good title for the homescreen).

iOS:
```
<meta name="apple-mobile-web-app-title" content="Short name">
```

Android: https://developer.chrome.com/multidevice/android/installtohomescreen

**Comment by danrabbit** [comment]
Good call, Cass. I've changed the bug title

**Comment by lewisgoddard** [comment]
What exactly do we want these set to?

**Comment by danrabbit** [comment]
Probably just "elementary"?

**Comment by maliktunga** [comment]
@danrabbit Good. Short and straightforward.

**Comment by davidak** [comment]
if i google `elementary` there is nothing from you on the first page. with adding `OS` every item is about your project.
also the domain is `elementaryos`. you should use this established brand as the page title and don't compete with an english word. (only apple can do that. nothing about apples on the first google page :D)

**Comment by cassidyjames** [comment]
Eh, technically elementary is our brand. elementary OS is a product of
elementary. The word elementary, when combined with our logo, is unique to
us. ;)
