### ISSUE TITLE
Add "Powered by Slack" to team page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1030]
Somewhere, probably the bottom. There's a Slack icon in FontAwesome.

**Comment by lewisgoddard** [comment]
http://fortawesome.github.io/Font-Awesome/icon/slack/

**Comment by srukle** [comment]
<p><i class="fa fa-slack"></i>Powered by Slack</p>

Just below the <a class="button suggested-action" href="get-involved">Get Involved</a> in team.php ?

**Comment by lewisgoddard** [comment]
I think we usually put a normal space between our icons and text, and I'm not sure we want it quite as bold as that. Maybe we have a faded or lighter class for supporting text.

![poweredbyslack](https://cloud.githubusercontent.com/assets/831389/13086339/b1cb9bd2-d4da-11e5-937a-8434164c346c.PNG)

**Comment by srukle** [comment]
You could simply give the color #777 inline.

`<p style="color: #777"><i class="fa fa-slack"></i> Powered by Slack</p>`

or

```
<p class="slack-bottom"><i class="fa fa-slack"></i> Powered by Slack</p>

.slack-bottom{color: #777;}
```

**Comment by danrabbit** [comment]
We have `.small-label` in main.css

**Comment by srukle** [comment]
Then the fix would be

`<p class="small-label"><i class="fa fa-slack small-label"></i> Powered by Slack</p>`

![screenshot](https://cloud.githubusercontent.com/assets/9255609/13086934/1fbfcee0-d4ab-11e5-9285-4ab5b8f3bec4.png)

**Comment by lewisgoddard** [comment]
Thanks for pushing this forward, @srukle.
