### ISSUE TITLE
Better slingshot documentation

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1032]
At the moment we don't document:
- [x] The keyboard shortcut to launch Slingshot
- [x] Things you can get in slingshot search
    - [x] Apps
    - [x] Settings
    - [x] Actions (as of Loki)
    - [x] Calculations

**Comment by srukle** [comment]
I notice that Elementary doesn't have very much centralized docs. So where do you suggest these docs be written?

Here? Or should it be something on its own?

https://elementary.io/docs/learning-the-basics

**Comment by lewisgoddard** [comment]
I think this is likely best put under the heading [Applications](https://elementary.io/docs/learning-the-basics#applications). Currently, that heading is devoid of images, as well as all these details. Current text:

> On the left side of the panel is the Applications item. Clicking Applications brings up a launcher with all of your installed apps. You can view multiple pages of apps using the pagers at the bottom or by scrolling. You can also use the view switcher at the top to switch between a grid view and a category view. Lastly, you can search the launcher by typing at any time.
