### ISSUE TITLE
Branches/Beta website page are indexed by search engines

### ISSUE THREAD

**Issue by KeitIG** [elementary/mvp#1034]
Shouldn't be.

![elementaryseo](https://cloud.githubusercontent.com/assets/1311607/13091143/0e22d2aa-d4fa-11e5-8f16-abd8f4a0c7d7.PNG)

Could be solved using a `meta` with `noindex, nofollow` on beta website.

**Comment by lewisgoddard** [comment]
A meta element won't update on existing branches, whereas a robots.txt will.

**Comment by KeitIG** [comment]
Shouldn't we delete old branches too btw ?

**Comment by lewisgoddard** [comment]
Possibly, but that's taken care of server-side.

**Comment by btkostner** [comment]
a `robot.txt` file should be added at the root of `beta.elementary.io` with the contents:
```
User-agent: *
Disallow: /
```

**Comment by fabianthoma** [comment]
Done: http://beta.elementary.io/robots.txt
