### ISSUE TITLE
Incorrect hreflang implementation

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1046]
Got an email from Google Search Console today:

> Google has detected that some pages on your site have implemented the rel-alternate-hreflang tag incorrectly. In particular, there seems to be a problem with incorrect language and region codes, or incorrect bi-directional linking (if page A links with hreflang to page B, there must be a link back from B to A as well). Google uses the hreflang attributes to serve the correct language or regional URL to the right users in search results.

> Until you correct the errors on the hreflang links, your website will not benefit from additional language or region targeting.

> Fix this problem now:

> **Find incorrect hreflang implementations**
> Use the examples provided in the International Targeting feature in Search Console to get a sample of pages with incorrect hreflang implementation.

> [See Error Report](https://www.google.com/appserve/mkt/p/TEcqZGjFTPmnpK1GNPgp5RPxOYF9DtrfikYiOMFBCotQ-TjeMlCCnDsw0rICunRSbFNaV_ZBoXBAmAHJOuP-lGYFwgQ568OJVbUXXRRS3ksqQpyCV13f8mPUqI0QWEo5OYF7nnXfv9MPQIrW4B3LbS3iYT7wcv5Ecaf_Y8XEEN4hrFCoTETtvojL29n7QqHbUUdzzL3UEGVix9GzMzLElfAsjvpjs3JYj_wgy0ha22436WAZWXrBYhUz74FSuD4T6snctTfDbxaH)

> Need more help?
> - Learn more about how to [use hreflang for language and regional URLs](https://www.google.com/appserve/mkt/p/m0YM_M67bo_mb3mgou8yuQnqGEMPHOJDbF6nzVnxC0SYvp5laUXPIsJQoozPcG4J6ED9-Id9OhcA_cjo35ummIhaZCpd31jETwYu-ziU6vHEGCKaelHUlD8hlnKYooE17SVTsuMDKQTx1SCQGpv_2DgcH5yo9tKLbVK6eLaTBk12HlKGk63xiwRu9zukx6zSH7Ao5OtWzeTOkx6QFw7-B_aIAJSMjXz6nfs08aFNIiIBluUN4u7Rlc1Sg8LiIALnzHaKwQVr2jaYNqTYtA==).
> - [Ask questions in our forum](https://www.google.com/appserve/mkt/p/Bi4jQxhchzMdxfwruGBL5DFI3OIbxeZ2u86EZPM4Kjz0D5V4P7pS_rLGXHCXGDeFHNuAcq_afAhIo37flk-qwblKgFrn5zFFcIiFsNQm-HKwV52niS7Pm_lhmWX_El4phrHzxflTt3yOI51_rcNhkkarGQN0tHS1Rj4lauNXKfphoK-VZ99RScWNhK7ZxMwtZ0DUJrVAYAjO5WIL7MIYXw1uCxh2Ldp6ORHxtvYUnEXaXC6RwJYzFDM=) for more help - mention message type [WNC-659602].

**Comment by lewisgoddard** [comment]
Can you post the error report and try and clear up if our language codes are wrong or if we're not linking back? As far as I am concerned, every page has `a` links to every language, but the `link[rel=alternate]` is only used on non-english pages.

### _templates/header.php
```
        <?php if (!empty($page['lang']) && $page['lang'] != 'en') { ?>
        <link rel="alternate" type="text/html" hreflang="en" href="<?php echo $sitewide['root'].(($page['name'] == 'index') ? '' : $page['name']); ?>">
         <link rel="stylesheet" type="text/css" media="all" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600|Droid+Sans|Roboto+Mono&subset=latin,greek,vietnamese,greek-ext,latin-ext,cyrillic,cyrillic-ext">
        <?php } else { ?>
        <link rel="stylesheet" type="text/css" media="all" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600|Droid+Sans|Roboto+Mono">
        <?php } ?>
```

### _templates/footer.php
```
                    <?php
                    foreach ($l10n->list_langs() as $langCode => $langName) {
                        $path = $sitewide['root'].$langCode.$page['path'];
                        ?>
                        <li><a href="<?php echo $path; ?>" rel="alternate" hreflang="<?php echo str_replace('_', '-', $langCode); ?>" data-l10n-off>
                            <?php echo $langName; ?>
                        </a></li>
                        <?php
                        if ($langCode == 'en') {
                            ?>
                            <hr>
                            <?php
                        }
                    }
                    ?>
```

**Comment by cassidyjames** [comment]
It looks like it's from English.

`'en' - no return tags`
