### ISSUE TITLE
www subdomain does not redirect

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1047]
`http://www.elementary.io` appears as a standalone site which hurts SEO. It should instead redirect to `http://elementary.io`

**Comment by btkostner** [comment]
Seems to display the page for me

**Comment by cassidyjames** [comment]
It displays the page but does not redirect to the non-www subdomain. This creates effectively a duplicate site.

**Comment by cassidyjames** [comment]
(likely a server-side config)

**Comment by lewisgoddard** [comment]
The in-repository [`nginx.conf`](https://github.com/elementary/mvp/blob/master/nginx.conf) is set to work like this, but since we hide the SSL portion I'm not sure how to change it.

**Comment by fabianthoma** [comment]
We have the same nginx configuration as this repo, with the exception of the ssl certificates added, but that's just a few lines and has nothing to do with routing, so no idea why this won't work

**Comment by lewisgoddard** [comment]
I'm saying that the config here doesn't include that, maybe use the first two server blocks from here. https://github.com/eustasy/letsencrypt-with-nginx/blob/master/nginx.conf

**Comment by lewisgoddard** [comment]
I'm going to leave this open until I either see changes propagate, or figure out what is wrong.

**Comment by lewisgoddard** [comment]
Fixed: https://www.google.co.uk/search?q=site%3Awww.elementary.io&oq=site%3Awww.elementary.io
