### ISSUE TITLE
Safari 9.2.1 iOS homepage menu overlap

### ISSUE THREAD

**Issue by Lukewh** [elementary/mvp#1049]
![](http://i.imgur.com/30DFULu.jpg)

Sent from my phone will investigate more when I get chance but looks like a minor fox

**Comment by Lukewh** [comment]
Fix... 

![](http://i.imgur.com/9sCRSvz.jpg)

**Comment by btkostner** [comment]
I'm going to guess flexbox support issue

**Comment by Lukewh** [comment]
https://github.com/elementary/mvp/pull/1058
