### ISSUE TITLE
Opening a link in new tab leaves the link text blue

### ISSUE THREAD

**Issue by Theonewithideas** [elementary/mvp#1052]
After opening the link in new tab either via middle-click or right click -> "open in new tab", the link stays blue after the link has been clicked. This is reproduced in Chrome, didn't check in other browsers...

![image](https://cloud.githubusercontent.com/assets/6058082/13191247/b1d88efc-d762-11e5-9aef-b0558527170a.png)
![image](https://cloud.githubusercontent.com/assets/6058082/13191281/e4e60de2-d762-11e5-909d-63b41c66bd53.png)

**Comment by btkostner** [comment]
This is actually an issue with the browser. It happens with anything that has a `:focus` style.

You can actually go to any website, and if you hover over some link that has a style, say underline, that style will stay when you right click and do something else.

Annoying, yes. Something we can fix, not really.
