### ISSUE TITLE
brand and team pages need to be translatable

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1053]
I checked out TRANSLATE.md but didn't follow exactly. We should make sure these are translatable since they add quite a bit of text.

**Comment by cassidyjames** [comment]
Here are the strings extracted using the `backend/extract-l10n.php` script... not sure where they go.
[brand.json](https://github.com/elementary/mvp/files/139326/brand.json.txt)
[team.json](https://github.com/elementary/mvp/files/139327/team.json.txt)

**Comment by lewisgoddard** [comment]
They should just be put in the right place when you generate them. It's `lang/en/`

**Comment by lewisgoddard** [comment]
Oh, sorry, wrong script. Run `.tx/prepush.sh` like it says in [`TRANSLATE.md`](https://github.com/elementary/mvp/blob/master/TRANSLATE.md), then commit the new files. You'll need to run `tx push -s` to push them to Transifex too.

**Comment by lewisgoddard** [comment]
Maybe run `php backend/translations-checker.php` too, it checks them for errors.
