### ISSUE TITLE
Purchase/Download button not translatable

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1054]
Since that button's text is being set directly in js, it's not translatable. As such, all languages show the button in English.

**Comment by btkostner** [comment]
We could do that, and just not have any animation.

Option 2 being we could have two spans of text on the website, and then we have the javascript just replace the button text with the translated span text.

**Comment by lewisgoddard** [comment]
Oh, I like Option 2, that's clever. Hidden down the bottom with the modals?

**Comment by btkostner** [comment]
sounds good to me
