### ISSUE TITLE
Linux Live USB Creation Method Should Switch To DD

### ISSUE THREAD

**Issue by sudopluto** [elementary/mvp#1055]
Reasons:
1) dd is now standard across most linux distros
2) the guide asks the user to drop into the terminal anyways for checksum

Please let me know if you guys agree, and if you do I'll start up on a pull request.

**Comment by lewisgoddard** [comment]
There are a couple of problems here. 1st, while the terminal is used for checksums, many people will skip those, and the commands can safely be run without any user input. DD, on the other hand, could inadvertently erase one of my drives if I use it without knowing what I'm doing, which is exactly the target audience of that document.

Without Unetbootin, there is no nice GUI. There is no dropdown of drives, and no identification of sizes. User selection of a drive would be made a guessing game. A dangerous guessing game.

### Summary
- DD requires input, incorrect user input results in wrong disk being wiped.
- DD isn't the only command needed, something else to help select the right disk is.
- DD doesn't allow me to reserve space for preservation, something people may want to use to try the distribution out more thoroughly first.

**Comment by sudopluto** [comment]
Hmmm those are some valid points.

I just don't like the fact that we are asking the user to install a random piece of software. Also the link included in the docs only works for ubuntu. What if the user is using another distro like Fedora? 

I actually think it would be cool if  elementry offered a cross platform application that would handle live usb creation, but that is outside the scope of this issue.

**Comment by lewisgoddard** [comment]
I agree, but if that is the main complaint then we can change the issue to point out that the linux instructions are not very cross-platform friendly. That said, it's very difficult, and confusing for the user, to write documentation for several distributions.

**Comment by sudopluto** [comment]
What about a bash script? The user copies and pastes a one line command that will setup a usb. The script could simplify choosing the disk to write to and could give a warning.

**Comment by danrabbit** [comment]
I'm very -1 on using a bash script. We shouldn't be conditioning new users that it is safe to copy scripts from the internet like that

**Comment by sudopluto** [comment]
Umm we could have the user manually download it? I mean realistically the user would become conditioned to copying and pasting anyways due to the necessity of ppas on Ubuntu.

**Comment by danrabbit** [comment]
We also don't recommend PPAs. They're unsafe and contribute to instability. Sorry but using a script is not a good solution.
