### ISSUE TITLE
Favicon for website in android multitasking view is hard to see in chrome.

### ISSUE THREAD

**Issue by sudopluto** [elementary/mvp#1056]
I'll probably make a quick pull request.
Edit: this is only for the docs site because of the purple.
![screenshot_20160220-231704](https://cloud.githubusercontent.com/assets/9754192/13200919/476e46b0-d82a-11e5-81d1-1a60645ae1fb.png)

**Comment by cassidyjames** [comment]
We may want to consider using a white-on-blue favicon everywhere (I imagine the black-on-transparent doesn't work well, for example, on Midori Private Browsing's dark tabs, either).
