### ISSUE TITLE
Header text is too thin

### ISSUE THREAD

**Issue by Theonewithideas** [elementary/mvp#1061]
h1 and h4 font-weight is too low, to the point where it looks unevenly-thin and out-of-place:

![before](https://cloud.githubusercontent.com/assets/6058082/13380935/c3949fbc-de4e-11e5-9b8d-9f64abfa60b7.png)

My solution would be to change the font weight:

h1: `100` -> `bold`
h4 `300` -> `bold`

![after](https://cloud.githubusercontent.com/assets/6058082/13380953/538d279c-de4f-11e5-8efb-f1c5079b8c77.png)

IMO, it looks easier on the eye and more elegant.

And resembles the style of h3 better : 
![h3](https://cloud.githubusercontent.com/assets/6058082/13380972/c4f7a826-de4f-11e5-999a-457318e18e6c.png)

**Comment by danrabbit** [comment]
Thin font weights are part of our brand. Marking this as opinion.
