### ISSUE TITLE
Tweet the Press quotes

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#107]
Looks like all of our quotes fit in 140 chars. Might be cool to have a mechanism to tweet the quote with a link to our website

**Comment by cassidyjames** [comment]
@danrabbit what was that link you sent me with an inline tweet thing? You called them "pull tweets."

**Comment by KeitIG** [comment]
How do you want to do this ? Just tweet them once ? When should be they tweeted ? What happens if a new quote is added ?

**Comment by danrabbit** [comment]
@KeitIG So what I'm thinking of is something like this: http://winwar.co.uk/plugins/inline-tweet-sharer/

Where a user would hover the quote and get a twitter icon ::after. Then they could click to tweet the quote along with a link back to our website. Basically just giving people an easy mechanism for sharing our website with their followers.
