### ISSUE TITLE
hashtool screenshot is not from the latest version of Windows.

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1071]
The hashtool screenshot looks old compared to the Rufus screenshot which looks newer. We should make sure we have screenshots from Windows 10.

**Comment by lewisgoddard** [comment]
I am assuming this is under Windows on https://elementary.io/docs/installation#verify-your-download

**Comment by lewisgoddard** [comment]
![image](https://cloud.githubusercontent.com/assets/831389/14812032/3319a168-0b93-11e6-994a-32b46c90a1fb.png)
