### ISSUE TITLE
Style printed documents better

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/mvp#1075]
Got this idea from reading this Reddit post https://www.reddit.com/r/elementaryos/comments/49715h/pdf_version_of_the_elementary_os_developer/

This might be a good idea to automatically generate PDF versions of our docs (user guide, dev guide, HIG, etc). Of course it's important that users have the latest versions of these docs, but being able to get a downloadable copy might be good.

**Comment by aleksandar-todorovic** [comment]
What's wrong with them just "printing" the docs as a PDF?

**Comment by KeitIG** [comment]
I guess a generated PDF would be easier to print than a web page

**Comment by lewisgoddard** [comment]
You can easily hide the menus, header, and footer with some print.css

Maybe we should change this issue to "Style printed documents better."

**Comment by divayprakash** [comment]
Correct me if I'm wrong, I think this would require `@import url("print.css") print;` statements to be added to all stylesheets, else `<link href="print.css" rel="stylesheet">` to all the separate `php` webpages.

**Comment by lewisgoddard** [comment]
We have a `header.php` file that can take care of this globally, and it could also be added to the existing sheet with:
```
@media print {
    body {
        background-color: lightgreen;
    }
}
```

**Comment by danrabbit** [comment]
Now that we have the actions sidebar, we could probably put a "Print", "Save", or "Share" item there that would make it easy for folks to print to PDF or some such

**Comment by btkostner** [comment]
Share would be interesting to create, but I feel like the print and save buttons are redundant as any modern browser already has them.

**Comment by danrabbit** [comment]
In that case, I'm going to change the title to what Lewis suggested earlier since it seems the scope of this issue is just creating a print.css
