### ISSUE TITLE
The instructions for verifying Downloads is incorrect

### ISSUE THREAD

**Issue by linusbobcat** [elementary/mvp#1076]
### Expected Behaviour
it should return the hashsum

### Actual behaviour
Assuming the ISO is in the downloads folder, copy and pasting "shasum -a 256 elementaryos-0.3.2-stable-i386.20151209.iso" into the terminal will fail as most terminals starts in the home folder

### Steps to reproduce the behaviour
1. Open a terminal
2. copy and paste the command line

### System
- OS X
- 10.11
- Firefox
- 44.0.2

A simple fix would be to have something like ``cd Downloads; shasum -a 256 elementaryos-0.3.2-stable-i386.20151209.iso``

Edit: this also affects Linux/Ubuntu obviously as it uses the same command.

**Comment by aleksandar-todorovic** [comment]
Why not something like:

    cd ~/Downloads && shasum -a 256 elementaryos-0.3.2-stable-i386.20151209.iso

Make sure that the terminal emulator will move to the Downloads folder regardless of in which directory the terminal is in and just `shasum` it, all in one command.

**Comment by linusbobcat** [comment]
Not sure why I forgot how the command line works, but ``shasum -a 256 ~/Downloads/elementaryos.iso`` would also work.

**Comment by btkostner** [comment]
We could `ls` the downloads folder, `grep` for any elementary isos, then `shasum`, but I think that might be a little too much.  Not sure about how the wildcards work on osx and the shell

**Comment by lewisgoddard** [comment]
I think we should use `shasum -a 256 ~/Downloads/elementaryos-0.3.2-stable-i386.20151209.iso` and add a note about the user changing the directory as needed. "assuming you have saved the download in your downloads folder..."

**Comment by danrabbit** [comment]
That would probably be the most straightforward and simple. I think it's relatively safe to assume that's gonna work for most people
