### ISSUE TITLE
bitesized bugs link includes fixed and in-progress bugs

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1090]
On Get Involved

Probably not useful for people looking for things to do to see things that were already done or being worked on by other people. We need to add the same filters as are on bountied issues and make sure in-progress and fixed issues aren't shown

**Comment by divayprakash** [comment]
Working on it

**Comment by divayprakash** [comment]
2 issues - 
* Any reason for not opening the bountied bugs page in a new tab?
* Why doesn't the bountied bugs page include the `NEW` and `INCOMPLETE` statuses?

**Comment by divayprakash** [comment]
@danrabbit  I've made a PR but it just includes exactly what you asked for and not the questions I asked above. Ping me and I'll fix it with those issues too if you need.

**Comment by lewisgoddard** [comment]
Any external link should open in a new page, there's a script that does it automatically.

**Comment by divayprakash** [comment]
The present HTML code for the links section on the 'Get Involved' page is -

```html
<a class="button flat" href="" target="_blank">Bitesized Bugs</a>
<a class="button flat" href="">Bountied Bugs</a>
```

So you see the `a` tag for the bountied bugs page doesn't have a `target` attribute to open it in a new window/tab.

If required, I can update the PR with this code.

**Comment by danrabbit** [comment]
It doesn't really make sense to show new or incomplete status bugs to someone who is looking for work. These status mean the issue is unconfirmed and it is not ready to be worked on
