### ISSUE TITLE
Sub-header in "Get Involved" page is not center aligned.

### ISSUE THREAD

**Issue by kushalpandya** [elementary/mvp#1091]
### Expected behavior

Sub-header on _Get Involved_ page which says *"Everything that we make is 100% open source and developed collaboratively by people from all over the world. Even if you're not a programmer, you can get involved and make a difference."* is not perfectly center aligned.

### Actual behavior

The enclosing element is following standard `p` tag style of `text-align: left`, which makes it look like following in my 1080p monitor.

![Elementary.io Get Involved Page](http://i.imgur.com/D668w3d.png)

### Steps to reproduce the behavior

1. Visit [Elementary.io Get Involved](https://elementary.io/get-involved) page on a Desktop browser
2. Notice how sub-header text is aligned.

### System information

- **Operating system**: Microsoft Windows
- **Operating system version**: 7
- **Browser**: Google Chrome
- **Browser version**: 49 (64 Bit)

**Comment by divayprakash** [comment]
Working on it

**Comment by kushalpandya** [comment]
@divayprakash I can make a pull-request in case you wanna offload some work. :smiley:

**Comment by divayprakash** [comment]
@kushalpandya Sure go ahead!

**Comment by snwh** [comment]
This is by design. All other `p` tags following a header are also left-aligned.

**Comment by lewisgoddard** [comment]
I suppose there is a difference between a paragraph following a header and a sub-heading. We need to decide which one this is.

**Comment by kushalpandya** [comment]
@lewisgoddard Yes and if it is a sub-header within `hero` component, center alignment will look more appropriate, again, just a personal opinion.
