### ISSUE TITLE
Add to contribution guidelines that you should squash your commits

### ISSUE THREAD

**Issue by codygarver** [elementary/mvp#1094]
I just absolutely wrecked the beautiful commit history of a branch by not squashing a branch's commits before merging it to master. This must never happen again.

**Comment by fitojb** [comment]
GitHub now lets repo owners to squash before merging: https://github.com/blog/2141-squash-your-commits

**Comment by btkostner** [comment]
Enabled for this repo, closing issue. Thanks @fitojb
