### ISSUE TITLE
Add Slingshot screenshot to Learn the Basics section

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1096]
At https://elementary.io/docs/learning-the-basics#applications we detail Slingshot, but we don't show a screenshot. It'd be nice to plop a screenshot (from a stock install) there.

**Comment by divayprakash** [comment]
Working on it

**Comment by suhasdarsi** [comment]
Can you assign that to me ? I would like to work on that

**Comment by btkostner** [comment]
GitHub doesn't allow assigning people outside of elementary, but if you want to work on it go ahead.

Sorry voldyman about assigning you, slip of the finger.

**Comment by suhasdarsi** [comment]
Thank you :)

**Comment by lewisgoddard** [comment]
@suhasdarsi Any progress on this?

**Comment by suhasdarsi** [comment]
Almost done a little busy with my end exams that's all

On Sat, Apr 23, 2016, 12:20 AM Lewis Goddard <notifications@github.com>
wrote:

> @suhasdarsi <https://github.com/suhasdarsi> Any progress on this?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/elementary/mvp/issues/1096#issuecomment-213550785>
>
-- 

[image: Way2Do] <http://www.way2do.net>

[image: Twitter] <https://twitter.com/suhas_darsi> [image: Facebook]
<https://www.facebook.com/SuhasDarsi666> [image: Google +]
<https://plus.google.com/+Suhasdarsi666> [image: LinkedIn]
<https://in.linkedin.com/pub/suhas-darsi/104/57/766> [image: Instagram]
<https://instagram.com/suhas_darsi/> [image: Pinterest]
<https://www.pinterest.com/darsisuhas666/> [image: Github]
<https://github.com/suhasdarsi> [image: Quora]
<https://www.quora.com/Suhas-Darsi-1>

Suhas Darsi / Co founder
darsisuhas666@gmail.com / +919000725505

Way2Do
+919000725505
Flat no 106,Plot no 34,Motherdairy CGHS ltd
www.way2do.net

**Comment by ajish097** [comment]
could i take it up in case suhasdarsi is busy ?

**Comment by suhasdarsi** [comment]
Yeah sure

On Tue, May 3, 2016, 8:10 PM ajish097 <notifications@github.com> wrote:

> could i take it up in case suhasdarsi is busy ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elementary/mvp/issues/1096#issuecomment-216550198>
>
-- 

[image: Way2Do] <http://www.way2do.net>

[image: Twitter] <https://twitter.com/suhas_darsi> [image: Facebook]
<https://www.facebook.com/SuhasDarsi666> [image: Google +]
<https://plus.google.com/+Suhasdarsi666> [image: LinkedIn]
<https://in.linkedin.com/pub/suhas-darsi/104/57/766> [image: Instagram]
<https://instagram.com/suhas_darsi/> [image: Pinterest]
<https://www.pinterest.com/darsisuhas666/> [image: Github]
<https://github.com/suhasdarsi> [image: Quora]
<https://www.quora.com/Suhas-Darsi-1>

Suhas Darsi / Co founder
darsisuhas666@gmail.com / +919000725505

Way2Do
+919000725505
Flat no 106,Plot no 34,Motherdairy CGHS ltd
www.way2do.net

**Comment by ajish097** [comment]
I am a newbie to opensource . If somebody could help me, it would be a great help .

**Comment by suhasdarsi** [comment]
It's a simple bug fork the project first then git clone it. Now familiarize
yourself with the folder structure and that's all you are good to go. Fix
it and submit a pull request

On Thu, May 5, 2016, 7:33 PM ajish097 <notifications@github.com> wrote:

> I am a newbie to opensource . If somebody could help me, it would be a
> great help .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elementary/mvp/issues/1096#issuecomment-217162993>
>
-- 

[image: Way2Do] <http://www.way2do.net>

[image: Twitter] <https://twitter.com/suhas_darsi> [image: Facebook]
<https://www.facebook.com/SuhasDarsi666> [image: Google +]
<https://plus.google.com/+Suhasdarsi666> [image: LinkedIn]
<https://in.linkedin.com/pub/suhas-darsi/104/57/766> [image: Instagram]
<https://instagram.com/suhas_darsi/> [image: Pinterest]
<https://www.pinterest.com/darsisuhas666/> [image: Github]
<https://github.com/suhasdarsi> [image: Quora]
<https://www.quora.com/Suhas-Darsi-1>

Suhas Darsi / Co founder
darsisuhas666@gmail.com / +919000725505

Way2Do
+919000725505
Flat no 106,Plot no 34,Motherdairy CGHS ltd
www.way2do.net

**Comment by ajish097** [comment]
I have cloned it into my local machine but can't seem to find my way around.. could you give me more insights ?

**Comment by cashhh** [comment]
Now that you cloned the repo you have your own copy of all the files in this repo. Once you make changes you want, create a pull request to have your changes looked at.

**Comment by ajish097** [comment]
Found a directory named sligshot inside images but can't figure out what to do with it ..

**Comment by danrabbit** [comment]
Hey @ajish097 it sounds like this might be a bit over your skill level. I would recommend checking out [Codecademy's course on git](https://www.codecademy.com/learn/learn-git) and also their [courses on web development](https://www.codecademy.com/learn/web). Fixing this issue requires being able to use git and modify the contents of a web page :)

**Comment by lewisgoddard** [comment]
You'll also need to know how to do intermediate markdown.

**Comment by ajish097** [comment]
Thank you all for the guidance .. Just one more thing , could anyone tell me in which file i need to make the changes ?

**Comment by ajish097** [comment]
![screenshot - 05072016 - 10 29 02 pm](https://cloud.githubusercontent.com/assets/16611719/15093358/4f133dfc-14a3-11e6-96cb-e55cc0d5db52.png)


is this okay?

**Comment by lewisgoddard** [comment]
[`/docs/learning-the-basics.md`](https://github.com/elementary/mvp/blob/master/docs/learning-the-basics.md)

**Comment by lewisgoddard** [comment]
@ajish097 Most of our screenshots don't include a background, apart from a transparent drop-shadow rendered by the system. Try using a tool like screencloud.

**Comment by cashhh** [comment]
![slignshot_icons](https://cloud.githubusercontent.com/assets/14286119/15093824/abef2470-1460-11e6-9c31-4f2be1e8c36c.png)
![slingshot_categories](https://cloud.githubusercontent.com/assets/14286119/15093825/abef982e-1460-11e6-9e6f-2a71ef4bd560.png)

I have these made..is this what your looking for?

**Comment by ajish097** [comment]
how about this one ?   
![preview1](https://cloud.githubusercontent.com/assets/16611719/15097728/b61a5004-1542-11e6-8362-3ac50854c488.png)
@lewisgoddard @cassidyjames @cashhh @danrabbit

**Comment by lewisgoddard** [comment]
We tend not to have an image right after a header. Instead, try nesting it immediately after the first paragraph there, and file a pull request.
