### ISSUE TITLE
Translation not applied?

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/mvp#1101]
This translation was done almost a month ago: https://www.transifex.com/elementary/elementary-mvp/translate/#es/index/78914004

Yet, the elementary.io/es/ site keeps showing "*Purchase* elementary OS" instead of "*Comprar* elementary OS".

**Comment by lewisgoddard** [comment]
This is my big "update translations script. Apparently I haven't run it in a while, but will do now.

```
git checkout master
git pull
.tx/prepush.sh
tx push -s
git checkout -b translations-update
rm lang/* -Rf
tx pull -a
php backend/translations-checker.php
git add -A
git commit -am "Update all Translations, even new ones"
git push --set-upstream origin translations-update
git checkout master
```
