### ISSUE TITLE
pt_BR 'Learning The Basics' page is not working

### ISSUE THREAD

**Issue by liddack** [elementary/mvp#1105]
Hi, I'm a member of the site's Brazilian translators team on Transifex.
So, when I try to open the pt_BR 'Learning The Basics', I simply get a blank page with the `nav` bar.

URL: https://elementary.io/pt_BR/docs/learning-the-basics

And I'm sure this issue is recent, since the page worked well two weeks ago.
Thank you all for the great job.

**Comment by lewisgoddard** [comment]
This is now fixed, as we have dramatically improved the translations validator. There are still a few minor flaws, but the page is now accessible.
