### ISSUE TITLE
Use Etcher for Mac ISO instructions [$20]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1107]
It sounds like Linusbobcat doesn't have any intentions to evolve his project into a proper app. Avi linked me to this project and I tested it. It's really simple and it works well. http://www.etcher.io

![etcher](https://cloud.githubusercontent.com/assets/7277719/14401887/9469eba6-fdd5-11e5-9e98-1cbb9f4eca43.png)

--
[Bounty Link](https://www.bountysource.com/issues/32769634-use-etcher-for-mac-iso-instructions)

**Comment by lewisgoddard** [comment]
Just for Mac, or Windows too?

**Comment by danrabbit** [comment]
I haven't personally tested on Windows. If someone can verify that it works well on Windows, I think it would make sense to use the same app. It's much simpler than Rufus for sure.

**Comment by KeitIG** [comment]
Just tested it, works well on Windows

**Comment by cassidyjames** [comment]
Honestly if we're comfortable with it, we could just recommend for everyone. Then we don't need many per-OS instructions at all.

**Comment by danrabbit** [comment]
I personally didn't know how to get the Linux version to run. Otherwise I would agree it would be simpler to have the same directions across the board

**Comment by lewisgoddard** [comment]
On linux you have to extract the archive, then run the executable as root. It's really nowhere near as comfortable as Unetbootin, and that's not a high bar.
