### ISSUE TITLE
Docs - HIG - H1, H2 etc. link to themselves

### ISSUE THREAD

**Issue by tvw** [elementary/mvp#1114]
### Expected behavior

No links at all, which reference themselves. This is completely pointless and confusing, because the page contains more of such dead links than real links, which make the real ones the needles in the haystack.

### Actual behavior

The headers are shown like beeing linked to somewhere else but only reference themselves.

### Steps to reproduce the behavior

1. Goto eg. [https://elementary.io/de/docs/human-interface-guidelines#avoid-configuration](https://elementary.io/de/docs/human-interface-guidelines#avoid-configuration)

**Comment by cassidyjames** [comment]
This is a feature to make it very easy to link someone to the specific section of the page.

**Comment by KeitIG** [comment]
And to facilitate links sharing. I guess we can close this.

**Comment by fabianthoma** [comment]
As already said above this is actually a feature to make linking to sections easier, so I'm closing this as a opinion type report.

**Comment by tvw** [comment]
I see, though it is counterintuitive, that an anchor is a link to itself at the same time because this way you cannot see a difference between anchors and links. Not good from a usability standpoint. But maybe this is a side effect of two decades of poor web design, where every site styles its ui-elements different and urges the user to search for links by moving the mousepointer over texts and treat everything as a link, which seem to be or could be a link.

As always: if you have to explain it, you did something wrong ;-)

**Comment by KeitIG** [comment]
Where @tvw is right, it's that those titles shouldn't be links in titles, but just titles. But it's one of the wiki's "feature", so I'm not sure it's a good idea to change that.

**Comment by danrabbit** [comment]
As stated above the need to be links so they can be easily shared. You can right click and "copy link". On mobile we don't have elements hide and show on hover, so we can't restrict things to a hover state
