### ISSUE TITLE
Foreign words in Spanish guide aren’t displaying in proper italic

### ISSUE THREAD

**Issue by fitojb** [elementary/mvp#1130]
### Expected behavior

Real italics.

### Actual behavior

Ugly automatic slanting.

https://elementary.io/es/docs/human-interface-guidelines#container-widgets
![captura de pantalla de 2016-04-24 23-52-31](https://cloud.githubusercontent.com/assets/554953/14774103/ba16f57a-0a77-11e6-85fd-b7a2a796a4da.png)

Compare with the real italic face from Google Fonts:
![captura de pantalla de 2016-04-24 23-56-40](https://cloud.githubusercontent.com/assets/554953/14774139/468d2362-0a78-11e6-8311-7da822a3c020.png)

I cannot simply remove the markup from the translation and ignore the fact that it’s a foreign word: the Spanish language grammar mandates this kind of words to be italicized. The alternative would be to wrap it in «guillemets», but that would look clunkier.

**Comment by KeitIG** [comment]
Well, it just shouldn't be in italic if I follow the other languages. I'm pretty sure "widget" is not spanish (oh wait !), but is it a word you can use every day ? or should it be in "guillemets" ?

**Comment by fitojb** [comment]
@KeitIG *Widget* is not a word used in everyday speech—only software developers would use it. Even so, you’re thinking on English conventions of stopping treating foreign words as “foreign” when they’re sufficiently integrated in the layman’s lexicon. It doesn’t work like that in Spanish: either you fully adapt the word to Spanish’s orthography and morphology rules (for example, *mitin* comes from *meeting*, but it isn’t written in italics or wrapped in quotation marks because it’s adapted), or you preserve the loanword’s foreign spelling and pronunciation, but then you have to italicize it or, as I mentioned, enclose it in quotation marks.

This whole thing is a matter of respecting typographical syntax (*ortotipografía*), and I’m aware that many translators simply won’t bother.
