### ISSUE TITLE
Burndown chart is too-aggressively cached

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1131]
### Expected behavior

I hop over to https://elementary.io/get-involved#desktop-development and see the up-to-date burndown chart. It's not heavily cached since it's a daily-updating chart.

### Actual behavior

I hop over to https://elementary.io/get-involved#desktop-development and see a burndown chart from several days ago, or whenever I first visited the page. It seems to be cached, forcing a hard refresh to get the new graph.

### Steps to reproduce the behavior

1. Go to https://elementary.io/get-involved#desktop-development
2. Wait a few days
3. Revisit https://elementary.io/get-involved#desktop-development in the same browser

### System information

- **Operating system**: elementary OS 
- **Operating system version**: Freya and Lokii
- **Browser**: Chrome
- **Browser version**: 50.0.2661.86 (64-bit)
- **Enabled Browser Extensions**: Pocket

**Comment by cassidyjames** [comment]
Not sure what our options are here since the caching is client-side. Can we set a header for the page/js that it's changed or something?

**Comment by lewisgoddard** [comment]
I think we need to set an exclusion in Cloudflare so that this shouldn't be cached for more than a day, or set a header for the location in the Nginx config. https://support.cloudflare.com/hc/en-us/articles/200169266-Does-CloudFlare-honor-my-Expires-and-Cache-Control-headers-for-static-content-
