### ISSUE TITLE
Missing `alt` attributes

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1135]
We're missing `alt` attributes on several images across the site. I'll try and audit and list them here.

- [x] [All support page icons](https://github.com/elementary/mvp/blob/73a5c13857f4e84b9cf314948fe8cdf18d4f409c/support.php#L20)
- [x] [homepage.js](https://github.com/elementary/mvp/blob/2545d0b667f563ef667895b8ec95de40804181d2/scripts/homepage.js#L173)
- [x] [Developer page svgs](https://github.com/elementary/mvp/blob/73a5c13857f4e84b9cf314948fe8cdf18d4f409c/developer.php#L13)
- [x] [HIG SVGs](https://github.com/elementary/mvp/blob/42b0bee55d8e4c01d45e77ba6a21c65c5b14bf11/docs/human-interface-guidelines.md#L664)

**Comment by jbull328** [comment]
I had a problem with this PR and needed to close It. I will work on adding the alt attributes and submit a new PR.

**Comment by lewisgoddard** [comment]
@cassidyjames Do you want to review this? #1140

**Comment by jbull328** [comment]
Yes, it is ready for review.
