### ISSUE TITLE
Sidebar expanding is significantly delayed

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1136]
### Steps to reproduce the behavior

1. Go to a docs page like https://elementary.io/docs/human-interface-guidelines
2. scroll down

### Expected behavior

The sidebar expands as the navbar retreats

### Actual behavior

The navbar retreats and the sidebar expands some time later

### System information

- **Browser**: Chrome 
- **Browser version**: 50.0.2661.86 (64-bit)

**Comment by lewisgoddard** [comment]
`/scripts/docs/main.js:132`

**Comment by lewisgoddard** [comment]
This is a combination of script timeouts being excessive, and that if you scrolled a little but not fully past the header, the move is not yet started. The same thing happens with the footer.
