### ISSUE TITLE
Code Style Guide: Use = instead of set

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1148]
We should mention that we use "=" instead of "set" in code. For example:

`set_can_focus (false);` should instead be `can_focus = false;`

**Comment by FleetAdmiral** [comment]
@danrabbit Hey , could i take this up?

**Comment by btkostner** [comment]
@FleetAdmiral you don't have to ask, just work on it and submit a PR when you are done :wink:

**Comment by FleetAdmiral** [comment]
@btkostner Ah , i'm new around here so didn't know that , i'll keep it in mind 👍

**Comment by btkostner** [comment]
@FleetAdmiral No problem. We appreciate your help make the docs better. Let us know if you have any questions.

**Comment by FleetAdmiral** [comment]
@btkostner Could you perhaps help me by mentioning in which files i need to add this too? I looked about and i'm guessing i should add it under docs/code/reference. Is that correct?

**Comment by btkostner** [comment]
Yep, that is correct. Somewhere under the `Code Style` section.
