### ISSUE TITLE
Installation Guide Flash Drive Requirement Incorrect

### ISSUE THREAD

**Issue by ibnesayeed** [elementary/mvp#1161]
The installation document says:

```
You'll need a USB flash drive with at least 1 GB of free space and a program called UNetbootin.
```

However, the downloaded ISO is more than 1GB.

**Comment by lewisgoddard** [comment]
This actually occurs within two places in the document, and is correct in the other.

**Comment by ibnesayeed** [comment]
@lewisgoddard are you talking about the `1 GB of system memory (RAM)` occurrence or is there any other place?

**Comment by lewisgoddard** [comment]
It appears incorrectly under Ubuntu and Windows. It is correct under OS X.

**Comment by ibnesayeed** [comment]
Shouldn't it also be changed in translation files of all languages such as `lang/uk/docs/installation.json`?

**Comment by ibnesayeed** [comment]
Oops! closed by mistake, hence opened again.

**Comment by lewisgoddard** [comment]
Language files are not updated until a fix has been finalized and merged. It may then take several days for translations be propogate.
