### ISSUE TITLE
Prep for loki-beta1

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1175]
- [x] ISOs to CDN/distribution network
- [x] Section on Developer page
  - [x]  Button to download beta
  - [x] Link to "release notes" which is the announcement blog post
- [ ] Publish blog post

**Comment by cassidyjames** [comment]
Waiting for ISOs, but the section on the dev page could be started

**Comment by cassidyjames** [comment]
Assigning @danrabbit for design/copy :)

**Comment by lewisgoddard** [comment]
I presume I will be doing the Distribution Network stuff, and can get the links for whoever wants to do the developer page section.

**Comment by btkostner** [comment]
attaching to loki beta PR #1179
