### ISSUE TITLE
update developer preview image with grid background

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1188]
What it says on the tin. Update the preview image to mimic the hero

**Comment by cassidyjames** [comment]
PNG version available at http://bazaar.launchpad.net/~elementary-os/elementaryos/prerelease-stuff-package/view/head:/backgrounds/purpleprint.png

**Comment by ddxor** [comment]
Can you provide some more specific requirements @danrabbit? I am struggling to figure out exactly which image needs to be changed here.

**Comment by danrabbit** [comment]
Hey @ddxor this report is referring to the opengraph/twitter preview image
