### ISSUE TITLE
Use a "Pay Later" button/link instead of $0

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/mvp#1196]
Instead of making the user put in a non-obvious $0 (very unlikely that someone would do that on their own, since you don't pay $0 for anything), have a "Pay Later" button under "Purchase elementary OS". 

This would spawn a modal window that let's the user put in their email address and date options like tomorrow, next week, etc, and never (this would replace the $0). 

We'll then automatically email them on the day they specified that they said they wanted to pay at that date.

Worth a shot at making the design clearer?

**Comment by danrabbit** [comment]
Since upwards of 90% of people (I think it's still 99%) put in 0, I don't think lack of clarity there is an issue

**Comment by lewisgoddard** [comment]
Would also make it seem like you have to pay at some point to keep using it, which is not the case.

**Comment by bigfatbird** [comment]
On the other hand there is no statistics how many people don't even download it because of lack of knowledge. Your 99% might only be the people informed you have to insert 0 to get a free download. The other crowd does not get tracked

**Comment by danrabbit** [comment]
I don't think raw adoption without any means to provide support for those users is something that should be optimized for. If growth (regardless of revenue) were a goal, sure then that's something to think about. But that doesn't sound like a recipe for sustainability.

**Comment by bigfatbird** [comment]
I was not voting for something, just that you read the wrong out of those statistics, maybe! ;)

**Comment by lewisgoddard** [comment]
@bigfatbird We can estimate to a certain amount by tracking the number of people who open a payment dialog but end up not downloading at all, assuming they were confused about how to download without paying. For reference, <1% of people do that.

A lot of people do seem to open the payment dialog without realising that that isn't just a big download button, but if >99.5% of those people figure it out, it's not a major issue.

**Comment by bigfatbird** [comment]
I do this from time to time, too. And I downloaded for free more than once, but on the other hand donated via paypal. :P Statistics lie - they always do. 

It’s for sure a mixed analysis, but still!

**Comment by bigfatbird** [comment]
Idea: Why not add a info on top of the download, or a short comment if one hovers over the button?

**Comment by danrabbit** [comment]
I think it's fairly clear from analytics that people not knowing how to download for free is not an issue. Getting people to pay is the issue ;)

**Comment by duesee** [comment]
I asked the same in #1230. You are introducing an additional barrier for no good reasons. For me and some family members (willing to try an alternative OS) this felt somewhat "sneaky".

**Comment by danrabbit** [comment]
There is a good reason and that reason is that we need to eat. We need to pay rent. We're people too. We also need to pay for hosting and for hardware to test on and for travel to conferences, etc etc. elementary OS is not free to produce. It costs money to develop it, so we must raise money to sustains its development. So far, pay-what-you-want is the best compromise we've made to pull in a halfway decent amount of revenue while still allowing over 90% of people to download for free.

**Comment by duesee** [comment]
I know and pay-what-you-want is perfectly fine. The point I wanted to make is that people who are actually willing to pay will do so anyway. Maybe instantly, maybe months later, maybe never.

But starting such a user/dev relationship with tricky paymant dialogs harms this relationship from the beginning and will, on the run run, lower the probability to get users pay recurrently for a good software product.

Ubuntu does it far better in my opinion: http://www.ubuntu.com/download/desktop/contribute?version=16.04.1&architecture=amd64

If someone wants to pay she/he will. If not -- just download it for free (or not). No tricks.
