### ISSUE TITLE
Create master list of URL redirects

### ISSUE THREAD

**Issue by codygarver** [elementary/mvp#1211]
We should be able to permalink things predictively without having to know the final URL.

For example, I need to put a link to the final release notes for Loki in the ISO metadata in order to close a bug on the milestone, but I don't know what the actual URL tumblr will give me for the post because it is not generated until the post becomes public.

I would like to be able to map a pretty, predictable elementary.io URL to a destination URL that's probably gonna be ugly.

**Comment by lewisgoddard** [comment]
This is basically already done in [`Nginx.conf`](https://github.com/elementary/mvp/blob/master/nginx.conf):


    location = /loki-release-notes {
        return 301 http://blog.elementary.io/post-id-here;
    }
