### ISSUE TITLE
Store link appears on the Blog, but not on the main website.

### ISSUE THREAD

**Issue by aldoiljazi** [elementary/mvp#1217]
Basically the link to the **Store** on the navigation bar appears on the **Blog** page (Tumblr) and not on the **main website**.

**Blog:**
![blog](https://cloud.githubusercontent.com/assets/12599754/17031753/62fd32b2-4f7e-11e6-8bfb-df08abaaa804.jpeg)

**Main Website:**
![site](https://cloud.githubusercontent.com/assets/12599754/17031754/6308ea12-4f7e-11e6-8787-0021abdab7ea.jpeg)

**Comment by cassidyjames** [comment]
Fixed on the Tumblr theme.
