### ISSUE TITLE
"Reference for Granite link doesn't take the user to the Granite reference

### ISSUE THREAD

**Issue by aldoiljazi** [elementary/mvp#1226]
### Expected behavior

Describe what you expected to happen.

### Actual behavior

Describe what actually happened, being specific about how this differs from your expectations.

### Steps to reproduce the behavior

1. 
2. 
3. 

### System information

- **Operating system**: 
- **Operating system version**: 
- **Browser**: 
- **Browser version**: 
- **Enabled Browser Extensions**:

**Comment by btkostner** [comment]
I'm going to assume you mean the "Reference for Granite" on our developer page. Assuming that's the case then it's due to this issue https://github.com/flobrosch/valadoc-org/issues/56.

Please confirm this is in fact you are referring to.

**Comment by aldoiljazi** [comment]
Yes that is what I am referring to...
