### ISSUE TITLE
Style the <kbd> tag

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#123]
Add CSS for the `<kbd>` tag (keyboard key).

**Comment by fabianthoma** [comment]
![screenshot 16](https://cloud.githubusercontent.com/assets/1058124/5879307/5d89e3b4-a32e-11e4-8b51-c5e1d480ae3d.jpg)
Can we reuse this? Any opinion on the design @danrabbit ?

**Comment by danrabbit** [comment]
Yeah I'm cool with re-using that style :)
