### ISSUE TITLE
Simplify download: remove 0$ amount hack.

### ISSUE THREAD

**Issue by duesee** [elementary/mvp#1230]
### Expected behavior

Push download button to start download...

### Actual behavior

Setting the amount to 0$ in order to start download hack neeeded...

I thought elementary should be accessible to everyone. I doubt that this "hack" is what you should expect from day-to-day users.

I understand that this may be a "motivator" for people to actually pay some amount (to support your great work, btw), but nonetheless this casts a very poor light on elementary.

**Comment by lewisgoddard** [comment]
I think this was best covered in #1196, even if it's not a total duplicate.
