### ISSUE TITLE
Create a style for appstream subdomain

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1231]
Looks like it's totally unstyled at the moment which means the graphs don't even show. We should fix that. Probably can steal Debian's as a base https://appstream.debian.org/static/css/style.css

**Comment by btkostner** [comment]
We can create a new style but the reason that page looks unstyled right now is due to ssl certificates. If you use https instead of http you should see the real styles.

**Comment by danrabbit** [comment]
Ah I can confirm that. Chrome complains that the cert is invalid and warns you not to visit the site

**Comment by lewisgoddard** [comment]
Is this issue not now resolved? https://appstream.elementary.io/ Our certificate validates for me fine.
