### ISSUE TITLE
use a photograph for "hero" image on the home page

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#126]
the notebook-hero is kind of a placeholder and the screenshot is of a dev system.

At minimum we should get a screenshot from a clean iso.

I'd still like to get a nice photograph instead of an illustration.

**Comment by vassilevsky** [comment]
What should be on the screenshot?
What resolution (screen size) is optimal?

**Comment by danrabbit** [comment]
Updating the bug title and removing from "aftermath" milestone.
