### ISSUE TITLE
Rename `hook/store` folder

### ISSUE THREAD

**Issue by btkostner** [elementary/mvp#1290]
The `hook/store` folder should be changed to `hook/printful` considering printful should be the only service accessing it. 

This is bikeshedding at it's best.

**Comment by lewisgoddard** [comment]
This is also part of #1282 (sort of)

**Comment by lewisgoddard** [comment]
This is on hold until after Loki.

**Comment by lewisgoddard** [comment]
Marking this as a duplicate, we should do this all together.
