### ISSUE TITLE
Icon URL broken

### ISSUE THREAD

**Issue by inad9300** [elementary/mvp#1296]
### Expected behavior

See properly all the icons in the [Houston page](https://houston.elementary.io/).

### Actual behavior

The Soup icon is pointing to a [non-existing image](https://elementary.io/images/developer/soup.svg). On the [Development page](https://elementary.io/developer) works nice since the [image's URL](https://elementary.io/images/icons/48/preferences-system-network.svg) is different.

### Steps to reproduce the behavior

1. Access https://houston.elementary.io/
2. Scroll down

### System information

- **Operating system**: elementary
- **Browser**: Firefox

**Comment by btkostner** [comment]
That whole page is outdated and needs to be updated before Houston goes to beta.

Also, please report Houston issues at https://GitHub.com/elementary/Houston
