### ISSUE TITLE
Create a pretty URL scheme to sign up for mailing lists

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#1311]
We just created a mailing list for package releases here: http://elementary.us14.list-manage.com/subscribe?u=6815d99e5893b4e213cdb00d2&id=db4e281d16

We want a pretty URL we can share for that. I think we should be forward thinking and assume we'll have more than one list so we should have some kind of scheme for this. Not sure what it should be

**Comment by codygarver** [comment]
`/release-list`?

**Comment by danrabbit** [comment]
Would it be better to do something list `/lists/release`?

**Comment by danrabbit** [comment]
Actually this is an interesting URL. It shows the archive with a signup button http://us14.campaign-archive1.com/home/?u=6815d99e5893b4e213cdb00d2&id=db4e281d16

**Comment by btkostner** [comment]
I would avoid using `release` for packages. We should use something like `/lists/package` for package releases and then we could add a press kit release signup at `/lists/release`.

**Comment by lewisgoddard** [comment]
Do we really want to have so many lists we need a scheme?

**Comment by danrabbit** [comment]
Well we already have two. I don't think it's unreasonable to believe we might have more in the future

**Comment by lewisgoddard** [comment]
What I'm saying is they can be named individually, is there a need for a standardised format?

**Comment by danrabbit** [comment]
Well I think it would make it convenient and predictable. less to think about when naming and it's like reserving a namespace so you know there won't be any collisions with pages in the future.

**Comment by lewisgoddard** [comment]
If you can settle on a name I can close this in seconds.

**Comment by danrabbit** [comment]
I like Blake's suggestion. Let's do `/lists/packages`
