### ISSUE TITLE
Block scrolling while modal is open

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#132]
We need to block scrolling of the body while the modal is open. This includes:

* Two finger touchpad
* 'touchmove'
* arrow keys
* 'mousewheel'
* Clicking and dragging the scroll bar

I have a bit of code from the ChiFi site, but for some reason it doesn't seem to work with leanModal

```
$('.dialog-background').on('scroll touchmove mousewheel', function (e) {
    e.preventDefault();
    e.stopPropagation();
    return false;
});
```

**Comment by lewisgoddard** [comment]
This works for me to stop scrolling with my touchpad, but not the scrollbar or arrowkeys because it doesn't try to catch those.

```
$('.js-target-jquery-leanmodal-overlay').on('scroll touchmove mousewheel', function (e) {
    console.log('Scroll Ignored');
    e.preventDefault();
    e.stopPropagation();
    return false;
});
```
