### ISSUE TITLE
Update screenshots in Installation Guide

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#134]
They're pretty old.

Maybe we can get @cassidyjames to do screenshots for latest Ubuntu?

FYI: the new screenshot tool can take transparent screenshots: https://code.launchpad.net/screenshot-tool

**Comment by emersion** [comment]
Just made new screnshots

Transparent screenshots don't work well with window corners ([see here](https://cloud.githubusercontent.com/assets/506932/5903418/dda2275a-a581-11e4-9612-40c7ab39c78c.png)), so I made [screenshots without transparent background](https://cloud.githubusercontent.com/assets/506932/5903449/0b6075d4-a582-11e4-9746-638e67897ac9.png) too.
