### ISSUE TITLE
Drop instructions for burning a CD

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#135]
* The experience in the live environment is much better from USB, especially with regard to boot times.
* Installation is faster.
* The media isn't destroyed/wasted after a burn.
* More modern computers don't have CD drives. New ones that do can still boot from USB.

**Comment by maliktunga** [comment]
@danrabbit Hmm that's a bit off-topic, but are you guys working on an elementary OS Live USB creator? I saw screenshots of UNetbootin and that's quite ugly (personal opinion).

**Comment by snwh** [comment]
Maybe, I had mocked one up and I seen slight progress towards it's creation. ;)
https://raw.githubusercontent.com/snwh/mockups/master/elementary/apps/boot-creator/boot-creator.png

**Comment by maliktunga** [comment]
@snwh Hmm it should be "64-bit" ;-)

That's insanely great. However, it's obviously designed for elementary OS and is fit for any Linux distro. What I would have in mind would be a program for Windows and OS X focused solely on installing elementary OS. A bit like, uh, Ubiquity I think?

**Comment by cassidyjames** [comment]
@maliktunga we've talked about it! It's something we'd love to do down the road, but can't devote official resources to at the moment.

**Comment by cassidyjames** [comment]
@maliktunga of course, if someone started an open source project, we could probably give some design direction. :)

**Comment by RoryJ-** [comment]
I've been working on making @snwh's mockup real, although I've been fairly busy and still haven't done much on the backend. I'll put it up on launchpad for others to contribute as soon as I it actually does something.

![screenshot_from_2015-01-20_20_21_49](https://cloud.githubusercontent.com/assets/6921585/5915904/037256cc-a603-11e4-9d38-e1a9b743303a.png)

**Comment by emersion** [comment]
Maybe we could first select "Creating a USB" by default instead of "Burning a CD"?
