### ISSUE TITLE
Real boot instructions for Mac [$15]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#136]
I dunno who wrote the nonsense that's currently there but it's just as easy to boot on a Mac as a PC. Pop in your USB, hold down option during boot, and select your boot disk. nbd.

**Comment by caketable** [comment]
I wrote a copy for Booting elementary OS on Macs during the (failed) documentation sprint a while back, but it got rejected. Here's the document. I tried to make it close to the Luna Boot Instructions.   https://docs.google.com/document/d/1iILdxwABYV3FqjFKrxERRU-qSsMJU8oDmULv-0uIUSk/edit?usp=sharing .
