### ISSUE TITLE
Add close class to dialog buttons

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#145]
the "close" class was set up in leanmodal, but never added to the dialog buttons

It might make more sense to just have .modal.button be the close class?

**Comment by lewisgoddard** [comment]
Will we always want every `.modal.button` to close the modal? Seems more specific to add a simple utility class instead and be a little clearer.

**Comment by danrabbit** [comment]
I'm not sure why we'd have a button in a dialog that doesn't exit it. But I'm cool with just adding .close to the other buttons for now
