### ISSUE TITLE
Fix recommended specs

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#152]
It sounds like we want to revisit the recommended specs to be a little more concise and clear. The goal should be to provide a recommended spec and then basically say "You can try it on less, but you're on your own".

A concern we have is that if we list some insane bare minimum spec, someone will try to run that and then complain about performance. We want to be safe, yet reasonable here.

**Comment by lewisgoddard** [comment]
I think this is becoming part of bug #320.

**Comment by danrabbit** [comment]
In defense of this report, #320 is kind of a group report. It should probably be marked as invalid and split up into individual complaints.
