### ISSUE TITLE
"Create a USB" sounds weird

### ISSUE THREAD

**Issue by maliktunga** [elementary/mvp#159]
Pedantry moment!

I saw on the Installation page the use of expressions such as "Create a USB". That's not very… correct to say. One should not confuse USB with USB flash drive or, in more familiar terms, a "USB stick". USB is a communication protocol.

I admit there's one thing bugging me and that is the fact "Live USB" is deemed correct in Linux terms.

**Comment by danrabbit** [comment]
Part of the problem here is we have a width constraint on mobile. But I think we want to drop CD directions, so that might go away. But generally I agree that we should be talking about creating a bootable disk less than talking about creating a usb drive :p

**Comment by maliktunga** [comment]
@danrabbit Oh right, I didn't realize mobile devices are a restraint. How about "Create a Live USB"?

**Comment by danrabbit** [comment]
yes "Creating a Live USB" fits. Sorry for the late response.

**Comment by maliktunga** [comment]
The pull request https://github.com/elementary/mvp/pull/192 fixes the issue.
