### ISSUE TITLE
Use an active voice

### ISSUE THREAD

**Issue by maliktunga** [elementary/mvp#164]
Instead of "elementary is designed to…", it could be "We designed elementary to…"

That would be more direct and inviting. That wouldn't start a revolution, but it's a small enjoyable detail.

**Comment by maliktunga** [comment]
Also, instead of

> In the following window, choose the ISO you just downloaded, and make sure the right disk drive with a blank CD in it is selected.

in could be

> In the following window, choose the ISO you just downloaded, and make sure you select the right disk drive with a blank CD in it.

**Comment by davidak** [comment]
>We designed...

i like that.
