### ISSUE TITLE
Link to the blag

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#17]
elementaryos.tumblr.com

Down with the Journal. Long live the Blog.

**Comment by cassidyjames** [comment]
When we roll this out, do we want it to be blog.elementaryos.org or something on a subdomain? I feel like that looks a bit more professional and lets people know they're for sure on an official elementary site.

It's easy to set up in Tumblr. :)

**Comment by danrabbit** [comment]
Yeah, I think blog.elementaryos.org would make sense and I'd much rather share that link than a tumblr link :p
