### ISSUE TITLE
Fix SVG logos size on IE9

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#177]
![191_selection](https://cloud.githubusercontent.com/assets/506932/5889235/7fcb0ac6-a41d-11e4-8309-8921b133e645.png)

**Comment by lewisgoddard** [comment]
Apparently this is a [known issue](http://caniuse.com/#feat=svg), and can be stopped in several different ways. Either we need to export the SVGs to the correct size by default, or use the CSS hack below. We will also need a class added conditionally for older IE browsers.

```
<!--[if lt IE 10]><body class="ieL"><![endif]-->
<!--[if gte IE 10]><!--><body><!--<![endif]-->
```

```
/* IE < 10 */
.ieL img[src*=".svg"] {
    width: 100%; 
}
/* IE >= 10 */
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    img[src*=".svg"] {
        width: 100%; 
    }
}
```

1. http://codepen.io/tomByrer/pen/qEBbzw?editors=110
2. https://gist.github.com/larrybotha/7881691

**Comment by lewisgoddard** [comment]
I'm not sure how well that would work considering we currently target the height, not the width.

**Comment by danrabbit** [comment]
It would probably be the simplest just to resize the canvas such that they are all 30px tall.

**Comment by emersion** [comment]
Yes, I think that's the best option. That CSS hack is very ugly.

I'll do this tomorrow.
