### ISSUE TITLE
Spin buttons should not be shown.

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#178]
The spin button ([beta](http://beta.elementaryos.org/)) currently increases the custom amount by `1ct`. `50ct` or `1$` would be more sensible.

**Comment by lewisgoddard** [comment]
You should not be seeing spin buttons. They should be hidden.

**Comment by lewisgoddard** [comment]
Apparently they are not hidden in Firefox, but Chrome is good.

**Comment by quassy** [comment]
Sorry, yes this was Firefox and is fixed now.
