### ISSUE TITLE
To use contractions or not to use contractions?

### ISSUE THREAD

**Issue by maliktunga** [elementary/mvp#183]
I noticed in the Installation page that there's a frequent blend of contracted and non-contracted language. For example, "we'll" versus "we will".

> […] **we'll** cover system requirements […]

> If you **haven't** already, **you will** need […]

I think it should come to the following decision: should the Installation page feel more like formal documentation or like a friendly tutorial? For the former, complete words are preferred while for the latter, contractions are preferred.

**Comment by danrabbit** [comment]
It should sound natural. I dunno about you, but I don't always use contractions when I'm talking. It depends on what I'm saying. So I'm not certain we should have a hard rule that everything must be contracted. But that contractions are okay and we should use them where it feels natural.

**Comment by maliktunga** [comment]
@danrabbit I see. So you're rather on the "let's make it friendly without being pedantic about it" side?

**Comment by cassidyjames** [comment]
@maliktunga yes, the "elementary voice" tends to be human, natural, and friendly. Not pedantic. We're free to mix contractions and non-contracted phrases as long as it is clear and sounds natural.
