### ISSUE TITLE
add bitcoin payment option

### ISSUE THREAD

**Issue by Matadoer** [elementary/mvp#187]
Would love to see a Bitcoin or even a Litecoin/Dogecoin payment option.

Also, the site mentions nowhere that you can download for free.
Feels kind of dishonest.

**Comment by lewisgoddard** [comment]
You can download for free just by putting a zero in the custom box, but it's not something we want to encourage.

**Comment by danrabbit** [comment]
Looks like Stripe is working on this upstream. Not sure it makes sense for us to add Yet-Another-Payment-Method instead of just waiting for their work to be completed. https://stripe.com/bitcoin

**Comment by cassidyjames** [comment]
I agree with @danrabbit; let's let Stripe take care of it, especially since they're already beta testing it.

**Comment by cassidyjames** [comment]
I went ahead and requested a beta invite/announcement email when the feature is ready. If there's anything I need to do down the road in the Stripe dashboard, I can take care of it.

**Comment by Matadoer** [comment]
@lewisgoddard BitPay and other merchant services (probably stripe too) convert the Bitcoin to fiat so you don't have to worry about price fluctuations. As for not encouraging people to download your product for free, I find this to be an ugly statement. If the product is good enough, people will support you and throw money your way.

Some people will have no clue that you can put 0 into the box and this is uncomfortably deceiving. I downloaded ElementaryOS for free to try it out, and it should be encouraged to download for free imo because it is after all it is Linux and a FREE, OPEN alternative to other proprietary operating systems.

"elementary has a single goal: to provide the best possible experience for our community. We're driven by a desire to be better, not by a paycheck. Contributors aren't profit-maximizers, they're purpose-maximizers." - Taken directly from your website.

I was thinking of throwing you guys a donation, but I'll wait until you guys have A) support for bitcoin and B) a download for free button

**Comment by lewisgoddard** [comment]
@Matadoer Converting bitcoin doesn't erase price fluctuations, it just means we don't have to worry about holding something that is fluctuating. The amount we get for say 0.05 bitcoins is still going to vary incredibly.

As for the "available for free", you'll need to talk to @danrabbit. The design spec I've seen for this site so far (informal only) is heavily encouraging a financial contribution. FYI they can't (legally) and shouldn't (morally) be called donations because elementary isn't a charity, or even a not-for-profit.

**Comment by davidak** [comment]
i have send bitcoins to ind.ie via stripe, it works very good!
you could talk to them to exchange experiences.

https://ind.ie/fund

if you want to provide privacy you should support bitcoin as an alternative to creditcard/paypal/...
also if you wouldn't use bitcoins, i do and a lot of other people too.
actually i have more money in BTC than € ;)

and i don't have a credit card! i don't need a credit, i have money.
using credits to pay is the first step to get indebted. i don't recommend it to anyone!

i like to test products before i pay for them. so a 0 button or "try first" maybe would leads to more users.

**Comment by davidak** [comment]
@cassidyjames have you actively contacted Stripe, told them about our project and asked to get the option to process bitcoins?

like i wrote in another issue, https://ind.ie/fund has bitcoin support with Stripe and it works well.

**Comment by quassy** [comment]
[Bitcoin with Stripe](https://stripe.com/bitcoin) seems to be open to the public now.

**Comment by davidak** [comment]
yeah

**Comment by cassidyjames** [comment]
@lewisgoddard I tried just adding the data attribute to the Stripe script tag (as documented [here](https://stripe.com/docs/guides/bitcoin)) but that didn't work in my local branch. Are we not using Checkout that way? :stuck_out_tongue:

**Comment by lewisgoddard** [comment]
"To process live Bitcoin payments, you need to enable the live Bitcoin API on your account" https://dashboard.stripe.com/account/bitcoin/enable

**Comment by cassidyjames** [comment]
Already did that.

**Comment by lewisgoddard** [comment]
I think you'll need to talk to @fabianthoma, he did most of the Stripe integration, I haven't even got receipts working yet.
