### ISSUE TITLE
Warn about AdBlockPlus

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#204]
This might be unnecessary so feel free to "Won't Fix"

AdBlockPlus apparently blocks social icons. That means the links to our social networks and the inline tweets and any time else we might want to use those and who knows what other possible icons (FA has a warning about it http://fortawesome.github.io/Font-Awesome/icons/ )

So it might be worth serving a small infobar that says something like "This site doesn't have any ads, but your adblocker may accidentally block other images used on this website. Please add us to your white list". Or such

**Comment by emersion** [comment]
Result when activating the filter:

![192_selection](https://cloud.githubusercontent.com/assets/506932/5906813/fa62626a-a59a-11e4-9c4e-b7af6eed598a.png)

**Comment by 19kestier** [comment]
I could easily create an info bar that does this, but if an AdBlock user like me has the Antisocial list activated, we probably also have the AdBlock Warning Removal list activated. Therefore, an info bar would be ineffective.
![screenshot 2015-01-29 at 8 04 09 pm](https://cloud.githubusercontent.com/assets/4749568/5969592/bcac2dce-a7f3-11e4-8b90-f81c26068dea.png)

**Comment by 19kestier** [comment]
The Fanboy's Annoyances list also has the same effect on the website...

**Comment by aleksandar-todorovic** [comment]
Taken from [here](http://fortawesome.github.io/Font-Awesome/icons/):

> Apparently, Adblock Plus can remove Font Awesome brand icons with their "Remove Social Media Buttons" setting. We will not use hacks to force them to display. Please report an issue with Adblock Plus if you believe this to be an error. **To work around this, you'll need to modify the social icon class names**.

Why not doing that? It's easier than working around Adblock and the design will remain as more simple if there is no need to show this warning message.

And as Fanboy said [here](https://adblockplus.org/forum/viewtopic.php?f=2&t=25444&p=107979&hilit=font+awesome#p107979):

>Don't use the Social list then, the elements/fonts are heavily used. And will remain blocked.

**Comment by danrabbit** [comment]
Closing this issue then. I don't care. If you intentionally break the web that's your problem.

**Comment by 19kestier** [comment]
Nah, there's got to be something we can do to fix this. Lots of users brave enough to switch OSes will have AdBlock with all filters on. A broken website makes a bad impression.

**Comment by danrabbit** [comment]
Intentionally forcing things to be shown that a user has intentionally blocked is arguably the definition of "evil".

**Comment by 19kestier** [comment]
Yes, but the Antisocial filter is for ridding of privacy invading social "share" buttons. And the Fanboy's Annoyances filter is to rid of annoying web content. Links to Twitter aren't "annoying". Can we file a bug with the lists?
I don't see reasonable grounds (based on what the filters are for) on why links to Twitter should be blocked.

**Comment by aleksandar-todorovic** [comment]
@19kestier I already traced bugs on the Adblock forum related to Font Awesome. Fanboy clearly stated in a link I provided in the previous comment that he won't fix this. Reporting it again has no point.

I agree with @danrabbit, this issue is pretty much over.
