### ISSUE TITLE
Add chart to "Get Involved" page

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#206]
Chart mockup: https://github.com/elementary/mvp/blob/2fd27b3a1b7ad1daa3aa5408c56f5d633f504787/images/get-involved/stats.svg

Source code: https://github.com/KeitIG/elementary-stats

Notes:
* ~~#196 needs to be merged in master before~~
* We should save data as JSON instead of using a CSV parsing library
* Maybe switch from Google Charts to another library? (something like http://bonsaijs.org/ ? Being Google-dependent seems not to be a good thing, and Google Charts seems like a quite heavy lib)
* Clean up `update.php`, remove ugly things like `exec("grep ...");` :-P
* Use Launchpad HTTP API instead of parsing raw HTML (https://launchpad.net/+apidoc/beta.html#milestone-searchTasks)

**Comment by lewisgoddard** [comment]
BonsaiJS isn't really a charting library. ChartJS seems mmuch more well suited, and we can just load the core and bar modules.
