### ISSUE TITLE
Link quote authors on get involved

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#208]
either wikipedia or maybe if there exists novelty twitter accounts?

**Comment by emersion** [comment]
* https://en.wikipedia.org/wiki/Federico_Fellini
* https://twitter.com/paulcookson
* https://en.wikipedia.org/wiki/Dieter_Rams
* https://twitter.com/RalphJohnson
  https://en.wikipedia.org/wiki/Ralph_Johnson_%28computer_scientist%29
