### ISSUE TITLE
Add torrent option

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#21]
People gonna complain about "where my torrent download at"

**Comment by snwh** [comment]
I think using a magnet link would be more modern of us.

**Comment by cassidyjames** [comment]
I remember a really awesome p2p-powered download thing you could embed into the browser, but don't remember what it was called.

I think it technically used torrents behind the scenes, so might even speed up the download for everyone. I'll try and find it to see if it makes sense. :)

**Comment by snwh** [comment]
Isn't that a bit over-complicated. Surely those who want to torrent it would have a torrent client, I don't think in-browser torrenting would add anything.

**Comment by cassidyjames** [comment]
Fwiw here's the project we looked at: https://github.com/feross/webtorrent

There are several advantages, even for normal downloaders. Chiefly that it's insanely fast.

**Comment by cassidyjames** [comment]
@danrabbit would it make sense to have an alternative downloads page where we offer up the 32-bit and torrent downloads? I think simpler is better when it comes to the main download.

**Comment by danrabbit** [comment]
Yeah if it's just a couple options it could also be done in a dialog

**Comment by lewisgoddard** [comment]
What trackers do we want? These are the big five plus my analytics tracker.
```
https://ashrise.com:443/announce
udp://open.demonii.com:1337/announce
udp://tracker.ccc.de:80/announce
udp://tracker.istole.it:80/announce
udp://tracker.openbittorrent.com:80/announce
udp://tracker.publicbt.com:80/announce
```

**Comment by cassidyjames** [comment]
Cody Garver has managed torrents for us in the past. I'm not sure what he used.

**Comment by aroman** [comment]
personally i really do not think webtorrent is worth it unless implementing it is as easy or easier than doing a regular torrent with public trackers.

**Comment by cassidyjames** [comment]
Per convo with @danrabbit, we're gonna have an alternative downloads page where we offer torrents and possibly 32-bit. On the home page we're just offering a pay-what-you-want (including $0) 64-bit download button that (if > $0) triggers the Stripe checkout.

**Comment by cassidyjames** [comment]
Will be handled by #89
