### ISSUE TITLE
Use an actual screenshot of Scratch on Get Involved

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#212]
We can take a sweet transparent screenshot with lp:screenshot-tool (not crappy gnome-screenshot that draws ugly drop shadows).

**Comment by lewisgoddard** [comment]
I actually like the drop-shadows, they make it stand out from the page. I also like the not-quite-scratch look that is so close to the original design, look neater.

**Comment by danrabbit** [comment]
No, shadows are good. But good shadows are good. Gnome screenshot whatever draws some ugly-ass offset shadows instead of using the actual real shadows from the window manager.

**Comment by lewisgoddard** [comment]
Okay, so we wouldn't be getting rid of them completely?

**Comment by emersion** [comment]
A friend reported that the wrong font is used on the screenshot. He's using Safari on a Mac, open sans font not installed. Seems that the font is loaded for the webpage, but not for the svg image. Using an actual screenshot would solve this issue. Another possibility is to load the font in the svg too.

![received_10203466699291701](https://cloud.githubusercontent.com/assets/506932/5908521/b5442304-a5a8-11e4-9c08-07a8adf146b6.jpeg)

**Comment by danrabbit** [comment]
Ah fuck I forgot about HiDPI though. What we can is just convert the text to paths. But we'll need to keep it as an SVG for HiDPI
