### ISSUE TITLE
Map on "get-involved" page missing countries

### ISSUE THREAD

**Issue by csmart** [elementary/mvp#216]
The map of the World (translations.svg) in the get-involved page (http://beta.elementaryos.org/get-involved) is missing a number of countries and thus looks a little strange.

For example, New Zealand and various Pacific islands, Indonesia, PNG, Philippines, Japan, Taiwan, Madagascar, The Falklands, Iceland, Sicily, the UK and Ireland plus whatever that boomerang shaped island is off the north of Russia, Serverny Island, that's it.

Tasmania is also missing from Australia. I mean I can understand leaving off New Zealand, but Tasmania!? :-)

**Comment by snwh** [comment]
And the island off the coast of eastern Canada (where I'm from) :O
