### ISSUE TITLE
Laptop image too big in beta.elementaryos.org?

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/mvp#218]
This is how I see http://beta.elementaryos.org/:

![captura de pantalla de 2015-01-26 23 24 49](https://cloud.githubusercontent.com/assets/6054951/5912437/a9fd1d02-a5b2-11e4-9418-1eab2f882d6d.png)

My screen has a resolution of 1920x1080. Perhaps the image is a bit too big?

**Comment by danrabbit** [comment]
Nope, that's how it's supposed to be ;)
