### ISSUE TITLE
Current pages should be differentiated in navigation.

### ISSUE THREAD

**Issue by donadigo** [elementary/mvp#228]
Currently, "Get Involved" label is seen even on the /get-involved page.

**Comment by lewisgoddard** [comment]
I am going to change your bug into a super-bug. Currently every page loads the same header template and will display every link, even to itself. While this is consistent, there is no indication of what the current page is.

**Comment by TrivediKavit** [comment]
We can check if the current URL Slug matches the href of the link. If so, we can add class of "active" to it and style it, say for example:

```
li.active
{
     border-bottom: 1px solid #C8D0D0;
     font-weight: 700;
}
```

**Comment by cassidyjames** [comment]
Gonna let @danrabbit sign off on design before we implement this.

**Comment by quassy** [comment]
How about a two pix stripe with the blue from a:focus (08c) or with grey from text color (333)?

    nav > .nav-content > ul > li > a.active {
        border-top: 2px solid #08c;
    }

(Code only for a quick test. Needs a bit more than this as this shifts text to the bottom, which it should not.)

**Comment by cassidyjames** [comment]
Honestly, the `:active` styling looks good to me. It doesn't change weight and it's something we already have in the CSS, so it'd be a matter of appending the selector with an `.active` class to the rule.

**Comment by lewisgoddard** [comment]
@cassidyjames I don't see an `:active` that applies to `nav a`, do you mean this?

```
nav > .nav-content > ul > li > a:focus {
    text-decoration: none;
    color: #08c;
    fill: #08c;
}
```

I'm sure with the current link-looping in JavaScript anyway we can append one class.

**Comment by danrabbit** [comment]
I'm not sure I'm super entirely convinced this is a problem that needs addressing. Each page is pretty different in its content. The solution of using the active/focus style kind of works but it looks weird, imo.

**Comment by quassy** [comment]
@lewisgoddard The `:active` selector applies when the mouse is pressed down on a link but not yet released yet. Here an `.active` *class* should be added to be able to differentiate the menu item whose page is currently displayed.

**Comment by lewisgoddard** [comment]
@quassy Unfortunately the testing page doesn't work so well because of root relative links, you'll need a local copy to test.

**Comment by lewisgoddard** [comment]
Abandoned my [pull request](https://github.com/elementary/mvp/pull/657#issuecomment-103952341), no design input and it's not a major issue. I personally think it makes the site look worse and doesn't actually help the user.

**Comment by lewisgoddard** [comment]
Given the various backgrounds we use, this doesn't look likely to be fixed, and I doubt it's a major source of confusion. If #ux say it doesn't need fixing we don't fix it, it's not like it's a single standardized tab structure where we can change the background too, it wasn't even that noticeable.
