### ISSUE TITLE
Add a screenshot

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#23]
Need at least one sexy screenshot of the default Freya desktop.

Might be interesting to do a shot with a few different sexy computers running Freya.

Would be very warm and indie of us to have kind of a set up "natural" shot like the new photos on system76

**Comment by cassidyjames** [comment]
@danrabbit want me to bribe @kazen117 into taking shots of System76 computers running elementary OS? :wink:

**Comment by cassidyjames** [comment]
I have a Galago UltraPro and this laptop as well: 
![samsung_530u3c_startseite](https://cloud.githubusercontent.com/assets/611168/5683583/49cc9234-97e6-11e4-8ae4-ef69b00d276f.jpg)

Also, my wife has this guy:
![np700z5c-s04ca-rc-unit](https://cloud.githubusercontent.com/assets/611168/5683635/b0caead0-97e6-11e4-8e9e-501ff0bb551c.jpg)

**Comment by danrabbit** [comment]
@cassidyjames if @kazen117 is who did the shots for you guys, hell yes!

**Comment by cassidyjames** [comment]
@danrabbit indeed. We'll see. Idk if she has free time/will work for free (or food). :D

**Comment by kazen117** [comment]
hi do what now?

**Comment by snwh** [comment]
One could attempt to crowdsource this. "Show us your sexy shots of your laptop running elementary".

**Comment by danrabbit** [comment]
@kazen117 We could use a nice picture for our homepage depicting elementary OS Freya. I think it'd be cool if we could get something with a similar feeling as what you've done for elementary OS. Specifically, something that looks organic, like a real person's desk. A Sable would probably be cool :)

**Comment by Akryum** [comment]
Hi, I made a mockup of home page there: http://bytevortex.net/share/elementary/elementary.html (elementary screenshot is a placeholder).
What do you think?
Also, different variants (for ex with headphones and other colors) looping with a neat transition effect would be great.

**Comment by KeitIG** [comment]
@Akryum Looks great :) here are a few advices: I don't like the orange, maybe you should color it with a "more elementary" color. Quotes looks good. And the laptop image does not look natural.

**Comment by danrabbit** [comment]
I'm not really a fan of using an illustration instead of an actual photo. Also, this page doesn't fly on mobile.

In the future, please use branches/PRs so we don't junk up reports with a review

**Comment by Akryum** [comment]
Well, I'm not into photography. :/
(Sorry for posting in the wrong place.)
