### ISSUE TITLE
jQl in a separate js file

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#231]
Which we will `<?php include('scripts/jql.js'); ?>` in pages. This will prevent us from copying each time the code.

**Comment by lewisgoddard** [comment]
Really it should be moved to the header template, and then scripts loaded by it afterwards. I think it's being used on nearly every page anyway, so it should ust be sitewide. I suppose this is an alternative.

`include './scripts/jql.js'`

**Comment by emersion** [comment]
Fixed in #239.
