### ISSUE TITLE
"Contribute by doing these things" sounds awkward

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#233]
I don't know how we should reword it, but this wording on the get-involved page feels awkward to me. :smile:

**Comment by danrabbit** [comment]
Yeah it does sound awkward and more pushy than inviting

**Comment by lewisgoddard** [comment]
COuld it not just be "Contribute", or "Get Involved" ?

**Comment by danrabbit** [comment]
I feel like the word "Contribute" is a demand/expectation. But I also want to avoid having a title that mirrors the link name if possible

**Comment by xd1936** [comment]
Something inviting, like "How you can help:", perhaps?

**Comment by lewisgoddard** [comment]
We could just remove that header altogether, maybe just have a little empty space under the chart.

**Comment by danrabbit** [comment]
@lewisgoddard yeah I'm +1 to that plan. Remove it and just have space.
