### ISSUE TITLE
Optimise PNGs

### ISSUE THREAD

**Issue by Matthew-Kirk** [elementary/mvp#236]
The image of Elementary OS on a laptop that you see on the beta homepage (http://beta.elementaryos.org/images/notebook.png) is unoptimised and far larger (file size-wise) than it needs to be. 

It is approximately 606.6 KB. Running it through [TinyPNG](https://tinypng.com/) reduces that down to 196.3 KB with no perceptible loss of quality.

What's particuarly fingers-on-chalkboard is that the screenshot of Elementary has JPEG artefacts already visible on it. So that means the author created a JPEG screenshot and then placed it inside a PNG. Perhaps just re-saving it as a JPEG would be best?

**Comment by cassidyjames** [comment]
PNGquant is super handy as well. Latest version available for elementary here: https://packages.debian.org/jessie/pngquant

**Comment by cassidyjames** [comment]
Making this include all PNGs currently on the site, as we can get well over 50% size reduction on most of them with no quality loss.
