### ISSUE TITLE
i can't close the download popup

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#238]
that should be possible by clicking next to it in the darkened space or hitting `ESC`.

maybe also like the payment popup.

**Comment by danrabbit** [comment]
This is intentional. You can only close it by selecting a download link. This is to prevent a case where you've paid and then you accidentally close the dialog.

**Comment by eddiemoore** [comment]
Could you save that the user has paid already so if they do close it then they don't need to go through the payment again?

**Comment by davidak** [comment]
@eddiemoore when you have paid, you will get an e-mail with a download link. https://github.com/elementary/mvp/issues/34

**Comment by eddiemoore** [comment]
What about the people that decide to not pay anything and click download? If they then decide that they want to pay then the only way to do that is to reload the whole page.

**Comment by lewisgoddard** [comment]
@eddiemoore Once they have clicked a download button, the modal closes and they can continue to browse the page and play if they wish.

**Comment by eddiemoore** [comment]
@lewisgoddard and if they decide not to download at that point?

**Comment by lewisgoddard** [comment]
Don't get me wrong, I added the original close button in that was later removed, but the idea is that if people have payed, we don't want them not downloading.

**Comment by eddiemoore** [comment]
I get that. But what about the people that decide not to pay anything?

**Comment by lewisgoddard** [comment]
I suppose we could add a conditional, especially as it could lead to them paying next time. I also think this could change once we are sending receipts with download links. @danrabbit What do you think?
