### ISSUE TITLE
Always show twitter icons on mobile

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#240]
We should probably always show the twitter icons next to the pull tweets when the user is on a mobile device. Because there's no hover on mobile and you can't tell it's tweetable otherwise.

**Comment by danrabbit** [comment]
Eh I dunno man. I feel like that would be really intrusive. I like that it's kind of hidden away. It's there, but it's not like in your face all the time.

**Comment by cassidyjames** [comment]
In the sprit of mobile first: the best approach is probably always showing them, then using a media query to hide then on devices above a certain size.

**Comment by danrabbit** [comment]
I'm extremely -1 on showing a bunch of twitter logos all over the site all the time. This isn't essential functionality for the site. If you really insist on every feature on desktop has to be available to mobile, then we should just remove this feature.

**Comment by cassidyjames** [comment]
Ah yeah that's a good point. I didn't think about having them all visible at once and feeling like they were everywhere. 

Marking as wontfix to leave 'em as-is.
