### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by eddiemoore** [elementary/mvp#244]
Currently if i go to **/asdasd** it just says ```File not found.```
Looks like the router.php file will need to updated for this.

**Comment by fabianthoma** [comment]
Actually this is the fault of nginx, which does routing on the server, the router.php is just for local testing on developers machines, I'll fix it next time I log on to the server

**Comment by lewisgoddard** [comment]
We don't have a "nice" not found error page at all. This needs to be designed, added, and then configured in both Nginx _and_ the router file.

**Comment by cassidyjames** [comment]
Umm guys? We have http://beta.elementaryos.org/404. It just needs to be set up server-side.

**Comment by lewisgoddard** [comment]
"Go to Home Page" ?

That is the most un-elementary phrasing I have ever seen.

Also, when the hell was that added!?

**Comment by cassidyjames** [comment]
Alright, developer-side is taken care of with the router.php. Just waiting for @fabianthoma to update the nginx config server-side and we'll be all set.

**Comment by fabianthoma** [comment]
Done, 404 now works
