### ISSUE TITLE
Re-base site on the Laravel platform or at least use Composer

### ISSUE THREAD

**Issue by nicekiwi** [elementary/mvp#245]
http://laravel.com/ - THE PHP FRAMEWORK FOR WEB ARTISANS.

Awwe, no frameworks. :( still Laravel is one of the most powerful and simplest to use. (built in support for Stripe Payments) 

At the very least Composer is a must to manage any PHP project like this. 
https://getcomposer.org/ - Dependency Manager for PHP

**Comment by danrabbit** [comment]
No sorry, we don't want to add unnecessary frameworks

**Comment by nicekiwi** [comment]
That is unfortunate in the case of Composer as it itself is not a framework and can offer a great deal to keeping the project simple. Seriously its not just another tool its a basic building block of modern PHP applications. 

http://culttt.com/2013/01/07/what-is-php-composer/
