### ISSUE TITLE
Add Android multitasking header bar colour

### ISSUE THREAD

**Issue by RoryJ-** [elementary/mvp#259]
Reference: http://www.androidpolice.com/2014/11/10/chrome-v39-on-lollipop-supports-custom-multitasking-headerstatus-bar-colors-with-a-simple-html-tag/

**Comment by cassidyjames** [comment]
@danrabbit mentioned we probably want this to be a template variable so we can change it on certain pages. Should be implemented like the page title variable.

**Comment by cassidyjames** [comment]
@danrabbit what do we want on the get-involved page?

**Comment by danrabbit** [comment]
@cassidyjames I believe that's #3e4e54
