### ISSUE TITLE
Support landing page [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#264]
We need a Support page that tells users where they can go to have their support questions answered.

Ideally this includes links to documentation and communities.

**Comment by Happy-Dude** [comment]
Idling in the #elementary freenode IRC channel, I notice that many users come in from the site assuming that the channel is like instant messaging and their questions will be answered *immediately*. 

That is definitely not the case and can unfortunately seem misleading to new users. I believe there should be a separate **Support** and **Community** landing pages and the IRC channel should be a link in the community page. Or, if anything -- community links should be combined with "Get Involved."

**Comment by cassidyjames** [comment]
@maffity said she's gonna take a crack at this. :D

**Comment by cassidyjames** [comment]
Trying to figure out what links should go on this page. 

1. Google+ Community
2. Subreddit
3. Installation docs
4. Maybe an FAQ?

I think setting up sub-pages at /support/ would make the most sense for things like the installation docs and FAQ. Then in the future we can keep any other support docs there.

**Comment by cassidyjames** [comment]
@Happy-Dude: we've all but abandoned IRC for support for this reason.

**Comment by cassidyjames** [comment]
Oh, it might actually be a good idea to link to Launchpad for reporting bugs.

**Comment by maffity** [comment]
This is what I'm thinking of doing.
![2015-01-31](https://cloud.githubusercontent.com/assets/10751728/5989972/a92e6760-a958-11e4-9055-7d237ffffbcd.jpg)

**Comment by danrabbit** [comment]
So my major problem with "FAQ" is... are those actually frequently asked questions? How do we know that? What if that question is not frequently asked anymore? With the "Answers" system we're pulling these automatically and it updates based on votes.

I do think it's valid to try to separate filing a bug from asking a support question, but I'm unsure how to really present that to someone. It seems to be a major point of confusion for people. What would suck though is to have more people filing bugs that actually aren't bugs. I'm unsure if we should be asking non-developers to file bugs.

I also think it might be good to make it clear that Google+ and Reddit are communities somehow and not a form of support that comes from elementary employees.

**Comment by cassidyjames** [comment]
@danrabbit the nice thing about an "FAQ" or "common questions" page is that there _are_ questions we get **all the time** via email, twitter, or sometimes random bug reports/Launchpad questions. We can put those there if we think they're common enough to warrant it.

**Comment by cassidyjames** [comment]
Here's where @maffity and I are. Feedback?

![screenshot from 2015-01-31 17 13 40](https://cloud.githubusercontent.com/assets/611168/5990406/8b180eb6-a96c-11e4-8452-83ac6d89ad72.png)

**Comment by cassidyjames** [comment]
(also, it's up at http://beta.elementaryos.org/branch/support/support)

**Comment by nod0n** [comment]
Hi, new here. I'm in the #elementary channel to. Was chatting whith @Happy-Dude about the channel. I think, we can link the channel in the support section, but as community channel. Like: "Elementary community channel: #elementary". I think i little note is nice, because I like IRC. ;)

**Comment by KeitIG** [comment]
@danrabbit didn't you say you were about to close IRC, or to not support it anymore ? I don't remember well.

**Comment by danrabbit** [comment]
Yeah we've had a lot of negative feedback about IRC. The biggest problem is that it isn't a guaranteed real-time chat. People come in expecting immediate responses.

**Comment by ApfelUser** [comment]
What about [Gitter](https://gitter.im)?
