### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by isdampe** [elementary/mvp#267]
Hi all,

Here's a few suggestions and/or my two cents

1. Move some of the scripts out of head down to just before /body. (Will help page load speed)
1. Start using a CSS pre-processor like SASS or LESS. (Will save a bunch of time writing stylesheets)
1. Utilize a tool like [autoprefixer](https://github.com/postcss/autoprefixer) for better browser cross compatibility
1. Considering wrapping functions homepage.js and other inside $(document).ready(); to be DOM safer and allow flexibility in script positioning.
1. Uglify / concatenate script files (Also could probably wait for production)
1. Minify css for delivery, I.e setup Grunt or Gulp for building. (This can probably wait for production)

**Comment by danrabbit** [comment]
OP, we don't accept group reports. Please break down each one of your issues into a separate report.

**Comment by isdampe** [comment]
You should reflect upon your contributing "rules" in README.md to prevent volunteers wasting time.

**Comment by lewisgoddard** [comment]
The readme currently states "Issues for *individual* actionable items, or bugs [...]" (emphasis mine).
