### ISSUE TITLE
Online tour?

### ISSUE THREAD

**Issue by isdampe** [elementary/mvp#268]
Perhaps building something like the [Ubuntu online tour](http://www.ubuntu.com/tour/en/) would be beneficial to give users a basic feel of ElementaryOS before downloading?

I'd be happy to build something along these lines in spare time if it's of interest?

**Comment by danrabbit** [comment]
Sorry, I don't think this is a good idea. It's unrealistic to expect this could possibly be a 1:1 representation. We have a Live CD/USB environment for testing purposes.

**Comment by isdampe** [comment]
... Would be beneficial to give users a ___basic feel___ of ElementaryOS ___before downloading___

I think you missed the point completely.

**Comment by danrabbit** [comment]
My point is that such a demo would be inaccurate and we already provide a mechanism for trying before installing.

**Comment by isdampe** [comment]
___before downloading___

I understand where you're coming from, but live CD / USB is inconvenient and also just as slow / inaccurate.
