### ISSUE TITLE
protect visitors privacy

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#276]
A website visitor should not get tracked by any 3rd party company.

For example, Google Analytics should not be used. There are good alternatives like [Piwik](http://piwik.org/).
It is self-hosted, can be configured to anonymize the IP (GA can also, but i don't trust it) and accept [Do Not Track](https://en.wikipedia.org/wiki/Do_Not_Track)-Headers.
The setup is easy (needs PHP and MySQL), the update works with one-click.

This topic came up in https://github.com/elementary/mvp/issues/93 and also affects https://github.com/elementary/mvp/issues/94 .

**Comment by KeitIG** [comment]
What would NSA/CIA/FBI/blabla care about a small website like ours ? Well, if a guy really cares about his privacy, let him use TOR and GA won't be able to "compromise" him.

My opinion of course.

(ps: the idea is good huh, but we'd better focus on features instead of that)

**Comment by lewisgoddard** [comment]
If elementary were served with a request that required we turn over users data, as a US-based company they would have no choice but to either comply or legally challenge such a request. Any semi-experienced server admin knows it is basically impossible to stop logging, especially when you go through so many devices in between.

I don't think Piwik provides any additional protection from snooping governments. Google have a far better legal team to be fighting that battle for us. That said, I do think we should honor DNT Headers, something I can implement shortly.

**Comment by 19kestier** [comment]
Using Google Analytics and Stripe JS (probably non-free). OMGUbuntu said this site would be "privacy minded". I don't think you're living up to that headline. @davidak piwik +1. Piwik is amazing!

**Comment by lewisgoddard** [comment]
I don't think you can process payments with a totally free product. Credit card processing is inherently proprietary.

**Comment by davidak** [comment]
you *can* process bitcoin payments with free software. (you also can use propriatary software from some provider so you don't need bitcoind on the server)
credit card would be my last choice. i even don't have one!
sepa would be a good alternative in europe. startnext uses it for example.

**Comment by lewisgoddard** [comment]
You expect us to remove Credit and Debit card processing? Especially within the US? Where most of elementarys money comes from?

"Freedom, at the point at which it inhibits utility, becomes restrictive."

**Comment by KeitIG** [comment]
I do not have bitcoins and I will never have.

But I do have a credit card. Elementary's users are not geeks, or devs or whatever, elementary os was designed to be easily accessible without any particular knowledge. The new website is going that way.

**Comment by davidak** [comment]
i don't say you should remove credit cards!

it is ok if i don't have to use it. i know most people have either a credit card or paypal so supporting this is good to reach most people. same for sepa in europe. (in germany only a few people have credit cards)

it would be really great if you will support bitcoin to have an alternative that gives one more privacy.

supporting only credit card will restrict some people.

**Comment by lewisgoddard** [comment]
Stripe are adding support for bitcoins, which shouldn't require any changes from us.

**Comment by danrabbit** [comment]
So it sounds like the actionable item on this report is to not load analytics if the client specifies Do Not Track

**Comment by lewisgoddard** [comment]
@danrabbit #282 does that.

**Comment by lewisgoddard** [comment]
Seeing as #282 is now closed and DNT headers are honored, can this issue be closed?
