### ISSUE TITLE
Understanding the Architecture/Philosophies.

### ISSUE THREAD

**Issue by nunomaduro** [elementary/mvp#277]
It is hard for me to understand why there is not a PHP framework to support this front-page, such as Laravel 5. In the near future add features can become more complicated.

**Comment by KeitIG** [comment]
We wanted to minimize tools used for the website. "M" ov "MVP" is "minimum" :) And not everyone know how to dev apps with Laravel (I do).

Otherwise I agree with you, it would save us some time (translation, rooting...)

**Comment by agauniyal** [comment]
Php framework to support frontend!!
