### ISSUE TITLE
Automatically Preprocess Assets

### ISSUE THREAD

**Issue by choyan** [elementary/mvp#279]
Currently the Front-end assets doesn't have any structure. I want to propose some points.

1) In the master folder we will have a folder named `assets/`
2) `assets/` folder will contain 2 folder named `dist/` and `production/`
3) `production` folder will contain all the necessary assets needed during production time. Like: unminified css, js and images
4) `dist/` folder will contain only distributed assets. Every asstes will be minified and concatenated.
5) These minification, concatenation and compression will be done by automated system like Gulp.

**Comment by cassidyjames** [comment]
Hey @choyan. I use gulp daily in dev and production for @system76, but it's probably overkill for this project at this point. A huge reason we're structuring the site as we are is to significantly lower the barrier of entry. Adding preprocessing raises that barrier extremely high for little tradeoff of a project this size.

**Comment by cassidyjames** [comment]
That said, if you notice assets that could be better optimized, feel free to file bugs.
