### ISSUE TITLE
Add a new way to contribute to elementary: support activities

### ISSUE THREAD

**Issue by PerfectCarl** [elementary/mvp#284]
Support activities are also a way to help elementary: 
   - **providing help in forums/reddit/g+**: without endorsing officially people having a doc that tackle the "how to provide helpful support for elementary" would be nice
   - **testing applications** and chiefly merge proposals is sorely needed. We can use (and train) people to be roughless and efficient testers. Using and updating [test documents](https://github.com/PerfectCarl/elementary-files-testing) is the way to prevent regressions as much as possible.
   -  **writing documentation** and samples: a section should be added in github right now and a clear call to contributing doc/merge request should be featured

**Comment by danrabbit** [comment]
As each of these would require their own new section, can you split this report into 3 separate reports please?

**Comment by davidak** [comment]
in irc is also much need for support; often they don't get any answer.
