### ISSUE TITLE
Set max-width on paragraphs and headings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#292]
Our default max-width for most elements on the site works well, except when we're using paragraphs or headings. We should set a sane max-width on those to prevent reeeeaaaally wide text-heavy pages.

**Comment by cassidyjames** [comment]
A max-width of around 50rem (calculates to 800px with the default size of 16px) looks decent to me.

**Comment by lewisgoddard** [comment]
Semi-fixed as `.row.docs` now has a 800px max-width.

**Comment by lewisgoddard** [comment]
This kind of links in with #332

**Comment by lewisgoddard** [comment]
I'm going to mark this as closed, it hasn't been much of an issues since `.row.docs` got a 800px max-width.
