### ISSUE TITLE
Get Involved: Tech Support

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#294]
Add _Providing help in forums/reddit/g+_ to the list of "How to get involved". Without endorsing officially people having a doc that tackle the "how to provide helpful support for elementary" would be nice.

**Comment by lewisgoddard** [comment]
This could also include committing to the stack exchange proposal until that goes through, then the actual site.

**Comment by btkostner** [comment]
Stack exchange is now included on the support page. Do you guys think this is still relevant?

**Comment by danrabbit** [comment]
It would probably still be useful as inspiration. I think one of the goals of the get involved page is to answer the questions of a person saying, "I want to get involved, but I don't know what I can do".
