### ISSUE TITLE
Get Involved: Code Reviews

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#295]
Testing applications and chiefly merge proposals is sorely needed. We can use (and train) people to be roughless and efficient testers. Using and updating [test documents](https://github.com/PerfectCarl/elementary-files-testing) is the way to prevent regressions as much as possible.

**Comment by danrabbit** [comment]
I'm worried that this is a bad idea. As much as in an ideal world we'd be able to crowd-source merge request testing, I feel like we won't be able to get testers to stay within the scope of the branch let alone have the technical knowledge to build and test the branch and especially get them to test it in a relatively clean environment.

I'm open to feedback from others, but I personally think we just need to focus on a culture that tells developers to do code reviews just as they need others to review their code.
