### ISSUE TITLE
Get Involved: Writing Documentation

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#296]
Writing documentation and samples: a section should be added in github right now and a clear call to contributing doc/merge request should be featured

**Comment by danrabbit** [comment]
This is going to depend on us figuring out how we want to do documentation. Either through raw html/css or through some kind of docs system like http://www.mkdocs.org/

**Comment by aleksandar-todorovic** [comment]
@danrabbit I think that you should choose GitHub + Markdown, the language used all around GitHub. That way, we could all participate in the progress, and it is pretty easy to export Markdown documents in HTML code to use it in the website itself once we write them. Markdown is pretty easy to learn and powerful enough accomplish all of the styling needed to make documentations. No additional package or web service is required. Everything could be done right here inside of a new repository.

**Comment by lewisgoddard** [comment]
Since we've gone with MDR, we can just add a section to `CONTRIBUTE.md` that details how to use Markdown.

**Comment by lewisgoddard** [comment]
This is somewhat dependent on #612 being merged, so I'm going to wishlist it for now.

**Comment by lewisgoddard** [comment]
I am unsure we now need a "writing documentation" document, most of our docs look pretty awesome already and I'm not sure what else we'd add. That said, adding a little to CONTRIBUTE.md about how to handle docs would probably help.
