### ISSUE TITLE
Set up subdomains for "developer", "developers", "dev", and "develop"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#298]
Right now our language isn't super clear and we use a mix of "Developer" and "Develop". "Developer" doesn't really make sense as a page title/URL to me as much as either "Develop" or "Developers".

I vote we change the link wording to "Develop" and the URL to `/develop`, and leave the heading that's on the page.

**Comment by danrabbit** [comment]
Developer.foo.bar is pretty much defacto. Check basically any website. Apple, Facebook, Paypal, Microsoft (it's a redirect, but still)

**Comment by cassidyjames** [comment]
Eh, Facebook and Google both redirect to developers and Microsoft redirects all three (develop, developer, and developers) to their actual site. I just feel like "Developer" is weird because it's the only thing that references who the user is instead of what they're doing or where they're going.

**Comment by cassidyjames** [comment]
I guess another reason "Develop" felt right in the right nav is that the left nav is nouns and the other item in the right nav is a verb.

**Comment by aroman** [comment]
Developer is definitely the standard from what I can see.

Like Dan said, everybody does it.

Check these search results out (esp. page 2): https://www.google.com/search?client=opera&q=develop+or+developer&sourceid=opera&ie=UTF-8&oe=UTF-8

My vote is for developer.elementaryos.org.

**Comment by aroman** [comment]
Another good argument in favor of developer vs. develop is that "develop" seems more like "develop elementary OS itself", rather than "third party developer(s)"

**Comment by cassidyjames** [comment]
Hang on Avi, we're not done bikeshedding this! Hop into #web on Slack :wink:

**Comment by cassidyjames** [comment]
Okay, I concede. I have opened pandora's box. I vote that we make the URL whatever @danrabbit wants to do.

**Comment by danrabbit** [comment]
Okay so it sounds like in Slack we decided to:

- [ ] Make the URL "developer"
- [ ] Set up redirect URLs for "developers" and "develop"
- [ ] Set up subdomains for "developer", "developers", and "develop"
- [ ] Call it whatever Cassidy wants in the UI as long as that name is clearly separated from 1st party developers. ie someone should not be confused thinking that to hack on elementary itself they should visit the "developer" page.

**Comment by danrabbit** [comment]
mentioning @fabianthoma for subdomains

**Comment by danrabbit** [comment]
Changing the description to just the subdomain bit.

Let's open separate reports for any other changes we need.

**Comment by fabianthoma** [comment]
so all of these subdomains should point to /developer ?
if so, it would not make much sense to set that up for the beta.elementaryos.org URL, if I should set it up, I'd do it for the elementaryos.org domain

**Comment by cassidyjames** [comment]
@fabianthoma yeah, subdomains on elementaryos.org. Conveniently the page will have the same URL. :)

**Comment by fabianthoma** [comment]
Alright, subdomains are done, the old dev site is now down because of that
