### ISSUE TITLE
Privacy Policy link color unreadable on Develop page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#299]
It's blue-on-blue. :stuck_out_tongue: 

![screenshot from 2015-01-29 14 02 02](https://cloud.githubusercontent.com/assets/611168/5966191/6c8ca7b2-a7bf-11e4-83f0-fab97bb3dee0.png)

**Comment by danrabbit** [comment]
I think we need to do footer a { color: inherit; } and get a little padding in there. It should be understood that stuff in the footer is pretty much gonna be links.
