### ISSUE TITLE
Add browser icons in privacy policy [$10]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#307]
It'd be a nice touch to have browsers listed horizontally at the bottom there with their icons.

**Comment by KeitIG** [comment]
ok, I worked a bit on it:

![capture du 2015-01-30 11 51 10](https://cloud.githubusercontent.com/assets/1311607/5974594/55ea5de4-a876-11e4-8e36-b6885878e108.png)

* I added a safari Link
* Boxes has different width, I have to fix that
* We have to chose responsive behavior: should I create a .column.fifth ?

**Comment by lewisgoddard** [comment]
@KeitIG

- [ ] Safari is incorrectly called Opera.
- [ ] Mozilla no longer prefix Firefox with their own title.
- [ ] This kind of makes it look like you can only disable cookies in Firefox. Maybe add duplicate links for the others or change the text to "Manage or Disable Cookies" ?

**Comment by KeitIG** [comment]
It's just a draft, not a PR :wink: I stil didnt commit anything.

You are right about manage/disable cookies. And I find it repetitive to read 5 times "manage cookies"

**Comment by KeitIG** [comment]
here are some of the possibilities

![capture du 2015-01-30 13 38 23](https://cloud.githubusercontent.com/assets/1311607/5975760/555dfda4-a885-11e4-8f3f-d54f43d22025.png)

**Comment by aleksandar-todorovic** [comment]
Since elementary OS ships Midori as the default browser, I think that we should consider including Midori too, even though it is not as popular as those browsers that are included already. This way it seems like we don't support our own browser choice.

**Comment by danrabbit** [comment]
@aleksandar-todorovic I agree, but I think that's its own separate issue. Can you do my a favor and file that please?

@KeitIG @lewisgoddard I think we should drop the disabling link from Firefox so we can have the browser names be the links. I really like the big icons across the bottom. Helps this page to be visually interesting. But the icons-as-bullets version is also cool

**Comment by KeitIG** [comment]
How about columns ? Do I have to create .column.fifth ?

**Comment by danrabbit** [comment]
@KeitIG Only if you really need them to be 1/5th of the available space. I believe .column + .column has a built-in margin and they should center within a .row so I don't think it's 100% necessary
