### ISSUE TITLE
Warn users of outdated browsers

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#32]
While not many of our visitors use outdated browsers, we should warn those who do that their browser is outdated and that our site won't work properly.

On system76.com we simply throw a big ol' header on <=IE10 with a link to browsehappy.com

```
<!--[if lt IE 10]>
	<div id="legacy-warning">
		<h1>System76 is built on modern web technologies your browser doesn&rsquo;t support.</h1>
		<p>This version of Internet Explorer is out of date and may contain bugs or security vulnerabilities. Please <a href="http://browsehappy.com/">upgrade</a> to IE 11 or an alternative web browser.</p>
		<p>If you have questions about an order or require support, feel free to <a href="/contact">contact us</a>.</p>
		<div id="legacy-warning-buttons">
			<a href="#" onClick="document.getElementById('legacy-warning').style.display = 'none';">Dismiss</a>
			<a class="primary" href="http://browsehappy.com/">Learn More</a>
		</div>
	</div>
<![endif]-->
```

This is then styled up with CSS and works quite well. I'm open to discussion on how else to implement it, but no matter what let's keep it simple. :)

**Comment by cassidyjames** [comment]
How it shows up on System76.com 

![screenshot from 2015-01-09 11 49 56](https://cloud.githubusercontent.com/assets/611168/5685235/ad4ee42e-97f5-11e4-9cc7-486730f6bb8f.png)

**Comment by danrabbit** [comment]
Yeah, I'm down with that. Would make it easier to target current gen browsers.
