### ISSUE TITLE
Installation page is a wall of text

### ISSUE THREAD

**Issue by Dany0** [elementary/mvp#320]
* [x] Remove text describing the page you're on.
* [x] Remove near-duplicate screenshots.
* [x] Drop "requirements" and just have "recommended".
* [x] Put recommended system, download link, and backup under "pre-install".
* [x] Try and Guess OS.
* [ ] Try and Guess Architecture.

---
 - more use of **bold** text and text formatting
 - maybe a video on installation? I don't know. a windows/os x executable (something like wubi) that would download the iso and make a bootable usb would be nice but a large undertaking

**Comment by cassidyjames** [comment]
@Dany0 I'm working on this in my drop-cds branch

**Comment by Dany0** [comment]
Mind committing it then?

**Comment by cassidyjames** [comment]
@DanyO I committed my changes, and they're in master. I didn't add bold or anything, but it cleaned up a lot of the text and wording.

**Comment by Dany0** [comment]
oh okay, so the original issue still stands

**Comment by lewisgoddard** [comment]
Is this now fixed? There's been a lot of changes I think.
http://beta.elementary.io/installation

**Comment by Dany0** [comment]
What? Barely anything changed. The original issue was that it's a **wall of text**. Aim for the clarity of a powerpoint slide or something of that ilk. At least I can imagine a way that you can tell people how to install eOS in two twitter posts and 3 screenshots. Maybe you could do it in less.

**Comment by lewisgoddard** [comment]
Okay

I think this first sentence can be dropped, since it doesn't really say anything other than "this is a page about installing".
> "elementary OS is designed to run on any relatively new 32-bit and 64-bit desktop or laptop. In this section, we'll cover system requirements and other prerequisites to installing elementary OS on your computer."

I think @danrabbit wanted to merge the minimum and recommended system requirements into a "recommended system". Isn't "Recommended System Requirements" an oxymoron?

The downloading elementary OS section is a little ridiculous. It literally just says go download. Maybe that should be merged with the recommended system into a "pre-installation" section, along with the 64 or 32 bit section.

Back Up Your Data would also go under "pre-install", but doesn't actually need changing I don't think.

I don't think the first screenshot for Rufus is needed under Windows, just the second one, and the rest of the instructions seem fairly concise.

Overall there is room to neaten this out a bit, but I don't think you can tell someone how to install a new system in two tweets. It wouldn't carry the necessary warnings or cover the major possibilities (like macbooks).

**Comment by lewisgoddard** [comment]
@cassidyjames Could you either push your branch or let me know if you're no longer working on this?

**Comment by Dany0** [comment]
>but I don't think you can tell someone how to install a new system in two tweets. It wouldn't carry the necessary warnings or cover the major possibilities (like macbooks).

I think you can if you had some sort of HW detection.

**Comment by lewisgoddard** [comment]
I don't think there's any way we can reliably detect the amount of ram or disk space on a machine, and people could easily be downloading for another machine. I will look into the idea of having the whole thing as a slideshow, but I'm not taken by the idea.

**Comment by Dany0** [comment]
I know, it would be possible with an external tool, but I'm not a huge fan of that.

**Comment by cassidyjames** [comment]
Okay, so let's split this issue up into actionable checklist items. As it stands it's too vague. In GitHub, you can do this:

```
- [ ] Item 1 to fix
- [ ] Item 2 to fix
- [x] Item 3 that has been fixed
```

...for checklists.

**Comment by Dany0** [comment]
I like it! The design problems can be solved by some professional :) Though I suggest adding a bit more margin to the rufus/unetbootin screenshot.

By the way, one sure way to detect OS X is to see if the browser is Safari 6+

Is it okay to comment on a closed issue?

**Comment by lewisgoddard** [comment]
The page should detect the operating systems in JavaScript. Also, Safari is supposed to be coming back to Windows soon.

**Comment by ApfelUser** [comment]
@lewisgoddard Really, Safari is going to come back to Windows? That would be awesome, from where do you have that info?

**Comment by Dany0** [comment]
Where'd you read safari will be back on windows? Google turned up nothing.

Another design suggestion - add icons to OS name for them to be more easily recognizable. (by the logic that a user who wants to install eOS on OS X will see the OS X icon and think "right, that's me!" instead of looking for the text)

**Comment by aleksandar-todorovic** [comment]
I agree, the addition of icons before the name of the OS is a great idea.

**Comment by lewisgoddard** [comment]
I think filing a separate bug for icons instead of text would be the way to go, I think this bug needs to be marked as resolved and other issues filed separately, or they end up 100 messages long and you can never find anything.
