### ISSUE TITLE
Section buttons look like they relate to the bug graph

### ISSUE THREAD

**Issue by maffity** [elementary/mvp#324]
On the Get Involved page, the section buttons are immediately below the bug graph. Since they share colors I thought they were somehow related.

If we want to keep the buttons the same colors, perhaps they could be in a new section with a different background color. Otherwise, I think we should change the colors on the graph or the buttons.

**Comment by lewisgoddard** [comment]
This is temporarily fixed as the graph is hidden for the current release.

**Comment by lewisgoddard** [comment]
The chart is back, and so is this bug.
