### ISSUE TITLE
Varnish for Caching

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#327]
or another software to deliver static content instead of parsing php on every request.

will increase the page load time and reduce load on the webserver.

**Comment by devTristan** [comment]
nginx is very fast w/ php5-fpm and proxy caching. Could be automatically disabled for logged in users and such.

**Comment by lewisgoddard** [comment]
I don't think we have logged in users, so caching could work. Would need to be disabled on `beta.../branch/...` though.

**Comment by lewisgoddard** [comment]
Okay, so Cloudflare caches HTML as it turns out, although we need this disabled for location detection on the homepage. That kind of invalidates this bug.
