### ISSUE TITLE
Cache-Control Headers

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#328]
let the browser cache static content like images, js, etc

for nginx:
```
location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
   expires 365d;
}
```

deactivate for development ;)

**Comment by lewisgoddard** [comment]
With Cloudflare enabled, I'm not sure this is entirely necessary.

**Comment by lewisgoddard** [comment]
This has become a duplicate of #648, which has a fix merged, but not implemented server-side yet.
