### ISSUE TITLE
Fix layout on Developer

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#330]
The way the icons are done in the sections on the right is definitely BS and it doesn't allow the layout to reflow properly on mobile.

**Comment by KeitIG** [comment]
Do you want to change the icons or just work on responsive layout ?

**Comment by sserdyuk** [comment]
Wanted to help, but I don't see anything wrong with the responsiveness of the layout there.

**Comment by lewisgoddard** [comment]
@danrabbit Can you clarify how you think this should flow, and that it's still an issue on [/developer](https://elementary.io/developer).
