### ISSUE TITLE
put a wikipedia link next to the social icons

### ISSUE THREAD

**Issue by ferst9** [elementary/mvp#334]
New users might be curious about elementary's history.
There should be a wikipedia link about elementary next to the social icons (reddit,...).
BTW the german version (http://de.wikipedia.org/wiki/Elementary_OS) is more complete than the english one.
PS : It would be great to have detailed information about elementary on wikipedia. A lot of information is missing.

**Comment by danrabbit** [comment]
There doesn't appear to be a FontAwesome icon for Wikipedia, so that would mean we'd need our own SVG there.

**Comment by cassidyjames** [comment]
I've commented on the FontAwesome project. A ton of people have requested the icon, so I'd imagine it'll be added in a future release. I'm okay with adding our own SVG until then.

**Comment by ferst9** [comment]
Thanks guys, now the wikipedia article should include much more details about elementary. How it all began until today.

**Comment by aleksandar-todorovic** [comment]
Maybe we don't need a separate SVG until then? After all, Wikipedia logo is nothing more than a capital W. Here is a [quick fix](http://jsfiddle.net/fLktadyn/1/) as suggested in the Font Awesome issue mentioned above.

**Comment by danrabbit** [comment]
That doesn't look like the wikipedia "W" here. See the actual logo: http://en.wikipedia.org/wiki/Logo_of_Wikipedia

**Comment by snwh** [comment]
I question the need to link to wikipedia. Shouldn't our own site explain the project?

**Comment by ferst9** [comment]
Maybe the website should only contain the essential part of elementary. The whole history can be found on wikipedia.

**Comment by danrabbit** [comment]
I'm going to close this as our wikipedia page contains inaccurate information and I don't really trust linking to an external source like this.
