### ISSUE TITLE
SVG looks bad in Luna

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#338]
maybe use PNG instead.

![luna](https://cloud.githubusercontent.com/assets/91113/6003712/027c5786-aafe-11e4-9442-cc6e3fd86b4e.png)

**Comment by KeitIG** [comment]
can you add a `height: auto` with developers tools (f12) on the logo and tell me what happens ?

**Comment by davidak** [comment]
nothing happens. with `height: 100px;` it looks like it should.

**Comment by cassidyjames** [comment]
Ha, that's pretty bad indeed. :) It looks like we can add `height: 66px` (since that's the natural height at 454px wide, the max width).

**Comment by KeitIG** [comment]
I won't be that simpler because of responsive, I'm working on it.

**Comment by KeitIG** [comment]
Ok, using 
```html
<object data="images/logotype.svg" type="image/svg+xml"></object>
```
seems to do the trick, but we're losing the `alt`attribute.

@cassidyjames If the image has fixed dimension, why couldn't we use a .png instead ?

**Comment by snwh** [comment]
There's a simpler solution:

```css
#logotype {
    background-image:url(/images/logotype.svg);
    max-width: 100%;
    width: 454px;
}
```

**Comment by cassidyjames** [comment]
The problem is that it needs to be embedded directly on the page in order
to be dynamically colored using the CSS `fill` attribute.

**Comment by KeitIG** [comment]
so @cassidyjames, I will use an object tag, so it will be fillable.

**Comment by cassidyjames** [comment]
@KeitIG sorry I just now got back to this.

Sorry, but you're wrong... you cannot use a linked CSS file in the site to set the fill when it's embedded using `<object>`. Go change the fill on the `body { }` rule in the CSS and see how the logotype doesn't change its color, but the logomark (which is not embedded in an object) does.

**Comment by cassidyjames** [comment]
The whole point of using an SVG is that it's scalable and will pick up the text (when we're sure to always use both `fill:` and `color:` in the stylesheet).

**Comment by KeitIG** [comment]
I'm checking that.

**Comment by KeitIG** [comment]
@lewisgoddard I need your advice on this one. Is `<?php include('images/logotype.svg'); ?>` would bother you (semantically) ?

I you're ok with this, consider it fixed.

**Comment by lewisgoddard** [comment]
@KeitIG I don't understand how that will fix the problem.

We can't use PNGs, JPEGs, or Objects because they don't support `fill`, and `<img src="thing.svg">` doesn't scale correctly in WebKit 1.x.

**Does embedding the SVG in `<svg ... ></svg>` fix the scaling problem?**

If include works, that's not semantically incorrect, just a bit unusual. Maybe comment following:
```
<?php
    // Embed the SVG to fix scaling in WebKit 1.x,
    // while preserving CSS options for the image.
    include('images/logotype.svg');
?>
```

**Comment by KeitIG** [comment]
Including the svg file with PHP seems the best option so.

**Comment by lewisgoddard** [comment]
So long as it fixes the scaling issue and doesn't break `fill` support, I'd merge that.

**Comment by lewisgoddard** [comment]
http://beta.elementary.io/branch/logotype-include/ is available for testing.

Should be fully responsive and remain `fill` compatible (proven by the fact the logo is red).

**Comment by KeitIG** [comment]
Sorry for haven't done that, I don't really have free time these days

**Comment by lewisgoddard** [comment]
That's okay, wasn't too much work.
