### ISSUE TITLE
Payment not remembered until reloading the page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#339]
If I:

1. I pay for the download using Stripe
2. Click a button to download the ISO
3. Go back to the elementary tab in my browser
4. Click to download again

...I expect to get the download dialog again. Instead, I'm prompted to pay again. If I reload the page then click the download button again, I'm properly remembered.

**Comment by lewisgoddard** [comment]
I will be able to grab this on Wednesday.

**Comment by lewisgoddard** [comment]
Done by devTristan.
