### ISSUE TITLE
Download modal does not have X button, does not close on click-away or esc key

### ISSUE THREAD

**Issue by devTristan** [elementary/mvp#341]
Unexpected behavior. Once the user has the download screen open, it cannot be closed without clicking a download button.

![selection_003](https://cloud.githubusercontent.com/assets/216009/6011979/fd41cdac-ab0f-11e4-8838-0929eed3325c.png)

**Comment by lewisgoddard** [comment]
This is currently the designed behaviour, to avoid paying users clicking away without getting their product. Once #339 (Payment not remembered until reloading the page) is fixed, I might be able to persuade @danrabbit to add back the close button and esc key options leanModal2 came with.

**Comment by devTristan** [comment]
oh, okay. Mind if I take that?

**Comment by lewisgoddard** [comment]
Sure, go for it. All it needs is the buttons removing, then adding `<input type="hidden" id="amount-custom" value="0">` and selecting it. Shouldn't be too much JavaScript.
