### ISSUE TITLE
"Change language" button

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#347]
Add a "Change language" button, and maybe a little message "This page is available in your language" when accessing `/de/installation` from a Spanish browser?

**Comment by emersion** [comment]
A set of SVG flag icons: https://github.com/lipis/flag-icon-css

**Comment by danrabbit** [comment]
We've talked about flag icons before on desktop and the conclusion was basically that they weren't a great idea. Mainly because a flag doesn't necessarily imply a language.

Font awesome does supply a change language icon: http://fortawesome.github.io/Font-Awesome/icon/language/

**Comment by emersion** [comment]
Okay, fine! Do you think a popover is a good idea?
