### ISSUE TITLE
Add a "FAQ" page

### ISSUE THREAD

**Issue by emersion** [elementary/mvp#348]
As discussed in #264:

> the nice thing about an "FAQ" or "common questions" page is that there are questions we get all the time via email, twitter, or sometimes random bug reports/Launchpad questions. We can put those there if we think they're common enough to warrant it.

**Comment by cassidyjames** [comment]
@danrabbit mentioned using the elementary meta-project's FAQ page from launchpad. That works for actually-frequent questions on Launchpad, so I think that works. :)

**Comment by emersion** [comment]
Using the Launchpad API or redirecting the user to Launchpad?

**Comment by cassidyjames** [comment]
Just linking to the Launchpad page.

Regards,
Cassidy James

--

**Comment by danrabbit** [comment]
Gonna assign to @cassidyjames since he has that support branch
