### ISSUE TITLE
Get Involved Graph isn't updating

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#349]
It appears to be stuck. We're at 1 issue today and it's showing 3 left still.

**Comment by emersion** [comment]
We need to set up one of these:
* Add a cronjob to execute http://beta.elementaryos.org/backend/chart.php every day (this is the script which updates the graph)
* Auto-update graph each day the first time a user go on the `/get-involved` page

**Comment by emersion** [comment]
Just manually updated the graph in #351. This is a temporary solution.

Also, accessing `/backend/chart.php` from beta.elementaryos.org doesn't work (_502 Bad Gateway_), maybe setting a custom time limit can help?

**Comment by lewisgoddard** [comment]
I've assigned fabian because this requires some background work and really needs doing.

**Comment by scriptiz** [comment]
Just added a recurring job in Azure to call that page every day at 3am and 3pm (UTC-0) until you'll get something sorted on your side.

**Comment by fabianthoma** [comment]
Alright, added the cronjob, starts from now every day, 3 in the morning UTC.
