### ISSUE TITLE
Set up download analytics

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#350]
It'd be great to be able to see data like:
* Total downloads including torrents
    * direct vs torrent
    * 32bit vs 64bit
    * per platform
* Average price paid per download (excluding 0 as an outlier)
    * per platform (a la humble bundle)
    * direct vs torrent

**Comment by lewisgoddard** [comment]
Google Analytics can be used for the tracking, but presumably you'd want the averages to be public.
```
ga('send', 'event', 'category', 'action', 'label', value); // value is a number and not in quotes.
// Send and Event are always the same.
// Category is the Download
// Action is how it was initiated. Homepage, and maybe in the future, email?
// Label of Download
// Price paid in pence.
ga('send', 'event', 'Freya Beta Download', 'Homepage', '32-bit Magnet', 0);
ga('send', 'event', 'Freya Beta Download', 'Homepage', '64-bit Direct', 2500);
```

**Comment by danrabbit** [comment]
TBH I don't care if they're public. I'm more interested in knowing how much effort we should put into 32bit support & what are sane values for the pay-what-you-want buttons. But also the cynic in me wants to know who's the cheapest and who kicks down ;p

**Comment by lewisgoddard** [comment]
If we're not concerned about public ones, then this can be done entirely in JavaScript with a load of `if`s and Google Analytics.
```
ga('send', 'event', 'Freya Beta Download (Architecture)', 'Homepage', '32-bit', 0);
ga('send', 'event', 'Freya Beta Download (Method)', 'Homepage', 'Magnet', 0);
ga('send', 'event', 'Freya Beta Download (OS)', 'Homepage', 'Windows', 0);
```

**Comment by danrabbit** [comment]
Make it so, Number 1
