### ISSUE TITLE
Add Midori to privacy policy

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/mvp#353]
So, after https://github.com/elementary/mvp/pull/337 got merged (and fixed #307 issue), I think that it is a perfect time to discuss adding Midori to that list. I think that this is an important issue because Midori _is_ our default browser. Not mentioning it seems like we're not supporting our own product.

**Comment by KeitIG** [comment]
Seems ok to me.

This make me think Midori has a different logo now: http://midori-browser.org/.

What one should we use ?

**Comment by lewisgoddard** [comment]
We should probably use whatever shows up in the dock in elementary OS. We don't want to be referencing to something with one logo and the person using it clicks on another.

**Comment by KeitIG** [comment]
Another thing, the only link I could find on Midori's website about Cookies was http://midori-browser.org/faqs/#blacklist_cookies, are you ok with this one Lewis ?

**Comment by lewisgoddard** [comment]
Well, that site is controlled from [eustasy/midori-browser.org](https://github.com/eustasy/midori-browser.org), so we could potentially add a section or modify that one if we want.

That page actually propogates from this Wiki](https://wiki.xfce.org/midori/faq).[

**Comment by KeitIG** [comment]
Ok, I'm afraid I don't have write access to this repo, for the moment I will only add the FAQ link.

**Comment by aleksandar-todorovic** [comment]
Glad to see that this one is going to get solved.

Off-topic: I'm loving the design of the Midori website.
