### ISSUE TITLE
Difference between Spanish from Spain, and Spanish from America

### ISSUE THREAD

**Issue by rubengc** [elementary/mvp#366]
All translated texts from Spanish are based on Spanish from America or Hispanic America (Argentina, Mexico, etc)

But we don't use the same terms for somethings (include can even have different terms in spanish from america) and this can be confusing for some users, some examples are:
English: Spanish (Spain) - Spanish (America)
Burn to disk: Grabar en el disco - Prender en el disco
Computer: Ordenador - Computadora
Turn on: Encender - Prender ("prender" can refer differents things in spanish from america)

Another differences are the replacement of the letter "s" by the letter "z" in some words and diferent tenses to express the same thing

Spanish from America, usually translates direcly from english, but Spanish from Spain attemps to translate based on context, for example
Browse our Blueprints
Browse is "Navega", Spanish from America understand this term like in english, but in Spanish from Spain, "Navega" is similar to the action of navigate the internet, so this more nested to the word navigate than browse, one correct translate (here always this subjective) for this word is "Explora" (explore)

I think it can be better for interaction between the user and the website to be translated by native people who know how to target the meaning of content to the people from same nationality

**Comment by danrabbit** [comment]
I believe what you'll want to do is propose another region on Transifex here: https://www.transifex.com/projects/p/elementary-mvp/

I don't believe that the website itself hard codes any specific language codes. Closing this report since it can't be solved here on the website.

**Comment by Fitoschido** [comment]
I’m from Latin America, and I have never heard anybody using the verb *prender* in the sense of burning a disc…

> Another differences are the replacement of the letter "s" by the letter "z" in some words and diferent tenses to express the same thing

That is nonsense. Spanish spelling rules are standardized everywhere, regardless of regional pronunciation customs.

> Spanish from America, usually translates direcly from english, but Spanish from Spain attemps to translate based on context

Even more nonsense. You’ll find bad translators everywhere, it has nothing to do with the place of origin.
