### ISSUE TITLE
GB with or without space?

### ISSUE THREAD

**Issue by TicTac7x** [elementary/mvp#369]
In some places there is for example "5 GB", but in some places it's "1GB". Not consistent.

**Comment by cassidyjames** [comment]
Good catch! Personally, I usually do without the space. But I'm indifferent as long as we're consistent.

**Comment by danrabbit** [comment]
I'm going to change this to "incomplete". OP, can you be specific about where the discrepancy is?

Just from a quick look, Dell and Apple are both using no space.

**Comment by TicTac7x** [comment]
886.0 MB (for PC or Mac)
512 MB of system memory (RAM)
5 GB of disk space
1 GB of system memory (RAM)
Begin with a spare USB flash drive with at least 1GB of free space.

**Comment by davidak** [comment]
officially it should be "1 GB", it also looks more right to me.

http://www.tuaw.com/2010/12/16/32-gb-versus-32gb-almost-everyone-is-writing-it-wrong/

**Comment by aleksandar-todorovic** [comment]
Great article!

I think that this article covers it all and that there should be a space between a number and an unit.

**Comment by KeitIG** [comment]
Translators should be notified since the changes were committed.
