### ISSUE TITLE
Translate the website [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#37]
We should probably get this set up sooner than later

**Comment by khampal** [comment]
Yes, I agree - it's always been a PITA to add translations after all the strings have been hardcoded into the page in the past. It's probably worth discussing how we should go about this (considering we're now not using any sort of framework or server side language (yet)).

**Comment by danrabbit** [comment]
I imagine we should probably go with some solution that works with a github plugin for translations. Anybody have any leads on that sort of thing?

**Comment by PhillipSz** [comment]
maybe we should just use something like: elementaryos.org/de or elementaryos.org/fr and then link to these pages? Would be a quick fix, even if that's really static :)

**Comment by jishnu7** [comment]
What about https://github.com/wikimedia/jquery.i18n ?

**Comment by quassy** [comment]
Using jQuery / Javascript in general for i18n sounds like a bad idea. 

If the site uses PHP without frameworks I think it would be most sensible to use the built-in functions for [gettext](php.net/manual/book.gettext.php). Templates can stay almost the same, only that every to-be-translated `<?php echo "English string"; ?>` has to be replaced by `<?php echo _("English string"); ?>` (or `<?=_( "English string" )?>` if you prefer it short, and enable shortcodes). GNU gettext is pretty much standard and there are a whole bunch of (including [web](weblate.org/)) apps for it, but you can also edit the files with a text editor if you feel desperate.

**Comment by Tajnymag** [comment]
As a temporary solution I'd agree with PhillipSz with the "elementaryos.org/lng". We would also have it easier to use the translated strings later.

**Comment by davidak** [comment]
much projects use Transifex, like ownCloud https://www.transifex.com/projects/p/owncloud/

it is free for open source-project. the interface is more modern than launchpad. but why not using launchpad, if you use it for the apps?

also, the localization should happen on server-side that the client simply get's a plain html file.
i hope you have caching like varnish to speed it up and don't have to apply the localization on every request. that saves lot's of resources on the webserver!

`<?php echo _("English string"); ?>` is really messy. there should be a more elegant way.

**Comment by Tajnymag** [comment]
But if we used the local manual translation, we could easily deal with currency convertion and translated "hero" screenshots.

**Comment by aleksandar-todorovic** [comment]
Please don't use Launchpad for the translation of the website. Choose Transifex or local translations. Both of them are much easier methods than the constant "something went wrong" errors we get on Launchpad.

**Comment by lewisgoddard** [comment]
Launchpad translations make no sense for a GitHub hosted project. They were never being seriously considered.

**Comment by Murazaki** [comment]
I understand that there is Weblate and WebtranslateIt that integrates well with Github (they are in the service hooks). Weblate is simple but seems to handle a lot of file types, and PHP files as well : http://docs.weblate.org/en/latest/formats.html#php-files

**Comment by KeitIG** [comment]
Laravel uses a nice system:

a template:
```php
<?php echo trans('users.noaccess'); ?>
```

lang/fr/users.php:
```php
return array(
   'noaccess'      =>	"Vous n'êtes pas autorisé à faire ça.",
   ...

);
```

**Comment by emersion** [comment]
Working on it, see #288
