### ISSUE TITLE
Not all quotes have ending punctuation

### ISSUE THREAD

**Issue by TicTac7x** [elementary/mvp#370]
Not all quotes have ending punctuation (periods)

Don't:
> “elementary OS is different… a beautiful and powerful operating system that will run well even on old PCs”

> “a fast, low-maintenance platform that can be installed virtually anywhere”

> “Websites should look good from the inside and out”

> “Before software can be reusable it first has to be usable”

Do:
> “Lightweight and fast… Completely community-based, and has a real flair for design and appearances.”

> “A different language is a different vision of life.”

> “Great design is making something memorable and meaningful.”

**Comment by cassidyjames** [comment]
Good catch. We should end all quotes with a period.
