### ISSUE TITLE
Custom amount input looks different (and wrong) with different browsers

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#371]
Generally the rendering seems different from browser to browser: The dollar signs are different in size as (for Firefox and Internet Explorer) is the surrounding box. Only in Chrome the text is displayed in grey.

Only for the German translation: The text overflows the custom amount textbox. "Benutzerdefiniert" translates to "Custom" (literally "User defined"). Unfortunately I cannot think of a better, shorter translation, so maybe the box should just be made bigger for some locales.

![Firefox 36](https://cloud.githubusercontent.com/assets/369996/6103404/47a01cf8-b044-11e4-9c9b-de2cc8cb6a8f.png)
![Chrome 40](https://cloud.githubusercontent.com/assets/369996/6103405/4925b4a2-b044-11e4-8425-ec8f784e6973.png)
![Internet Explorer 11](https://cloud.githubusercontent.com/assets/369996/6103406/4abd3b14-b044-11e4-9950-d8f80512f116.png)

**Comment by lewisgoddard** [comment]
I think the b ox is actually sizing correctly, but the other inputs in IE11 are not (they're too tall). Firefox doesn't support coloring placeholders, IIRC. IE needs some box-sizing adjustments by the look of it and they all need some padding set.

**Comment by quassy** [comment]
Original code (why is this split in four lines?): 

    .button::-webkit-input-placeholder {
        color: #333;
    }
    .button:-moz-placeholder {
        color: #333;
    }
    .button::-moz-placeholder {
        color: #333;
    }
    .button:-ms-input-placeholder {
        color: #333;
    }

The Firefox placeholder is correctly colored, only the placeholder colors for Webkit and MS seem to have no effect. Adding !important works in Chrome so apparently they get overwritten by some other value.

**Comment by KeitIG** [comment]
@quassy It is splitted in four lines because `::-webkit-input-placeholder` is a pseudo-element, not a property.

**Comment by quassy** [comment]
Pseudo-elements don't behave much different to elements, so this should work fine and is [better code](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself):

    .button::-webkit-input-placeholder, 
    .button:-moz-placeholder, 
    .button::-moz-placeholder, 
    .button:-ms-input-placeholder {
        color: #333;
    }

**Comment by KeitIG** [comment]
Oh I didn't understand it in that way, yes you are right !

**Comment by lewisgoddard** [comment]
@quassy It is split into four lines because many browsers will ignore any css rule containing an invalid selector is [just ignored](http://stackoverflow.com/questions/13816764/invalid-css-selector-causes-rule-to-be-dropped-what-is-the-rationale). Since only each of those selectors are only for one browser, they will always be ignored if condensed.

**Comment by lewisgoddard** [comment]
@quassy Also, it's Firefox that has the color wrong, not the others. #333333 is actually quite a dark grey, not the lighter one. The reason it is not working is because `:-moz-placeholder` has been replaced by `::-moz-placeholder` [since Firefox 19](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-placeholder).

**Comment by lewisgoddard** [comment]
@quassy Finally, a `float: left;` on the `:before` element fixes the height problem in IE, and doesn't seem to break anything else. Given a few hours I will have a branch up for review.

**Comment by quassy** [comment]
Thanks for the explanation. I stand corrected. 

It's weird that `::-moz-placeholder` does not work as it seems to work fine on the [mozdev example](https://developer.mozilla.org/en/docs/Web/CSS/::-moz-placeholder). `opacity: 0.4` seems to be the reason why the placeholder is so light, but I am unable to change it with devtools. Probably have to live with that.

**Comment by lewisgoddard** [comment]
### Mozilla Placeholder Color
Mozilla applies a silly `opacity: 0.4` to all the placeholders. There isn't a way around this right now.

### Placeholder Width
There isn't a way to set this dynamically based on the width of the placeholder, but I've added more padding to stop it going under the $ sign.

### IE Height
I still need to test this.

**Comment by lewisgoddard** [comment]
I hope to be able to resume work on this shortly, but certainly not this week. If someone wants to steal what I've done so far in comments, go for it.

**Comment by Dazag** [comment]
I have fixed it, but I can't push. Do I need to be in the community or something! thanks in advance and sorry for spamming! :dancers:

**Comment by lewisgoddard** [comment]
@Dazag You'll need to create your own fork and push to a branch on that, then you can file a pull request for review.
