### ISSUE TITLE
Add a dependant technologies/projects page

### ISSUE THREAD

**Issue by roryjs** [elementary/mvp#382]
Add a page with donation links to technology that elementary OS relies on, e.g. ubuntu, gnome, debian, linux kernel, etc.

As one of our aims is to be as linux beginner friendly as possible, we should ensure that people are aware that elementary OS relies on huge amounts of work by other open source projects and make sure it is easy to donate to them.

**Comment by btkostner** [comment]
Along with this, we should include stats about how elementary contributes upstream.

This quote from Cassidy wrapped it up nicely:
>41 different public open source projects. 745 public code branches. 14,172 bug reports (10,000 of which have been closed). Over $15,000 in bounties (including $3,470 to upstream projects). Several contributions upstream including to Ubuntu, GTK+, GStreamer, and Vala. A private build server to compile code and crank out images daily. 79 developers and contributors collaborating daily, with dozens more coming and going.

Another name for the page could also be "community"

**Comment by davidak** [comment]
maybe the payment for elementary can be organized like humblebundle where you can set how much money goes to what project. defaults most to elementary (80%) and the rest to other key projects it is based on. one point could be "others" where all small projects are combined with a list on hover. the user can actively decide what is important for him.

nobody will go to all projects and face the difficulties donating to them!

**Comment by lewisgoddard** [comment]
@davidak I think that would be very hard to organize.

Which upstream projects?
Weighted or equally distributed?
Do we track every single donation and the distribution?
What about ones that don't go through?

**Comment by davidak** [comment]
yes, it's a bit of work. it could be the next step for the payment.

the exact design should get worked out.

it's a legitimate point that elementary would not exist without the work of others and that they should profit from our (financial) success.

https://www.youtube.com/watch?v=1u6cZifg15w

>What about ones that don't go through?

if we can't find a way to donate to a project once, how could any normal user?

**Comment by danrabbit** [comment]
https://www.bountysource.com/issues/8493727-add-a-dependant-technologies-projects-page
