### ISSUE TITLE
New translation for web site

### ISSUE THREAD

**Issue by serkandurusoy** [elementary/mvp#390]
Hi,

I've just gone ahead and translated [mvp to Turkish](https://www.transifex.com/projects/p/elementary-mvp/language/tr_TR/) but don't know what next, so please forgive me for creating this issue for a wrong purpose.

Just wanted to ping (if not already done by transifex) whomever is tasked with reviewing/integrating new translations.

Great site by the way!

**Comment by emersion** [comment]
See #399.

**Comment by serkandurusoy** [comment]
Thanks! :clap:
