### ISSUE TITLE
Beta site wrongly translated in dutch

### ISSUE THREAD

**Issue by lolobergkamp** [elementary/mvp#404]
Hi there

In the dutch version of your  beta homepage you have below the payment options "custom" that is translate to "aangepaste" instead of "aangepast". I'm actually the one who made that mistake on transifex, someone else corrected mine translated and changed "aangepaste" to "aangepast".But you ported the first translation (wrong) instead of the second translation (right) in.I think you should as default port the last translation in instead of the first on.

On a different note, could you guys ask the reviewers on launchpad to review on transifex?

**Comment by emersion** [comment]
Yes, we need reviewers. I think I'll modify TRANSLATE.md to ask for reviewers.

When was the mistake corrected? The last update from Transifex has been made 15 hours ago (see #399).

**Comment by lolobergkamp** [comment]
That mistake was corrected 11 days ago.

**Comment by lolobergkamp** [comment]
Seems to be fixed now, you can close it.
