### ISSUE TITLE
App Carousel background shifts on slide change

### ISSUE THREAD

**Issue by JoshStrobl** [elementary/mvp#406]
When changing between the photos and music slide, the mountains background "shifts" substantially. I went ahead and [recorded a short clip to show the issue](https://www.youtube.com/watch?v=o7wTyUpWdwk).

Browser (as you can see in the video): `Chrome 40.0.2214.111`
System (not like it really affects anything, but I'll provide it anyways): `Fedora 21`

**Comment by danrabbit** [comment]
Hey Josh, I'm going to mark this as invalid since that branch hasn't been merged into master yet.

If you liked, you can comment on the pull request here: https://github.com/elementary/mvp/pull/405

But I already know about the issue and the branch will be fully reviewed before being merged :)
