### ISSUE TITLE
Change Serbian translation from Latin to Cyrillic

### ISSUE THREAD

**Issue by Theonewithideas** [elementary/mvp#407]
In Serbian, we use both Latin and Cyrillic lettering, and most of Google services (for example) use Cyrillic. I think users woud feel more welcoming if they had the text in Cyrillic, it feels more personalized, and kinda looks more professional.

There is not a big difference, but I think it would affect Serbian users, as they usually feel that they're left behind in the tech world, so making this change would welcome them, I think.

Attached images show the difference:

![latin](https://cloud.githubusercontent.com/assets/6058082/6212386/0af57860-b5e5-11e4-9a7f-8a144825c868.png)
![latin2](https://cloud.githubusercontent.com/assets/6058082/6212389/12178f34-b5e5-11e4-8f3a-fed3d76c575a.png)

I am willing to rewrite all the strings if we decide that this is a change that we should go with.

**Comment by aleksandar-todorovic** [comment]
In my opinion, it is easy to decide.

If elementary itself is translated into Latin, then the website should be in Latin too. If it is translated into Cyrillic, the website should be in Cyrillic.

So, we should probably check that out and act accordingly.

**Comment by tintou** [comment]
It's not that simple, in elementary OS there are sr_RS@latin that uses the Latin script, whereas sr_RS uses the Cyrillic script to write Serbian.
So here as the @latin represents a variant (here for more info: https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html ) so the default should be Cyrillic indeed.

**Comment by tomicakorac** [comment]
Although I do not agree with some of the arguments expressed in this thread, I do agree that Serbian translation should be done in Cyrillic. I have already completed the transliteration (plus a few minor changes to the existing translation) and made a pull request. Hoping to see this issue closed soon.

**Comment by aleksandar-todorovic** [comment]
This one should be closed because it is already resolved in https://github.com/elementary/mvp/pull/410
