### ISSUE TITLE
Quote tweet content not translated

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#412]
We're translating the display text, but not the text that is tweeted.

**Comment by aleksandar-todorovic** [comment]
@davidak We already had a long discussion about that [on Google+](https://plus.google.com/u/0/+DanielFor%C3%A9/posts/JKuhP3p9aP9).

**Comment by davidak** [comment]
@aleksandar-todorovic ok, thanks.

**Comment by lewisgoddard** [comment]
I'm guessing the easiest way to do this would be a little bit of JavaScript on that class to update the twitter link after the page has loaded with the translated quotation.
