### ISSUE TITLE
Get Involved says "Freya Beta 2" still

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#413]
This probably needs to be set such that it gets the name of the milestone we're pulling the graph data from

**Comment by lewisgoddard** [comment]
I don't think there's a way to set this programmatically that will ever work out as more efficient than just changing the title when we update the backend. I suppose we could add a variable, but it doesn't seem necessary to automate this.

**Comment by gamerlv** [comment]
I would have to agree with that. It would be nice to have it all change automatically, but I don't think it justifies the effort. It's not like we complete a milestone every 6 weeks
