### ISSUE TITLE
Discourse powered support page?

### ISSUE THREAD

**Issue by mominul** [elementary/mvp#422]
[Discourse](http://www.discourse.org/) is modern, smarter, Open Source like elementaryOS. Others are also using it for its modern-ness and features like [Ubuntu](http://discourse.ubuntu.com/). I like elementaryOS for its beauty, modern features. So I will be happy if developers use Discourse on the elementaryOS website.

Thanks!

**Comment by davidak** [comment]
it is the only forum software that is usable for me! it is out of the way and you can focus on the discussion 

used for example at https://discourse.syncthing.net/

but i think the support page should not be a forum, but a Q&A site where you quick find the answer to your question without the need to read a whole thread.

**Comment by lewisgoddard** [comment]
I am under the impression that the council do not want a forum, rather a specialised question and answer. As @davidak said, you shouldn't need to read a thread to find an answer.
