### ISSUE TITLE
Why do you not accept payments over $999,999.99?

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#423]

**Comment by lewisgoddard** [comment]
>What is the maximum amount I can charge with Stripe?
>
>There is a technical limitation of 999,999.99, regardless of the currency, though we don't impose any other limitations atop that. There are no weekly or monthly limits to the amount you can charge through Stripe.

https://support.stripe.com/questions/what-is-the-maximum-amount-i-can-charge-with-stripe
