### ISSUE TITLE
Not every available language is displayed

### ISSUE THREAD

**Issue by SyntheticDream** [elementary/mvp#434]
Hi everyone!
Recently i came across a strange issue: not every available translation is displayed in 'Languages' menu. All this time I've been thinking that Ukrainian translation is still not available (tho it is 100% ready on transifex since Feb 19), but today I tried 'uk' instead of 'ua' ( http://beta.elementary.io/uk/ ) and it worked (silly me).

To reproduce:
* open 'Languages' menu of [elementaryos website](http://beta.elementary.io/)
* open [transifex page](https://www.transifex.com/projects/p/elementary-mvp/)
* realize that lists don't match

**Comment by lewisgoddard** [comment]
The first thing we need to do is check out the directories in the [langs folder](https://github.com/elementary/mvp/tree/master/lang). I count 59 directories so we'll probably have to defer to the [transifex page](https://www.transifex.com/projects/p/elementary-mvp/) as you did to find out which ones are most complete. Setting the threshold to 100% seems a little harsh, but still leaves plenty of languages. The biggest gap however happens just below 75% where there is a jump to around 30%.

Then look at the `list_langs()` function in the `l10n` file in `_tempaltes` [here](https://github.com/elementary/mvp/blob/master/_templates/l10n.php#L2). This is where the actual functions come from. You need the language code, as the directory name in `langs`, and the title in it's native language.

Based on your request, you want `        'uk' => 'Мова',` added in there, but we should also get any that are complete enough added in at the same time. I believe @emersion is responsible for much of the translation work, wonderful as it is. I'll ask what people think the minimum translated should be.

**Comment by SyntheticDream** [comment]
Thanks!
>75% seems ok. BTW, maybe there should be some explicit note for translators on how to notify upstream about new translation. I've seen that some people do this through github, others wait for that happen magically (like me).

**Comment by lewisgoddard** [comment]
Upstream? You mean on Transifex?

This site has a [TRANSLATE.md](https://github.com/elementary/mvp/blob/master/TRANSLATE.md) that is supposed to detail how to properly translate and then update the site, but I think it needs some work.

**Comment by SyntheticDream** [comment]
>Upstream? You mean on Transifex?

I mean that even if translation is actually pulled from Transifex to the website, the 'Languages' menu is not updated at the same time, so you can access translation only from URL. But I might be wrong, because I'm not familiar with how this things work.

>This site has a TRANSLATE.md that is supposed to detail how to properly translate and then update the site, but I think it needs some work.

Yeah, I've read that, but there are no information for transifex coordinators (which I am).

Oh, and one more little thing, I think there was a misunderstating: "Мова" should be "Українська".

**Comment by lewisgoddard** [comment]
As of March 2nd, the required languages look like this. Everything marked "to add" requires a localised version of it's own name.

Code | Language | Percentage | On List
---- | -------- | ---------- | -------
ar_SD | Arabic (Sudan) | 100% | To Add
bg | Bulgarian | 100% | Yes
cs_CZ | Czech (Czech Republic) | 100% | Yes
nl | Dutch | 100% | Yes
en | English (source language) | 100% | Yes
fi | Finnish | 100% | To Add
fr | French | 100% | Yes
de | German | 100% | Yes
el | Greek | 100% | To Add
id_ID | Indonesian (Indonesia) | 100% | Yes
it | Italian | 100% | To Add
it_IT | Italian (Italy) | 100% | Yes
lt | Lithuanian | 100% | Yes
ne | Nepali | 100% | To Add
no | Norwegian | 100% | Yes
nb | Norwegian Bokmål | 100% | Yes
pl | Polish | 100% | To Add
pt_BR | Portuguese (Brazil) | 100% | To Add
pt_PT | Portuguese (Portugal) | 100% | Yes
ro_RO | Romanian (Romania) | 100% | Yes
ru | Russian | 100% | Yes
sr | Serbian | 100% | Yes
sr@Ijekavian | Serbian (Ijekavian) | 100% | To Add
es | Spanish | 100% | Yes
tr_TR | Turkish (Turkey) | 100% | Yes
uk | Ukrainian | 100% | Yes
ar | Arabic | 95% | To Add
fa_IR | Persian (Iran) | 90% | To Add
bs | Bosnian | 85% | To Add
zh_CN | Chinese (China) | 85% | To Add
et | Estonian | 85% | Yes
sv | Swedish | 85% | To Add
zh_TW | Chinese (Taiwan) | 80% | Yes
pl_PL | Polish (Poland) | 78% | To Add
hr_HR | Croatian (Croatia) | 73% | To Add
hu_HU | Hungarian (Hungary) | 38% | Maybe
sl | Slovenian | 36% | Maybe
hu | Hungarian | 29% | Maybe
