### ISSUE TITLE
Get Involved

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#44]
Either a new page or section needs to be created to explain how to contribute.

This section should include links to Launchpad, GitHub, and Bountysource at a minimum.

**Comment by danrabbit** [comment]
Mockup from Harvey: https://github.com/harveycabaguio/elementary-Site-Mockups/blob/master/Get%20Involved/Desktop.svg

**Comment by emersion** [comment]
I'll be happy to start to work on this tomorrow, if nobody starts before :-)

**Comment by danrabbit** [comment]
I think today I will try to get a simple navigation set up. That seems to be kind of a pre-requisite to me ;)

One thing I think we have to be careful with here is that many of the pages illustrated here may not exist. So we should be careful to make sure that we're only building things that are real.
