### ISSUE TITLE
Get Involved: Statistics are changing while scrolling on bigger screens

### ISSUE THREAD

**Issue by JulienMcJay** [elementary/mvp#469]
This bug happens on the "Get Involved" page on the beta website on elementary.io. But it happens only on bigger screens, I think. But this bug randomly appears while scrolling. Has anyone else this issue?

**Comment by lewisgoddard** [comment]
When scrolling? If the mouse moves over a bar the stats reflect it's content, using the last bar as the default when not over the chart. Is this what you are experiencing? If not, I'll need more thorough reproduction instructions.

**Comment by JulienMcJay** [comment]
Yes, I experienced what you mentioned. Sorry.
