### ISSUE TITLE
Change "elementary, LLC" to "elementary LLC."

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#47]
What it says on the tin. Minor technicality for the footer.

**Comment by lewisgoddard** [comment]
Is this how LLC is legally formatted? If you're using the legal name, it's probably best to follow whatever legal guidelines exist. "elementary, LLC" seems better because I read it as "elementary, Limited Liability Company", which is strange without a comma.

**Comment by danrabbit** [comment]
Well Cassidy is the legal owner of the LLC, so that's probably why he filed ;p I think formatting varies by region.

**Comment by cassidyjames** [comment]
“elementary LLC.” is the legal name of elementary LLC.
