### ISSUE TITLE
Recommended download option highlight

### ISSUE THREAD

**Issue by evfool** [elementary/mvp#471]
Currently when trying to download the beta ISO the dialog popping up shows a dialog with a button with black text on white background for 32-bit and a white text on blue background for 64-bit.
I can't tell you the exact reason why, but I have clicked the 32-bit button first twice instead of clicking the 64-bit button I wanted. I might be the dumb user, but maybe the readability is worse on the 64-bit button than on the other, or somehow the 32-bit is more visible than the other.
What about using another way to highlight the recommended button? E.g. Difference in size, using other colours, using some other sort of highlight, as the current one doesn't really work for me.

**Comment by danrabbit** [comment]
I'm going to close this. It sounds like we're going to discontinue 32bit during the next cycle
