### ISSUE TITLE
The countdown clock does not reach zero.

### ISSUE THREAD

**Issue by lolobergkamp** [elementary/mvp#472]
It currently says 3 days 24 hours.

![image](https://cloud.githubusercontent.com/assets/10854535/7026653/50099e9e-dd4b-11e4-854f-2b6b4d61535e.jpg)

**Comment by lewisgoddard** [comment]
The others suffer the same deficiency, they never state zero, and subsequently display their maximum +1

**Comment by fabianthoma** [comment]
Hey, I remember this beeing a design decision we conciously made back when we released Luna, to never show a 0 on one of these dails unless there really is no time left. I also remember that it looked weird when there was no circle. I can assure you that it correctly displayed as 3 days and 24 hours, it was a compromise.
