### ISSUE TITLE
Support page: misaligned icons w/long translations [$15]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#474]
On the support page, the icons become misaligned if the translated app name breaks into two lines. See here: https://plus.google.com/+Desiderantes93/posts/ckVzQgwmaHm

**Comment by desiderantes** [comment]
You can check this going to the support page on the spanish version of the site

**Comment by emersion** [comment]
Do you prefer to cut the text or to try to align properly icons while keeping the newline?

![screenshot from 2015-04-14 18-19-38](https://cloud.githubusercontent.com/assets/506932/7141552/a55fa0aa-e2d2-11e4-8b7a-ec057eec72c5.png)

![screenshot from 2015-04-14 18-22-45](https://cloud.githubusercontent.com/assets/506932/7141610/275c9ad6-e2d3-11e4-9a3d-dc2f2045f56b.png)

**Comment by lewisgoddard** [comment]
We should allow the text to push everything down after going onto two lines, I don't think it will ever be long enough to warrant cutting it.

**Comment by danrabbit** [comment]
Yeah I'm in favor of the second one showing both lines.
