### ISSUE TITLE
Add Patreon and Bountysource [$30]

### ISSUE THREAD

**Issue by fabianthoma** [elementary/mvp#478]
I guess this needs no further description, other than the question as to where.

**Comment by danrabbit** [comment]
Someone had a branch at one point that added monetary stuff to "get involved". As in get involved by funding us. Not sure what happened to the branch, but could be a place for it.

**Comment by danrabbit** [comment]
Found the PR with funding stuff https://github.com/elementary/mvp/pull/232

**Comment by lewisgoddard** [comment]
Fixed by #562
