### ISSUE TITLE
Add style for code blocks [$20]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#487]
We should copy the solarized-like style we had on the old docs. It was rad

**Comment by lewisgoddard** [comment]
It was indeed rad, **but** if we could make it match the new Scratch default even more, would that not be radder?

**Comment by danrabbit** [comment]
Haha for sure. But since the Scratch default is solarized... xD

**Comment by lewisgoddard** [comment]
Also, I would like to propose we drop the `$` so when I copy and paste I don't get weird errors. We should be able to use `::before { content: '$'; }` to emulate it.
