### ISSUE TITLE
Get Involved: variable height on header buttons in some languages [$15]

### ISSUE THREAD

**Issue by tengwar** [elementary/mvp#489]
As seen here:
![screenshot from 2015-04-12 00 10 04](https://cloud.githubusercontent.com/assets/7026772/7103452/92c5a560-e0a8-11e4-98dd-8b53934f6a6e.png)

<sub>BTW these translations are terrible, but I'm not going to create another account to fix them. And when I tried improving translations on Launchpad people kept reverting to the terrible, incomprehensible, unnatural word-for-word translations arguing that they "respect the Gnome translation guidelines".</sub>

**Comment by jordanlittle** [comment]
Adding <pre>vertical-align:middle</pre> to that nav link selector (.row.hero .actions .button.flat) at least makes things a bit more presentable.

**Comment by emersion** [comment]
@tengwar: these translations are not on Launchpad.

@jordanlittle: please make a PR :-P

**Comment by tengwar** [comment]
So it isn't possible to have them all with the same height? Well, at least jordanlittle's fix makes it better.

@emersion I know, I'm not going to create a Transifex account. But that part about Launchpad referred to Pantheon (+apps) translations.

**Comment by lewisgoddard** [comment]
@emersion It appears you have a bounty to collect.
