### ISSUE TITLE
Bluetooth "Set Up New Device..." Doesn't Work by Default

### ISSUE THREAD

**Issue by AMSmith42** [elementary/mvp#501]
Post install, if a Bluetooth adapter is installed, the "Set Up New Device..." under the panel icon does not launch anything.  The user must install the gnome-bluetooth package manually in order to launch 'bluetooth-wizard'.  The wizard will launch by either the command line or from the panel icon when "Set Up New Device..." is selected.  This solution is not obvious to the user, so gnome-bluetooth or a similar package should be installed by default.

**Comment by fabianthoma** [comment]
This project is for our website, I reported this bug on launchpad for you: https://bugs.launchpad.net/elementaryos/+bug/1443531

**Comment by AMSmith42** [comment]
Thanks.  I was confused.
