### ISSUE TITLE
Add hash sums to Installation page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#502]
Several people have asked for verified hash sums of the ISO, which is a good idea. Perhaps the Installation page would be a good place for this?

**Comment by lewisgoddard** [comment]
Sha1 will do?

**Comment by cassidyjames** [comment]
Works for me. Plus those are provided by Sourceforge.

**Comment by yashmehrotra** [comment]
Where should we put the Sha1 on the installation page ( right before download, or in the beginning ) ?

**Comment by lewisgoddard** [comment]
Maybe a little table at the bottom of the download section on [/docs/installation](http://elementaryos.org/docs/installation)

**Comment by yashmehrotra** [comment]
So how about adding something like this - 

| | MD5 | Sha1 |
-----------------|--------|-------|
Elementary OS Freya i386     |0ad75a048a89ee0bde5d7d333e5d5baf |4b82a9566c37464ca85eb29181e05cf538dd67f0 |
Elementary OS Freya amd64 |742cc5b2c21bb1872954b13b7b2091a3| ff02eec5cba2c060fd3a5ac85b48d4075bb4f1a3 |

**Comment by lewisgoddard** [comment]
1. elementary is _never_ capitalized. Capitals are for things that are important, and you operating system should just exist in the background.
2. We don't refer to them as i386 and amd64. Users might not know what those are and everywhere else says 32 Bit and 64 Bit. We shouldn't need to be more specific than that.
3. Maybe with a little magic we can make it so people only see the first few digits then ... off, but they can still copy any given code easily.

**Comment by yashmehrotra** [comment]
1 & 2. ok, so whats the best way to write this , Freya 32 bit ?
3. So, you mean add something like - If our mouse hovers over their it shows the full text ? ( This is what sourceforge uses btw ).

**Comment by lewisgoddard** [comment]
Seeing as there's only 1 release on the site right now, it can probably be kept as simple as "32 bit" and "64 bit".

Yes, what Sourceforge is doing seems better.

**Comment by lewisgoddard** [comment]
Reference for hashes. https://gist.github.com/lewisgoddard/0e6c89788ab71462c274

**Comment by davidak** [comment]
i think it should be the next step after download.

1. download iso
2. check iso
3. copy to usb thumb-drive

also the check instructions must be easy and usable on windows/os x/linux with on-board tools.

that could be included in the slider for windows / os x, linux.

a checksum display would also be a good feature for the copy programs.

**Comment by aleksandar-todorovic** [comment]
It will probably be useful to add the detailed steps here: https://elementary.io/docs/installation

So, maybe just add the sums in the installation process and link to that document for further reference?

**Comment by PhillipSz** [comment]
I think we should not provide MD5 hashes, as MD5 is really insecure and it should not be used anymore:
https://en.wikipedia.org/wiki/MD5#Security
https://twitter.com/natmchugh/status/624668649412923393
