### ISSUE TITLE
js styleguides, css methodology

### ISSUE THREAD

**Issue by Scribblex** [elementary/mvp#503]
I think, they are necessary. I know, that each of us is going to produce cool stuff, but the project will be better, if all contributors start to code in one style.

I consider, it is a good idea to make jcsrc-file. Here's the link: [jscs](https://www.npmjs.com/package/jscs). We can make manifesto and use it like code review guide, plugin in some IDEs, or even formatter to code.

I also want to ask, what do you think about using css methodologies: [bem] (https://en.bem.info/), preprocessors like less and post-processors.

What do you think?

**Comment by lewisgoddard** [comment]
We want our development to be as lean as possible so people can jump right in and build. I don't want people to have to know how to use less just to change a CSS style. We have both a [Code Style Guide](http://elementary.io/docs/code/code-style) and some web-specific guidelines in [CONTRIBUTE.md](https://github.com/elementary/mvp/blob/master/CONTRIBUTE.md). The problem with code style enforcers is, occasionally, the code style is wrong. There will always be exceptions, but JSCS doesn't like that.
