### ISSUE TITLE
No/Wrong clock settings on Lock Screen / Login Screen

### ISSUE THREAD

**Issue by joaojotta** [elementary/mvp#504]
I use and installed ElementaryOS 0.3 with the Portuguese (Lisbon) time settings witch automatically sets the clock for 24H but the Lock Screen / Login Screen is always on 12H setting.

There is (apperantly) no way to change that. Is there? Guess not.

Hope I'm wrong or, at least, that I helped with a bug report.

**Comment by cassidyjames** [comment]
Thanks for the report, @joaojotta. However, this is the issue tracker for our website, not the OS itself. :) You can report bugs for elementary OS at https://bugs.launchpad.net/elementaryos
