### ISSUE TITLE
Visual glitch after drag and drop

### ISSUE THREAD

**Issue by alarrosa14** [elementary/mvp#506]
drag&dropping icons of launcher menu reveals a GUI bug where mouse pointer looks odd (shown in the next image):  

![image](https://cloud.githubusercontent.com/assets/7881301/7127835/59a65b52-e220-11e4-98ed-3c23d853762b.png)
(sorry for the photo, a screen capture wouldn't show the mouse pointer)

**Comment by danrabbit** [comment]
This tracker is for the elementary.io website. Desktop bugs are not tracked here. This issue is already being tracked in the appropriate tracker. Closing this issue.
