### ISSUE TITLE
T-Shirts on Store page need real photographs

### ISSUE THREAD

**Issue by alexgleason** [elementary/mvp#538]
![screenshot from 2015-04-17 14 05 10](https://cloud.githubusercontent.com/assets/3639540/7209171/a305063e-e50b-11e4-81cd-4999637aefd1.png)

These t-shirts need real photos. The descriptions say: (Real-life photos coming soon!)

I just had the black terminal shirt shipped to me, and when I get it in I'm going to take a few photos for your consideration. While we're at it, they could possibly be retouched too (blue elementary shirt has a yellow background).

**Comment by alexgleason** [comment]
![terminal-tee](https://cloud.githubusercontent.com/assets/3639540/7508044/d2c31374-f43e-11e4-8e4b-9a4c07035579.jpg)
![terminal-tee](https://cloud.githubusercontent.com/assets/3639540/7508046/d75d848c-f43e-11e4-930f-671906254024.png)

Sources: https://drive.google.com/file/d/0BwfNEizpnybJN0VYVkRmVTdoNUE/view?usp=sharing

GPL

**Comment by lewisgoddard** [comment]
@alexgleason We just moved to MIT licensing, would you mind us using that to avoid doubling up?

**Comment by alexgleason** [comment]
@lewisgoddard Sure, MIT works. I was trying to make it compatible with the elementary logo since it's on my sleeve which I believe is GPL?

Btw when you say "we moved to MIT" do you mean just the website? Thanks.

**Comment by lewisgoddard** [comment]
Yes, the [website license](https://github.com/elementary/mvp/blob/master/LICENSE.md) is now MIT, I believe it's more compatible with most of the libraries used.

**Comment by alexgleason** [comment]
Okay I updated the license on the link above to match the site's license. Use it if you'd like, but it looks like the shop is managed externally so someone with access should do it.

Also, @danrabbit Is the tan background on the blue elementary tee intentional? If not it can be cropped out so the background is handled by CSS. Of course the trade-off is a ~1 MB image vs ~250 kB.

**Comment by lewisgoddard** [comment]
I think a slightly off-white, away from the color of the shirt is technically preferable. For instance, a blue shirt would have a slightly orange-tinged background, and orange would have blue tint. That decreases the artificial brightness around the product and makes the colors appear more natural and full.

**Comment by danrabbit** [comment]
TBH, I don't think it's a good idea to use this image. It's pretty apparently fake.

**Comment by alexgleason** [comment]
@danrabbit I understand. If you think it's worth fixing I linked the source images above.

Out of curiosity how was the first photo taken?
