### ISSUE TITLE
Top navigation should be responsive

### ISSUE THREAD

**Issue by alexgleason** [elementary/mvp#539]
![screen shot 2015-04-17 at 4 39 14 pm](https://cloud.githubusercontent.com/assets/3639540/7211444/6f771bb2-e520-11e4-8a99-f5243453f730.png)

The current implementation is not absolutely horrible, but it's also difficult to press on small screens without zooming (the 'e' logo and nav items are too small) and the nav items also don't collapse like they should.

**Comment by alexgleason** [comment]
This needs design however. A common approach would be to just enlarge the logo, then have clickable menu button at the side that reveals the nav items in a menu.

For instance, here is a mobile nav menu I recently implemented at my work:

![screen shot 2015-04-17 at 4 47 18 pm](https://cloud.githubusercontent.com/assets/3639540/7211567/a501b12e-e521-11e4-8c37-57d5a8cc1054.png)

Clicking the "Menu" button toggles the visibility of the nav items.

I can implement something like this if the solution is agreed upon.

**Comment by danrabbit** [comment]
This is a duplicated of #275 

Gonna close this.
