### ISSUE TITLE
'Click to tweet' on quotes doesn't show

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/mvp#541]
On Windows, Chrome 42, the 'click to tweet' thing for quotes on the home and get involved pages do not show the text.
![image](https://cloud.githubusercontent.com/assets/2775325/7214046/68e420e2-e55c-11e4-926f-04a4c61f16ee.png)

**Comment by danrabbit** [comment]
This is actually due to your ad blocker. If you turn that off they'll show up.
