### ISSUE TITLE
API Key Error [$20]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#548]
Some users are reporting an API key error. The following browsers have been reported:
* Firefox 37
* Chromium 41
* Chrome 42
* Safari 8

**Comment by danrabbit** [comment]
Just got another report of Chrome Version 42.0.2311.90 (64-bit)

**Comment by lewisgoddard** [comment]
This is because we're loading the API key asynchronously, after `homepage.js` is done, it fires of a fetch for that. If they try and pay before then it will not work. We should probably add an include so it is a short snippet in the header.

**Comment by danrabbit** [comment]
IMO this is of the utmost importance. We're getting a LOT of reports of this issue.
