### ISSUE TITLE
Add edit links in docs

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#581]
It would be really rad if there was a way to have an edit link which would show the relevant .md file in GitHub. Might encourage more edits and at the very least it would be convenient for us.

**Comment by seanballais** [comment]
Oh, it would then be like a wiki. Should the editor be anonymous or should have an account? We must protect the docs from trolls though.

**Comment by emersion** [comment]
Since this would show the .md file in Github, contributors would have to make a PR.

What for translations

**Comment by danrabbit** [comment]
@emersion hm that's a good question. I think I would say still the source.

**Comment by lewisgoddard** [comment]
@danrabbit Slack has a channel switcher at the bottom of their sidebar (kind of like our big-doc navigation sidebar) which is twice the height of a normal row and switches to an icon except on hover. Would something like that be good?
