### ISSUE TITLE
Update hash/fragment when scrolling in docs

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#595]
Right now in the docs if you click to a section, then scroll on a bit, the URL still includes the hash of the earlier section.

Would it be useful to update the hash to link to the current section?

**Comment by lewisgoddard** [comment]
I assume this should only apply to docs, and not every id we scroll past.

Check out `/scripts/smooth-scrolling.js` for how to get an id quickly from an absolute path in javascript.

**Comment by cassidyjames** [comment]
@lewisgoddard yes, only in docs.
