### ISSUE TITLE
Add payments with stripe

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#6]
Sounds like stripe checkout is the way to do it

**Comment by cassidyjames** [comment]
How should this flow look? Click the button and get a dialog (like the current site)?

**Comment by cassidyjames** [comment]
Looks like we can tie it to a button/link. To keep the ability to download for pay-what-you-want or free, we need to:

1. let the user define an amount (whether it's free-form or a few options)
2. If they choose 0/free, just give them the download
3. if they choose a fee, trigger Stripe.

https://stripe.com/docs/checkout

**Comment by danrabbit** [comment]
Yup that sounds right to me. Nice and simple. We could stick with current pre-populated entry design for now and decide if we want something more elaborate later.

**Comment by cassidyjames** [comment]
Started on the pre-populated entry at https://github.com/elementary/mvp/tree/variable-payment

**Comment by danrabbit** [comment]
So we talked in IRC about doing something similar to Humble:

![screenshot_21_42_15](https://cloud.githubusercontent.com/assets/7277719/5793989/886b3844-9f0f-11e4-9ec5-1e3517f06130.png)

We've implemented an entry at https://github.com/elementary/mvp/tree/stripe-payment

**Comment by fabianthoma** [comment]
Paying with stripe is added, now the buttons and adjusting the value is missing. @lewisgoddard is gonna do this.
