### ISSUE TITLE
Justify paragraphs/text in docs

### ISSUE THREAD

**Issue by embik** [elementary/mvp#608]
I'm not really sure if it's worth an issue and it's more personal opinion than anything else, but I really would like to see justified paragraphs in the docs (for example [here](https://elementary.io/docs/code/getting-started)). At least to me, it's way easier to read long texts with it. Not sure if it's important to anyone else though.

**Comment by lewisgoddard** [comment]
I don't think the design team would like the idea of justified text, it makes the word spacing uneven and hasn't been shown to actually improve things except glancing looks.

**Comment by cassidyjames** [comment]
Yeah, left-aligned/ragged-right is more readable. We used justified text on the old site but have moved away from it for elementary things.
