### ISSUE TITLE
Update the @elementary organization website url

### ISSUE THREAD

**Issue by IonicaBizau** [elementary/mvp#610]
Currently it uses `.org` domain which is redirected to `.io`. Since this is not a big problem, I think you still have to update it. :smile: 

> ![screenshot from 2015-04-27 12 01 12](https://cloud.githubusercontent.com/assets/2864371/7344545/20a45a7e-ecd5-11e4-8275-9bcf175c7cb6.png)

**Comment by KeitIG** [comment]
poke @danrabbit

**Comment by gamerlv** [comment]
Updated

**Comment by IonicaBizau** [comment]
Cool! Keep up the good work! :+1:
