### ISSUE TITLE
Geary, scroll-bar right of list messages.

### ISSUE THREAD

**Issue by belousovsw** [elementary/mvp#611]
Hi.
Geary, scrollbar between list message pane and preview message, mouse pointer not scroll list, only by mouse scroll wheel.

Sorry for my english, and thanks for a "Elementary OS"
![default](https://cloud.githubusercontent.com/assets/8617855/7355497/f2fdb8b2-ed2a-11e4-983e-feb5dd397bd4.jpg)

**Comment by danrabbit** [comment]
This tracker only tracks issues for elementary.io. It does not track issues for applications. Please report this issue against Geary in BugZilla https://bugzilla.gnome.org/page.cgi?id=browse.html&product=geary
