### ISSUE TITLE
Navbar overflow breaks on mobile with long strings

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#619]
If you visit the elementary site with German translation (which has longer strings, which I presume is the cause of the issue here) the navbar not only has x-scroll but also y-scroll and the navbar elements are split in two lines (just like before, only you now have to scroll x and y in that tiny container).

**Comment by danrabbit** [comment]
It looks like the width of `nav > .nav-content` is hard coded.

**Comment by quassy** [comment]
Personally I don't like the (quite new) vertical scrolly thing because it is not discoverable (alternative would be to have a ... button when there is hidden overflow) and it also breaks in small windows on desktop browsers. IMO the links should be displayed in two rows again, just a bit nicer looking, e.g. with equal spacing so it looks intentional and not weird like it did before.

**Comment by cassidyjames** [comment]
Isn't fully fixed, just worked around. Reopening.

**Comment by ericorruption** [comment]
What about using a menu button and a hidden, stacked menu when the page is loaded on small screens? Clicking/tapping the button would reveal the menu.

Then as the device width grows to some amount of pixels, we show the current, inline navbar.

**Comment by quassy** [comment]
As there are only five menu elements I don't think a hamburger menu is *"justifiable"*. Simply having two lines of menu entries is much more discoverable.
