### ISSUE TITLE
Desktop Development Scratch screenshot is distorted

### ISSUE THREAD

**Issue by codygarver** [elementary/mvp#622]
The titlebar in this Scratch screenshot is distorted: elementary.io/images/get-involved/desktop-development.svg

Attached is a screenshot of the page for context:
![desktop-development-bad-scratch-screenshot](https://cloud.githubusercontent.com/assets/2166391/7403429/4eb0b97c-ee9b-11e4-9e59-2354dbbc383f.png)

**Comment by cassidyjames** [comment]
I think it's that the right font isn't being used?

**Comment by lewisgoddard** [comment]
I'm not sure if it's any help, but this is what I see when I close everything.
![screenshot from 2015-05-07 16 03 25](https://cloud.githubusercontent.com/assets/831389/7518409/a35a985c-f4d2-11e4-9c5c-1909c172ca2f.png)

**Comment by quassy** [comment]
How are the shadows for the [window screenshots](https://github.com/elementary/mvp/blob/master/images/get-involved/desktop-development.svg) generated?
