### ISSUE TITLE
Build in analytics / service to detect site issues, 404s

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#629]
> There should be a listener service that checks if certain URLs receive a high amount of 404s and then a redirect could be established. 

Having said that in a different bug report I'd like to rephrase: elementary should probably use Piwik to get some stats on site usage and also identify potential issues with the site.

**Comment by gamerlv** [comment]
We already have stats tracking using google analytics. However I'm not sure who has control over that. Wouldn't a piwik install be a bit overkill for just tracking 404 hit's?

**Comment by lewisgoddard** [comment]
We could add an event to track 404 errors with Google Analytics, as well as most other errors you can think of.

**Comment by quassy** [comment]
@gamerlv Piwik would only make sense as an alternative to Google Analytics of course, I didn't know MVP already used GA. Personally I think using GA is a huge privacy issue even though it is somewhat more comfortable than Piwik.

@lewisgoddard :+1:
