### ISSUE TITLE
Delete cookies section of Privacy Policy is missing Epiphany

### ISSUE THREAD

**Issue by snwh** [elementary/mvp#631]
Epiphany is common enough of a browser on Linux to perhaps include instructions for deleting cookies from it.

**Comment by danrabbit** [comment]
We need their icon and a link to directions

**Comment by snwh** [comment]
I've all that. :)

**Comment by danrabbit** [comment]
Wanna share with the rest of the class then?

**Comment by snwh** [comment]
Why not just file a pull request? :)
