### ISSUE TITLE
Donate button for website besides the one for download

### ISSUE THREAD

**Issue by Thegoru** [elementary/mvp#634]
Please add a visible donate button besides the one for when you download it (I would actually put the option of $0 available for the download button). Here is why, I did not donate at first (used the Custom = 0), since I wanted to try it first but after people see how awesome it is they will want to donate. You don't want to make people feeling like you are trying to trick them (especially us nerds).So it would be great if you add an option of $0 for the download and give people to opportunity to come back and donate by adding a visible donate option. Also, when you click on the donate button for the download to enter your credit card currently it says "Pay", I suggest changing that to "Donate". It just sounds better for public relations.

**Comment by snwh** [comment]
But it's not a donate model. It's a pay-what-you-want model.

**Comment by Thegoru** [comment]
You guys already have the funding option on "get involved - funding" for Patreon, I would just suggest at-least bringing that option the the main page for returning folks like me. For the download, the option of 0 should be there and visible, in my opinion since it is open source. For example in my case, I would not pay for a distro until I try it and see that I like it, which is what I did in this case and had to cancel the second download to pay for the awesome OS. I think there would be other people who would do that, too.  To summarize, there should be a visible option to come back and contribute (pay/donate) to the project without any hassle.

**Comment by danrabbit** [comment]
Sorry OP, we're going to stick with making people type 0. We really on funding to keep elementary afloat. 

#624 is about adding Stripe (Credit and bitcoin) to the get involved/funding page.

We purposely don't use the word "Donate" because we're not a non-profit organization and we don't want to trick people into thinking we are. Your payments are not tax-deductible.

**Comment by Thegoru** [comment]
I understand. I guess just adding that option for returning folks who did not pay initially would be nice without having to click the download button. 

Just for kicks and beyond, below is a suggestion on how to make people pay you (I just read your blog on the whole controversy with the pay-what-you-want model). I do believe you guys should get paid for the great work, hopefully without pissing off to many people. 

Remembering learning this in a class, make people feel like they are being watched to act just. Plato wrote about it, too. I think it could be applied to the open source software to increase contributions. Put some eyes on the download screen and add a 0 option or not? Could get creative with it. There is a lot of research that says it might work.

Here is an article about it:
http://www.scientificamerican.com/article/how-the-illusion-of-being-observed-can-make-you-better-person/

Thanks for the response!
