### ISSUE TITLE
Resize the Notebook Hero image based on media

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/mvp#647]
Google complains about (82% reduction) notebook.png, maybe have it so it scales from different files?

**Comment by cassidyjames** [comment]
Are you sure it's the notebook hero and not the wallpaper?

**Comment by cassidyjames** [comment]
I'm getting tiny compression on either one, only a 4% reduction.

**Comment by cassidyjames** [comment]
(and after the 4% reduction, it looks like poo)

**Comment by cassidyjames** [comment]
@lewisgoddard is drunk, Google said resizing it could reduce filesize. They're already compressed as much as possible without losing quality. Editing the title. :)
