### ISSUE TITLE
Fix Caching of Static resources.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/mvp#648]
### Leverage browser caching

Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.

Leverage browser caching for the following cacheable resources:

http://elementary.io/images/notebook.png (4 hours)
http://elementary.io/images/screenshots/background.jpg (4 hours)
http://elementary.io/images/screenshots/midori.png (4 hours)
http://elementary.io/images/screenshots/music.png (4 hours)
http://elementary.io/images/screenshots/photos.png (4 hours)
http://elementary.io/images/screenshots/videos.png (4 hours)
http://elementary.io/images/support/midori.svg (4 hours)
http://elementary.io/images/support/multimedia-audio-player.svg (4 hours)
http://elementary.io/imges/support/multimedia-photo-manager.svg (4 hours)
http://elementary.io/images/support/multimedia-video-player.svg (4 hours)
http://elementary.io/images/thirdparty-logos/lifehacker.svg (4 hours)
http://elementary.io/images/thirdparty-logos/maclife.svg (4 hours)
http://elementary.io/images/thirdparty-logos/wired.svg (4 hours)
http://elementary.io/scripts/homepage.js (4 hours)
http://elementary.io/scripts/jQuery.leanModal2.js (4 hours)
http://elementary.io/scripts/slider.js (4 hours)
http://elementary.io/styles/home.css (4 hours)
http://elementary.io/styles/main.css (4 hours)

**Comment by ericorruption** [comment]
What about spriting images and minifying js and css? Does someone have plans on that?

**Comment by lewisgoddard** [comment]
@ericorruption 

Most of our images are big and beautiful, whereas spriting is best for smaller images like icons, which we would try to replace with CSS equivalents.

As for minifying, that's a relevant (but separate) issue. While it has been confirmed that minification and gzipping in conjunction deliver the best results, while in active development a compromise was made between ease and speed.

**Comment by lewisgoddard** [comment]
@fabianthoma Can you update the server to reflect the changes added here?

```
    # Cache Static Assets until they are changed.
    location ~* \.(html|css|js|png|jpg|jpeg|gif|ico|svg|eot|woff|ttf)$ { expires max; }
```

**Comment by gamerlv** [comment]
Added the nginx cache setting to the live config. Not entirely sure if it will work as expected because of cloudflare.

**Comment by lewisgoddard** [comment]
Cloudflare has been updated to reflect these changes.
