### ISSUE TITLE
Abstract footer

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#65]
We should probably pull the footer out into its own file and have it appended to each page to make sure it stays consistent and updated across pages.

This is kind of a pre-requisite to multiple pages.

**Comment by lewisgoddard** [comment]
While I hate to say it, PHP is the biggest and most well-supported amongst web hosts. A simple `include '_template/footer.html';` will pull in your template file.

**Comment by KeitIG** [comment]
We can consider a single-page website and then call page-content via Ajax too. Cleanest way to do it in JS.

**Comment by lewisgoddard** [comment]
With JS, so long as the actual content is prioritised, it's fine by me. Server side is probably faster though, since it's one less initial http request. We can use ajax for subsequent pages.

**Comment by cassidyjames** [comment]
I'm leaning on PHP just because it's super easy. :) Also, I'd like to avoid AJAXing parts of the website in unless necessary.
