### ISSUE TITLE
Slider alignment glitches when moved too fast

### ISSUE THREAD

**Issue by btkostner** [elementary/mvp#651]
The homepage app slider glitches and defaults to main photos screen when you click the selector too fast.

Video: https://www.youtube.com/watch?v=z9YQvbViqsY

**Comment by cassidyjames** [comment]
I remember seeing this. I'll take a look at the CSS animation. I remember something similar happening on the slingshot branch before we tweaked the animations.

**Comment by cassidyjames** [comment]
:alarm_clock: 7pm | Reminding myself to take a look. :)

**Comment by cassidyjames** [comment]
@danrabbit I'm still seeing this exact behavior at elementary.io, I'm not sure that branch fixed this specific issue. Unless it's a caching thing.
