### ISSUE TITLE
404 for user guide URL

### ISSUE THREAD

**Issue by jeffmcneill** [elementary/mvp#660]
This link is on Distrowatch but 404s. In general, 404s should be monitored, so some system for that. Better would be a 404 page that returns an internal search result to try and find said missing page:

https://elementary.io/docs/user-guide

**Comment by lewisgoddard** [comment]
This was partially fixed a week ago with #639 "Add tracking to the 404 page.", and will be monitored in the future.

The URL [/docs/user-guide](http://old.elementary.io/docs/user-guide) never existed on the new site, and is likely a remnant from the old release. It's probably best to link to [/docs/learning-the-basics](http://elementary.io/docs/learning-the-basics).

**Comment by jeffmcneill** [comment]
You should add a redirection (301) in .htaccess or whatever cms you have. These links were built by lots of people over time. Fight linkrot.

**Comment by lewisgoddard** [comment]
I;m going to group this with my other 404 corrections over at #646, which kind of makes this a duplicate.
