### ISSUE TITLE
Resize the wallpaper image based on media [$25]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#664]
Same as #647 but for the wallpaper image.

<bountysource-plugin>
---
[Bounty on Bountysource](https://www.bountysource.com/issues/14909210-resize-the-wallpaper-image-based-on-media)

**Comment by lewisgoddard** [comment]
I think it just doesn't apply to smaller formats at the moment, although I'm not sure of the cut-off, it goes to a block color.

**Comment by mindslost** [comment]
Maybe I don't understand the whole issue, but using the following CSS code will make the image resize per the size of the browser.

```css
background-image: url("../images/screenshots/background.jpg");
position: absolute;
width: 100%;
```

**Comment by lewisgoddard** [comment]
@mindslost We're looking for something that loads a digitally smaller image for smaller formats, to save on bandwidth. This is a current code example:
```
#carousel {
    background-color: #0d6c7f;
    background-image: linear-gradient(to bottom,
                                  #015263,
                                  #338b9f
                                  );
}
@media (min-width: 1350px) {
    #carousel {
        background-image: url("../images/screenshots/background.jpg");
        background-size: cover;
        height: 100vh;
    }
    #carousel .slide > .column:nth-child(2) {
        margin-top: 33px;
    }
}
```

**Comment by Lukewh** [comment]
Something like this? https://github.com/elementary/mvp/compare/master...Lukewh:idea-664?expand=1

The images aren't optimised, I quickly resized them. Wanted to check this is what was meant before proceeding further.

**Comment by lewisgoddard** [comment]
@Lukewh Take a look here for how we did the last one. We probably don't need as many breakpoints as you suggested. https://github.com/elementary/mvp/pull/744/files

**Comment by Lukewh** [comment]
@lewisgoddard I've updated https://github.com/elementary/mvp/compare/master...Lukewh:idea-664?expand=1 to be stylistically similar to https://github.com/elementary/mvp/pull/744/files. I don't think we can just resize the image due to the 'cover' nature and the ratio changes. Let me know what you think and I'll make the images higher quality.
