### ISSUE TITLE
Simple International Store [$50]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#670]
We should build a super simple international sticker store.

- [x] JSON-based product list
- [x] Stripe to accept payments
- [x] International address form
- [x] Send data to payment@elementary.io

We can then manage this all on our (@maffity's and my) end. I mention stickers-only because they don't require customs forms or shipping provider integrations whereas tees would.

**Comment by cassidyjames** [comment]
I should also add

- [ ] Auto-detect default location (US or not) and show the appropriate store
- [ ] Provide a way to switch between stores (in case out auto-detection gets it wrong)

**Comment by eddiemoore** [comment]
+1

**Comment by addicted1adi** [comment]
You are planning it for desktop or mobile devices?

**Comment by addicted1adi** [comment]
share json link

**Comment by cassidyjames** [comment]
@addicted1adi I have a branch with HTML and some CSS in #673. Here is a sample of what some JSON could look like:

```json
{
  "products": [
    {
      "name": "Logomark Stickers (set of 3)",
      "sku": "sticker-logomark-set",
      "price": 1.50,
      "qty-options": [
        {
          "0": "None",
          "1": "1 set",
          "2": "2 sets",
          "3": "3 sets",
          "4": "4 sets",
          "5": "5 sets",
          "6": "6 sets",
          "7": "7 sets",
          "8": "8 sets",
          "9": "9 sets",
          "10": "10 sets"
        }
      ],
      "desc": "Set of blue 2-inch (5 cm) circle stickers with the elementary &lsquo;e&rsquo; logomark in white. Silkscreened on premium vinyl and layered with three coats of 100% UV protection meaning your stickers will stick for several years without fading.",
      "image": "http://placehold.it/600&text=Logomark Stickers"
    },
    {
      "name": "Logotype Sticker",
      "sku": "sticker-logotype",
      "price": 3.00,
      "qty-options": [
        {
          "0": "None",
          "1": "1",
          "2": "2",
          "3": "3",
          "4": "4",
          "5": "5",
          "6": "6",
          "7": "7",
          "8": "8",
          "9": "9",
          "10": "10"
        }
      ],
      "desc": "elementary logotype in white on a transparent vinyl sticker; perfect for your laptop or car window. Measures approximately 8 × 2&Prime; (20 × 5 cm). Silkscreened on premium vinyl and layered with three coats of 100% UV protection meaning your stickers will stick for several years without fading.",
      "image": "http://placehold.it/600&text=Logotype Sticker"
    }
  ]
}
```

**Comment by cassidyjames** [comment]
@addicted1adi here's the branch on the beta site: https://beta.elementary.io/branch/international-store/international-store

**Comment by cassidyjames** [comment]
@addicted1adi and lastly, our whole site is always mobile-first and responsive across mobile and desktops. See our README at https://github.com/elementary/mvp#architecturephilosophies

**Comment by souravsingh** [comment]
This issue looks bitesized to me.Can I work on it?

**Comment by KeitIG** [comment]
@souravsingh sure, go for it :+1: Just be ready to commit over and over after our code reviews ;)

**Comment by lewisgoddard** [comment]
I wouldn't describe this as bitesize, there's quite a few things to do.

**Comment by bonndan** [comment]
Came here in search for the stickers (living in Germany). Do you really want to write yet-another-store? Sounds neither bitesize nor a good invest of efforts to me. I am not much of an ecommerce guy, but after two minutes googling I found prestashop offering a free cloud based store (though the stripe module might not be free).

**Comment by LGCoder** [comment]
I might start working on this..... there is a bounty hunter "adi" working on this issue 9 months ago.... should I start or could adi let me know? Also, need more terminal tees, ironic and off subject, but I am waiting for the terminal tees.....

**Comment by btkostner** [comment]
The new store is going to display items from (amplifier)[http://amplifier.com/] and use (stripe)[https://stripe.com/] to process payments. Current work on it is in the `new-store` branch.
