### ISSUE TITLE
Payment of a decimal dollar amount

### ISSUE THREAD

**Issue by nunomaduro** [elementary/mvp#675]
Hey,

The price customization box should not accept decimal values such as 0.5?

**Comment by lewisgoddard** [comment]
We don't currently accept payments below one dollar or at a fraction of a cent.
Apart from that, decimals such as 1.2 will become $1.20.

This has drawn my attention to the fact that 0.5 behaves like 0 with no indication as to why.

**Comment by KeitIG** [comment]
Is it a Stripe limitation or ours ?

**Comment by danrabbit** [comment]
It's ours.  But it's because of processing fees. Under a dollar it's not even worth it to process the transaction because the majority of it will be fees

**Comment by lewisgoddard** [comment]
If you're wondering about the fees, you can view a breakdown here: https://docs.google.com/spreadsheets/d/15cVmPH3PYQyM3maI3hW6mv2tNVqv5DZeexB2D-3WwlU/edit?usp=sharing
