### ISSUE TITLE
Review .column responsive behavior

### ISSUE THREAD

**Issue by KeitIG** [elementary/mvp#676]
Hello everyone, 

not an issue, just a discussion.

#### Default behavior
![capture du 2015-05-22 13 12 29](https://cloud.githubusercontent.com/assets/1311607/7769480/6573d4c8-0084-11e5-9550-b889064aeff1.png)

#### How in my opinion it should be
![capture du 2015-05-22 13 12 15](https://cloud.githubusercontent.com/assets/1311607/7769479/655f3ca2-0084-11e5-8e29-fa01d34d147d.png)

what do you think about that ?

**Comment by lewisgoddard** [comment]
Possible duplicate of #332

**Comment by IsmaOrdas** [comment]
Why not make the column wider? Like 80% oo 90% of the viewport and set a bigger font-size.

**Comment by KeitIG** [comment]
No need to keep this open.
