### ISSUE TITLE
Branding/Logos page

### ISSUE THREAD

**Issue by Moini** [elementary/mvp#677]
Hi everyone,

I've been looking for some logo usage guidelines and easily accessible logos on your website, but wasn't able to find them. 
Could you add a page with at least both logos (e only, and elementaryOS) in svg and some hints about the cases when they may be used (by press, support companies, or other software projects, etc.)?

(The reason I was looking for a logo was that our open source software deployment tool m23 (remote installation and client management via network to physical and virtual clients) now supports remote installation and updates/backups/package installation/etc. for elementaryOS, http://m23.sf.net).

I had asked the same question over at lp (https://bugs.launchpad.net/elementaryos/+bug/1457095), and got permission ;), but for the others who will search for this same thing, it may be useful to provide a page (saves you some answers ;) ).

**Comment by cassidyjames** [comment]
@Moini, thanks for the report! We do have logos available at http://bazaar.launchpad.net/~elementary-design/+junk/brand-assets/files, but it's not easily found. :smile: 

I agree, having some sort of logo/brand guidelines and assets readily available from the site would be beneficial for press, third-party devs, etc.

**Comment by Moini** [comment]
@cassidyjames, thanks for the link :) I noticed there's a blue one, too. That would look less pale among all the other distro logos on our page. Is the blue one still 'current' or is it deprecated?

**Comment by cassidyjames** [comment]
@Moini it's still current!

**Comment by Moini** [comment]
@cassidyjames: Thanks :D

**Comment by yaabdalla** [comment]
@cassidyjames I'd work on creating this page, but I'm not sure what information to provide on usage cases. Any help?

**Comment by lewisgoddard** [comment]
There was a document detailing the spacing to use for logos and such, but I can't seem to find it anywhere. http://blog.elementary.io/post/107640994166/the-importance-of-our-brand has a similar theme, but none of the images I'm after.

**Comment by aleksandar-todorovic** [comment]
Yup, I referenced so many times to that blog post that I really do think that something similar should be in the documentation as well.

My suggestions:

* Including the logos (in both `.svg` and `.png` formats) and clear guidelines on what should and should not be done with them.
* Stating the importance of correctly referencing to the elementary OS (like using lowercase `e` all of the time, putting a space between the word `elementary` and the word `OS`, not referencing it as `eOS` and things like that).

I believe that those two suggestions should be in the same document. 

I think that it would also be useful to state the way third-party developers should be using elementary's brand (like creating a simple picture saying `designed for elementary OS` that third-party developers could use in their products).

**Comment by Moini** [comment]
(just inserted a space into all occurrances on our website ;) Thx, Aleksandar!)

**Comment by aleksandar-todorovic** [comment]
Don't worry, you're far from the only one. :)

**Comment by cassidyjames** [comment]
https://slack.com/brand-guidelines is a great example of what we're after. I'll work on this!
