### ISSUE TITLE
drag and drop changes the mouse point weired

### ISSUE THREAD

**Issue by yellowairplane** [elementary/mvp#678]
I usually use "drag and drop" to copy files. But in elementary OS, that makes the mouse point weired, which looks perfect before.

**Comment by lewisgoddard** [comment]
Unfortunately, this is a bug tracker only for the elementary.io website. Fortunately, the bug you are looking for is already filed at https://bugs.launchpad.net/ubuntu/+source/xorg-lts-utopic/+bug/1390625
