### ISSUE TITLE
False translation on the main page

### ISSUE THREAD

**Issue by JulienMcJay** [elementary/mvp#680]
On the german version of elementary.io it says:

"Surfe das Internet mit einem schnellen & leichten Web-Browser. Midrori läd HTML5 Webseiten und Web-Apps während er wenig Akku verbraucht."

but it should be

"Surfe das Internet mit einem schnellen & leichten Web-Browser. Midrori lädt HTML5 Webseiten und Web-Apps während er wenig Akku verbraucht."

There is a missing "t" on the word "läd", but it should be "lädt".

There are much more translation errors on the main page.

Hope anyone fixes this soon.

*~JulienMcJay*

---

**Screenshots:**

![Screenshot taken from elementary.io](http://i.imgur.com/NKvJ8ZM.png)

![Screenshot taken from elementary.io](http://i.imgur.com/Ine3dmU.png)

and much more issues...

**Comment by KeitIG** [comment]
Hi @JulienMcJay ! 

Thanks for reporting this :+1:  Everything related with translations go on Transifex. See https://github.com/elementary/mvp/blob/master/TRANSLATE.md for more details.
