### ISSUE TITLE
"Meet our apps" awkward on big displays

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#681]
![screenshot from 2015-05-26 11 51 20](https://cloud.githubusercontent.com/assets/611168/7819262/a7fd91dc-039d-11e5-960f-f4aee8ab20e9.png)

We should find a way to keep it more centered.

**Comment by lewisgoddard** [comment]
```
#carousel .slide.row {
  max-width: initial;
  margin: 0 calc(50% - 700px);
}
```

[Browser Support for `calc`](http://caniuse.com/#feat=calc)

![screenshot from 2015-05-26 19 11 04](https://cloud.githubusercontent.com/assets/831389/7819652/0ab70c6c-03db-11e5-854b-7403b6cd7aa8.png)
