### ISSUE TITLE
Space/Ellipsis text  messed up in HIG

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#685]
See https://elementary.io/docs/human-interface-guidelines#prevent-common-mistakes, compare to http://old.elementary.io/docs/human-interface-guidelines/punctuation.

> * Only use **one space** after a period.
>   * i.e. “This is a sentence. This is another sentence.”
>   * Use `\u0133` in your code.
>   * See [Using Ellipses](#) for usage details.

Should be:

> * Only use **one space** after a period.
>   * i.e. “This is a sentence. This is another sentence.”
> * Use a proper **ellipsis character** (…) rather than three dots.
>   * Use `\u0133` in your code.
>   * See [Using Ellipses](#) for usage details.

**Comment by aleksandar-todorovic** [comment]
Wait, Using Ellipses document is not still updated? Where should the link lead to?

**Comment by lewisgoddard** [comment]
To the "Using Ellipses" section on the same page. https://elementary.io/docs/human-interface-guidelines#using-ellipses
