### ISSUE TITLE
Footer floating above content

### ISSUE THREAD

**Issue by btkostner** [elementary/mvp#69]
The footer of the page floats over the content when the screen height is smaller than the content.

**Comment by btkostner** [comment]
![image](https://cloud.githubusercontent.com/assets/3385679/5698074/8cab0c8e-99c1-11e4-9a45-6ef85764ae81.jpg)

**Comment by lewisgoddard** [comment]
This also happens if the content is taller than the viewport, the footer will scroll up with the content and overlay.

**Comment by cassidyjames** [comment]
@danrabbit was aware when he wrote the styles for the page and was just waiting to address it until it became a problem. :)

A possible solution is to take off the absolute positioning and give the wrapper a `min-height` of `90vh` (or something). This lets the footer flow as part of the normal box model while making sure it's nearer the bottom on short pages.

**Comment by KeitIG** [comment]
I'm no sure it would look good on mobile. I would set a height on <footer>
