### ISSUE TITLE
Mention casting in code style guide

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#693]
According to a conversation that Rico had the other day with Christian:

`(widget as Gtk.Entry).max_width_chars` using `as` for casting is not a good idea
`(widget as Gtk.Entry)` can be `null`, if you know what the object is then use `((Gtk.Entry) widget).max_width_chars`. If you use `as` you need to add a `nullcheck` to do it properly.

So we should recommend:
`((Foo) Bar).method`

Not
`(Foo as Bar).method`

**Comment by lewisgoddard** [comment]
Is this already in the code style and is wrong, or is it an entirely new section?

**Comment by pavlicekl** [comment]
No, it's not mentioned in code style anywhere.
Deserves a new section, I suppose.

**Comment by lewisgoddard** [comment]
Fixed by #876 876
