### ISSUE TITLE
Add Meta tags for Social Networks

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#70]
We should add the proper meta tags so social sites like Google+ and Facebook pick up a nice title, description and thumbnail.

**Comment by hollissam3** [comment]
What would the powers that be like to have for the content?

**Comment by KeitIG** [comment]
SEO I guess,

minimal code:
```
<!-- Twitter Card data -->
<meta name="twitter:card" value="summary">

<!-- Open Graph data -->
<meta property="og:title" content="Title Here" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://www.example.com/" />
<meta property="og:image" content="http://example.com/image.jpg" />
<meta property="og:description" content="Description Here" />```
[more here](http://moz.com/blog/meta-data-templates-123)

**Comment by cassidyjames** [comment]
For the main description (some social networks and search engines): 
```
<meta name="description" content="A fast and open replacement for Windows and OS X. Pay what you want or download for free." /> 
```

Twitter:
```
<meta name="twitter:card" value="summary">
<meta name="twitter:title" value="elementary OS Freya">
<meta name="twitter:description" value="A fast and open replacement for Windows and OS X. Pay what you want or download for free.">

```

For Google+:
```
<meta itemprop="name" content="elementary OS Freya">
<meta itemprop="description" content="A fast and open replacement for Windows and OS X. Pay what you want or download for free.">
```

Since it requires more markup and isn't applicable right now, I'll open a new issue for once we have a large image (for richer social integration).

**Comment by cassidyjames** [comment]
@danrabbit wanna check over that copy and make any suggestions/edits? ^

**Comment by cassidyjames** [comment]
(basically most social networks will display it like this:

**elementary OS Freya**
A fast and open replacement for Windows and OS X. Pay what you want or download for free.

**Comment by cassidyjames** [comment]
Ah, Google+ and facebook both use OpenGraph. https://developers.google.com/+/web/snippet/
