### ISSUE TITLE
"Get Involved" header buttons overflow in other languages.

### ISSUE THREAD

**Issue by tengwar** [elementary/mvp#701]
![screenshot from 2015-06-18 18 46 35](https://cloud.githubusercontent.com/assets/7026772/8236714/7930df26-15ea-11e5-81e2-99f3b5f0817d.png)

Polish language, 1366x768 screen resolution. Varying size + wrapping look especially weird together.

**Comment by lewisgoddard** [comment]
I suppose we could work on having the heights all be the same at least, but I'm not sure we can stop overflow without wrapping text with hyphens, not something I think #ux will agree to.

**Comment by tengwar** [comment]
Maybe just make the translations shorter and not literal. E.g. instead of "Tworzenie strony internetowej" ("website creating", originally "web development") use "strona internetowa" ("website"). And instead of "Praca nad pulpitem" (which sounds ridiculous BTW) just use "System". (And maybe don't translate "Design".)

Generally in Polish the website has a lot of papercut bugs that make it look like a phishing site.

**Comment by btkostner** [comment]
This doesn't seem to be a problem after the redesign of get-involved. The buttons have been changed to single words and I have yet to find a language and resolution that causes the buttons to wrap to multiple lines.
