### ISSUE TITLE
start.elementary.io does not exist nor forwards to main page

### ISSUE THREAD

**Issue by embik** [elementary/mvp#704]
On a fresh install of elementary OS Freya unstable (`elementaryos-unstable-0.3.1-amd64.20150620.iso`), Midori has a default / starting page called `start.elementary.io`. This page does not exist and yields a DNS resolution error from CloudFare.

I'm not sure if that's happening on the stable version as well, but seems to be a bit of a user experience issue for new installations. If there is no special content planned for such a page, I'd suggest redirecting `start.elementary.io` to `elementary.io`.

**Comment by fabianthoma** [comment]
Should be resolved, start.elementary.io now points to the production server and will be redirected to our homepage.
