### ISSUE TITLE
Carousel layout is inconsistent at certain sizes

### ISSUE THREAD

**Issue by btkostner** [elementary/mvp#712]
between 1284px and 1350px the text on "Photos" and "Music" is under the image while "Videos" and "Midori" are on the side.

![photos](https://cloud.githubusercontent.com/assets/3385679/8348894/22d686ca-1acd-11e5-97e1-ee06ee71dfd3.png)
![videos](https://cloud.githubusercontent.com/assets/3385679/8348898/2a773e06-1acd-11e5-95cb-43d4a32b3417.png)

**Comment by hyptos** [comment]
Img's are of different size 

video : 854x543
midori : 755x622
photos : 914x620
music : 915x620

The right size is 915x620, we could either make the slider work for any imgs or get correct imgs size ?

Getting correct imgs size is way simpler to implement :)

Which one do you want ?

**Comment by btkostner** [comment]
We should go with same image sizes, but in the future, for code reusability sake,  it should be smart enough to fix this .  (my thoughts)

**Comment by lewisgoddard** [comment]
Fixed in #924
