### ISSUE TITLE
The 404 page doesn't load on non-english language errors, but the header is sent.

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#718]
The website should return good looking, helpful error messages when encountering 403s and 404s instead of nothing. Maybe include a DDG search field or similar pre-populated with elements from the URL.

E.g. when you click on [development guide](https://elementary.io/docs/code/the-basic-setup) which is linked [from here](https://elementary.io/ar/docs/code/reference), all you get is a blank page.

**Comment by lewisgoddard** [comment]
The 404 page is nice https://elementary.io/404
The 403 page is not https://elementary.io/_templates

**Comment by quassy** [comment]
Well [development guide](https://elementary.io/docs/code/the-basic-setup) returns 404 header but not the nice 404 page. So there is probably more to this issue.

**Comment by lewisgoddard** [comment]
I am going to split off the 403 page into a separate issue, and make this just about 404 pages not loading when not in English. I'll likely need @emersion's help on this one.
