### ISSUE TITLE
Back-end

### ISSUE THREAD

**Issue by KeitIG** [elementary/mvp#72]
So we have to choose a server-side language to fix issues below

As we said, Stripe got APIs for cURL, Ruby, Python, PHP, Java, Node and Go. We must choose one of these or a language supporting cURL. We were having a preference for Go.

- [ ] Cookies #68 
- [ ] Get file size #60 
- [ ] Page components #65 
- [ ] Download later (mails) #34 #24 
- [ ] Stripe support #6

**Comment by lewisgoddard** [comment]
I do not think Go is a good fit for this.

It's a relatively new language that many people don't know as well as they should and it isn't really geared towards web development. Like Python, I think it tries to do too much and ends up doing nothing great.

Meanwhile, practically anyone to ever build a website knows some PHP, and JavaScript. It is trivial to build a JavaScript function that hits a PHP API that puts data into an array, echoes it as JSON and returns that data back. This way we can 

### Cookies

PHP sets cookies with `setcookie`.

JavaScript can set cookies with `document.cookie`

jQuery also has a [jQuery.Cookie](https://github.com/carhartl/jquery-cookie) plugin.

### File Size

PHP
```
<?php
echo json_encode(array('size' => filesize($file)));
```

Fetch with JavaScript or jQuery, or load in the page.

### Page Components

Static HTML fetched dynamically with JavaScript.

### Download Later

JavaScript hits and API with the mail, with the protection I outlined in that issue. Our internal PHP hits the external Madrill API with our private key, and returns a JSON response of success or an error.

### Stripe Support.

Entirely JavaScript.

**Comment by cassidyjames** [comment]
For the filesize, I believe we're still planning to link to Sourceforge for the download. Perhaps they have an API to get the filesize? If not, I'm totally okay with it being manual as it's not going to change often at all.

**Comment by cassidyjames** [comment]
Closing as we've implemented basic PHP templating.
