### ISSUE TITLE
The Carousel behaves strangely in Safari while the page is loading.

### ISSUE THREAD

**Issue by nunomaduro** [elementary/mvp#722]
Hey folks,

I'm experiencing the following issue on OSX in Safari:
![elementary](https://cloud.githubusercontent.com/assets/5457236/8393746/c7c15602-1d15-11e5-893b-c8383468659e.png)

**Comment by snwh** [comment]
I cannot confirm with OSX + Safari. Which version of OS X/Safari are you using?

**Comment by nunomaduro** [comment]
Perhaps it related to the fact that I have done a quick scrool down when the page was loading.

OS X: Yosemite
Safari: 8.0.6

**Comment by snwh** [comment]
So it's no longer an issue?

**Comment by nunomaduro** [comment]
Of course is a issue. Is a normal behavior a user make try to scroll a page when a page is on load.

**Comment by aleksandar-todorovic** [comment]
@nunomaduro Is this happening once you let the page load and then scroll the page? I'm curious.

**Comment by nunomaduro** [comment]
@aleksandar-todorovic No. Is while the page loads. Perhaps is JS related.

**Comment by lewisgoddard** [comment]
To emulate, maybe try turning JS off. That will make it like it hasn't executed yet, and should get the same results.

**Comment by nunomaduro** [comment]
Sorry for the late response but i didn't have much time lately.

So, i used the inspect element tool and i was able to verify that the following line don't have the properly height:

Safari ( don't work correctly ) :

<div id="carousel" class="slide-container slide-fixed-height light" style="min-height: 457px;">

Chrome ( works correcty ):

<div id="carousel" class="slide-container slide-fixed-height light" style="min-height: 1055px;">

Good luck.

**Comment by lewisgoddard** [comment]
The latest version of Safari is only available on OS X, so I can't test this at all.

**Comment by Lukewh** [comment]
I can't reproduce this on El Capitan, Safari version: Version 9.0 (11601.1.56)

There is a small height issue but the carousel content is masked on first load, growing to the correct height when ready. The menu position and animation is unaffected.

Tested with and without Apples Network Link Conditioner in the 'Very Bad Network' profile.

Would be good to get a second opinion especially from someone using Yosemite.

**Comment by nunomaduro** [comment]
I think this issue no longer exist. At least didn't happen again after 20 tries.
