### ISSUE TITLE
HIG Switch screenshot outdated

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#728]
Needs to be updated to the new ones

**Comment by lewisgoddard** [comment]
###References
https://elementary.io/docs/human-interface-guidelines#checkboxes-switches
https://elementary.io/images/docs/human-interface-guidelines/checkboxes-switches/switches.png

**Comment by lewisgoddard** [comment]
Is this acceptable? Maybe round off the corners? I feel like showing them in an actual app is better, plus I don't know how to get them on a white or transparent background.

![screenshot from 2015-07-31 00 10 24](https://cloud.githubusercontent.com/assets/831389/8997379/9b8422d2-3718-11e5-883e-269e8138a811.png)

**Comment by cassidyjames** [comment]
I'd prefer either a faded-edges shot like some of the others or just an on-white or on-transparent shot of the switches like on the current site. I just made this guy and will PR. :)
![switches](https://cloud.githubusercontent.com/assets/611168/9011274/728d4f2e-3769-11e5-88bf-3f4bd50396d1.png)
