### ISSUE TITLE
Add screenshot to social meta tags

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#73]
Once both #70 and #23 are implemented, we can add a screenshot to the meta tags for richer social integration.

For Google+, we just add:
```
 <meta itemprop="image" content="http://our.image.url.here.jpg"> 
```

For Twitter, we replace `summary` with `summary_large_image` to get:
```
<meta name="twitter:card" content="summary_large_image">
```

...and then add:
```
<meta name="twitter:image:src" content="http://our.image.url.here.jpg">
```

**Comment by KeitIG** [comment]
What kind of pic should it be ? A live screenshot or we can just imagine the elementary logo ?
