### ISSUE TITLE
Set up permalinks with redirects for app help links [$25]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#730]
After some discussion it sounds like we want to set up some kind of permalinks (like "elementary.io/support/noise") that desktop apps can point to so we don't have to issue a package update if the help URL changes.

The problem here is that many of these apps still point to old answers. The current place to get app help is Launchpad answers. But we think the future place to get help is specific tags on StackExchange.

This is the issue in LP https://bugs.launchpad.net/scratch/+bug/1456733

--
[Bounty on Bountysource](https://www.bountysource.com/issues/23978816-set-up-permalinks-with-redirects-for-app-help-links)

**Comment by lewisgoddard** [comment]
Currently, redirects are written in Nginx, but since these are simple matches they can be done in PHP without any issue, and updates will happen the second they merge, rather than  when Fabian updates the config.

**Comment by lewisgoddard** [comment]
Because we were getting so many 404s on `/support/*`, they're currently redirected to `/support`. (FYI we used to have `/support/answers`) Would we be okay with something like `/get-support/noise`, or `/get-help/noise` ?

**Comment by danrabbit** [comment]
Hm, maybe just /help/* then? Less characters :p

**Comment by lewisgoddard** [comment]
We could technically turn off the support redirect, or limit it down, but it's bad practice. I'll add some redirects tomorrow then.

**Comment by lewisgoddard** [comment]
- [ ] Audience
- [ ] Files
- [ ] Geary
- [ ] Maya
- [ ] Midori
- [ ] Noise
- [ ] Photos
- [x] Scratch
- [ ] Snap
- [ ] System Settings
- [ ] Videos
- [ ] Terminal

**Comment by sudopluto** [comment]
I would be happy to work on this, but I would need an example of what I would need to change.

**Comment by lewisgoddard** [comment]
If no-one ever writes these, I'm actually in favour of `/get-support/noise` etc.

**Comment by lewisgoddard** [comment]
@emersion Go get that bounty buddy!
