### ISSUE TITLE
docs/hig for icon size and alignment are incomplete

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#731]
Proper docs never are complete but this particular section has been bugging me for some time: The [size and alignment section](https://elementary.io/docs/human-interface-guidelines#size-and-alignment) of icon guidelines only mentions some sizes for 48px icons. It'd be most helpful to at least have the positioning, icon sizes, border radii and shadow sizes for the three most common shapes square, circle and document (vertical rectangle, e.g. mime types) in all 6 official sizes.

**Comment by quassy** [comment]
The common sizes for "circle and document" are still missing.

**Comment by lewisgoddard** [comment]
All the sizes fall under rectangle, it mentions how to use those same dimensions for other elements.
