### ISSUE TITLE
Geary support link points to Ubuntu package

### ISSUE THREAD

**Issue by embik** [elementary/mvp#732]
As [this question on Launchpad](https://answers.launchpad.net/elementaryos/+question/269074) points out, the Geary link on [elementary.io/en/support](https://elementary.io/en/support) forwards users to the [Ubuntu package questions](https://answers.launchpad.net/ubuntu/+source/geary). The Ubuntu community won't support these questions though (for good reason, we're a different distro after all), so we either need to pull this link (for now) or find a better link for Geary support (shame we don't have support forums :stuck_out_tongue: )

**Comment by danrabbit** [comment]
As stackexchange is currently still private, we'll probably just need to pull this link for now since there isn't a geary-specific link for support other than Launchpad Answers

**Comment by danrabbit** [comment]
StackExchange is now in public beta. We could change the links to there now? http://elementaryos.stackexchange.com/questions/tagged/geary
