### ISSUE TITLE
Port HIG over

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#75]
This'll be a big undertaking. We should port the Human Interface Guidelines (http://elementary.io/docs/human-interface-guidelines) over to the new site.

We should also discuss how adding to/editing the HIG works. I'm all for using GitHub like everything else, but it might make the workflow easier if we generate the links to the pages more dynamically based on the file/folder structure.

**Comment by cassidyjames** [comment]
@danrabbit and I have talked about using Mkdocs for documentation, which would include the HIG.

**Comment by lewisgoddard** [comment]
Pull request #476 is a work-in-progress for this.

**Comment by seanballais** [comment]
@lewisgoddard May I help with the porting? :)

**Comment by seanballais** [comment]
@lewisgoddard I'll be branching from your pull request to help you with porting the docs.

**Comment by seanballais** [comment]
As is #571 also. Just did that pull request to help with the porting efforts. Ported 5 so far in the aforementioned pull request.

**Comment by lewisgoddard** [comment]
Done!
