### ISSUE TITLE
Expiration not Specified for JSON

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/mvp#756]
http://elementary.io/data/slingshot.json (expiration not specified)

**Comment by ddxor** [comment]
Hey @lewisgoddard 

Can you please provide a brief explanation as to why this change is necessary? I can see your linked issue, but that also doesn't provide any information as to why this is a problem.

**Comment by lewisgoddard** [comment]
Not caching the JSON means it's being reloaded for every homepage view, totally unnecessarily.
