### ISSUE TITLE
get-involved page is broken?

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/mvp#757]
This is what I see right now on chrome v44.0.2403.89 (64-bit):

![captura de pantalla de 2015-07-24 19 42 04](https://cloud.githubusercontent.com/assets/6054951/8886150/9910a95c-323c-11e5-962b-faf2677e443e.png)

**Comment by aleksandar-todorovic** [comment]
Just tried it with the latest Firefox and Chrome and it works fine for me.

Can you try to open it with addons disabled?

**Comment by Gabriel-p** [comment]
Just tried, still seeing it the same way. This is the link I visit BTW: https://elementary.io/es/get-involved

Also tried with Midori which gave mixed results. If I use the 'https' link I get:

>Midori can't find the page you're looking for

>The page located at “elementary.io” cannot be found. Check the web address for misspelled words and try again.
SSL handshake failed

If I use 'http' I can apparently see the page with no issues (assuming this is what it should show):

![captura de pantalla de 2015-07-24 20 07 57](https://cloud.githubusercontent.com/assets/6054951/8886390/b2739a46-323f-11e5-91fe-aa417d589920.png)

**Comment by lewisgoddard** [comment]
This is fixed, we're just waiting for the CloudFlare cache to update.
