### ISSUE TITLE
Lowercase the first letter of the title of Bosnian, Croatian and Serbian language

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/mvp#772]
I understand all three of those languages and in every single one of them the grammatically correct way to reference to them is to lowercase their first letter.

It's grammatically correct to say:

* `bosanski` instead of `Bosanski` (Bosnian)
* `hrvatski (Hrvatska)` instead of `Hrvatski (Hrvatska)` (Croatian)
* `српски` instead of `Српски` and `српски (ијекавица)` instead of `Српски (Ијекавица)` (Serbian) (yup, the name of Ijekavian dialect should be lowercased too)

Of course, if they're in the beginning of the sentence, they should be capitalized, but here we're not using them as a part of a sentence.

This is already done to some languages (like Czech and Bulgarian), so we should do it in these three languages too.

Google Translate isn't really a viable source, but I'm going to use it as a reference to confirm this issue: [Croatian](https://translate.google.com/#en/hr/Croatian), [Bosnian](https://translate.google.com/#en/bs/Bosnian) and [Serbian](https://translate.google.com/#en/sr/Serbian).

**Comment by lewisgoddard** [comment]
For reference, these are set in [`/mvp/_templates/l10n.php`](https://github.com/elementary/mvp/blob/master/_templates/l10n.php)

**Comment by aleksandar-todorovic** [comment]
Thanks!

I was thinking of submitting a pull request instead of an issue, but I wasn't sure where to find them.
