### ISSUE TITLE
Redirecting to 404.php does not work on subdomains

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/mvp#789]
I tested this out on http://beta.elementary.io.

Basically, if you type http://beta.elementary.io/something-random you don't see that nice 404 page that you see when you type http://elementary.io/something-random.

Also, http://blog.elementary.io shows a 404 page that's inconsistent with http://elementary.io, but I'm not sure if Tumblr allows the customization of 404 pages. If so, then I think that this 404 page should definitely match the one set on http://elementary.io.

**Comment by hyptos** [comment]
Hello,

To add on what you said 

> that you see when you type http://elementary.io/something-random.

Well on the fr version of it, the http code is correct but there is nothing to display.

Looks like when there is the languages settings ie hostname/fr/something-random or hostname/en/something-random the 404 doesn't work. But if you go to hostname/something-random the 404 is working as intented.
