### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by felixinx** [elementary/mvp#791]
Hi,
When I go to [`https://elementary.io/thispagedosentexsists`](https://elementary.io/thispagedosentexsists) it return a `404`, but no page (blank page). Thanks!

**Comment by aleksandar-todorovic** [comment]
Works fine here.

What's your config?

**Comment by felixinx** [comment]
Hi,

On Chrome, Windows, it's return 404, Blank
On Midori, Elementary, it's return a 404. Check image.

It's look like a SSL issue.

**Comment by lewisgoddard** [comment]
Chrome on Windows, works fine for me.

**Comment by aleksandar-todorovic** [comment]
Midori has a known issue with displaying elementary.io's SSL certificate which is the reason why elementary.io does not enforce https by default currently. It should work with the http protocol if I'm not mistaken.

As for the Chrome, I don't have access to Windows right now, and I can't seem to replicate this on Linux. Maybe this has something to do with some add-on you have activated?

**Comment by gamerlv** [comment]
Is your browser / system language something other than English? If so this is probably related to #718

**Comment by felixinx** [comment]
Yes, I think that is related, but I can view the [404 page](https://elementary.io/fr/404) in french.
