### ISSUE TITLE
Payment description is not translated

### ISSUE THREAD

**Issue by desiderantes** [elementary/mvp#805]
On the payment dialog, there's a description, "elementary OS download", that should be translated if possible. Pic related, spanish site showing the english text.

![captura de pantalla de 2015-08-21 16 01 51](https://cloud.githubusercontent.com/assets/1703429/9419049/fd463b7a-481d-11e5-847b-4b1ffbd27bfa.png)

**Comment by lewisgoddard** [comment]
I see why this is happening, we're setting that ourselves in JavaScript which is never translated.

**Comment by lewisgoddard** [comment]
This is no longer valid, as it is now "Freya 0.3.2", and release names should not be translated.
