### ISSUE TITLE
update video icon

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#810]
We released icons so we need to update to the new videos icon

**Comment by btkostner** [comment]
Seems to already be current on the homepage and support page. Only place that needs to be updated is in screenshots.

`/images/responsive-images/`
`/images/notebook.png`
`/images/docs/human-interface-guidelines/icons/icons.png`

**Comment by gitzain** [comment]
Do we have a PSD for the images? I can take the screenshots and update the PSD.

**Comment by cassidyjames** [comment]
Also `/images/docs/learning-the-basics/dock.png`

**Comment by cassidyjames** [comment]
@gitzain these aren't Photoshop files (we don't use Photoshop at all :smile:), they're just screenshots from an actual OS install.

**Comment by gitzain** [comment]
I get how the screen on the laptop is done but what about the laptop visual?

**Comment by divayprakash** [comment]
I'm willing to work on this just need the green flag.
@btkostner @danrabbit @cassidyjames

**Comment by btkostner** [comment]
As far as I know nobody else is working on it, so go for it :+1:

**Comment by btkostner** [comment]
Here is the [laptop.svg](https://drive.google.com/a/elementaryos.org/file/d/0B9VgWPss_ZgHcm9NMzlVSFVqZGs/view?usp=sharing).

**Comment by divayprakash** [comment]
@btkostner Can't access the `laptop.svg`, Google Drive denies access.

**Comment by btkostner** [comment]
@divayprakash sorry about that, you should be all good now.

**Comment by divayprakash** [comment]
In progress
