### ISSUE TITLE
Add a CSS linter to branch checks

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#811]
I recently noticed we had some small issues in our CSS. We should add a linter to our branch checks, at least for some common things like making sure "0" has no units, no empty rules, syntax is correct for properties (had an extra comma in an RGBA), etc.

**Comment by btkostner** [comment]
Right now (as far as I can tell) there is no build step for the website. The way I see it we could,
1) Add a build step to lint the css
2) Plug the linter to run on each page request when in a development environment. (overtaxing?)
3) Robot?

**Comment by fabianthoma** [comment]
@danrabbit could you provide me with a css linter and the configuration to go with it? Then we can run that in jenkins as part of the branch deployment

**Comment by btkostner** [comment]
recently added
