### ISSUE TITLE
Split strings are not localizable

### ISSUE THREAD

**Issue by fitojb** [elementary/mvp#815]
Just see.

![screenshot from 2015-08-23 22-20-28](https://cloud.githubusercontent.com/assets/554953/9432238/4a242d1c-49e5-11e5-95ae-b53ec8f51cbf.png)

There is no way you can create a Spanish translation (nor in any other language besides German, maybe) that makes sense.

**Comment by danrabbit** [comment]
In the future, please try to file with a more descriptive title.

I don't think this string makes a whole ton of sense in English either.

**Comment by fitojb** [comment]
@danrabbit: Yeah, I should try, because you miss the point. The string is broken into two in the Transifex UI.

**Comment by lewisgoddard** [comment]
This string is "broken" (I would have said fragmented) because the second part is a link. Since Transifex has no way of remembering what parts are links it much by taken as two or more separate strings. One for the first part of the sentence, the second for the link, and a third for the end. Assuming Transifex is working properly, you should be able to carry on reading down the set of strings naturally.

As such, I think this is the intended behaviour.

**Comment by fitojb** [comment]
@lewisgoddard If it was "intended behavior" I wouldn't have bothered to file a bug report. [It is A MISTAKE to break (or "fragment", if you want to be picky) strings in multiple parts](http://rimas.kudelis.lt/2010/06/14/software-that-is-actually-localizable/). Period.

**Comment by btkostner** [comment]
According to the Transifex [documentation](http://docs.transifex.com/live/webmasters/#translating-links), the `a` element should be part of the segment. As a workaround we could also add `tx-content="block"` to the `h4` element, this should force everything in that element to be a single segment, we would just have to work around the html `a` element in the segment.

**Comment by lewisgoddard** [comment]
So we should be submitting the full HTML to Transifex, so that translators can decide where to position the link?

Instead of:
```
All apparel is in US sizes. Tees run a bit snug; for sizing details, see American Apparel’s
```
&
```
sizing chart.
```

It would be:
```
All apparel is in US sizes. Tees run a bit snug; for sizing details, see American Apparel’s <a href="http://www.americanapparel.net/sizing/default.asp?chart=mu.shirts" target="_blank">sizing chart</a>.
```

**Comment by danrabbit** [comment]
Ah sorry, I misunderstood the nature of the issue. Indeed it's important to be as explicit as possible when filing a report. Sometimes a screenshot is not as clear as it may seem to be.

I agree that showing translators HTML is not ideal, but I think the only way to get around that would be to structure it so the link is not part of the sentence. We could do something like:

"See American Apparel for sizing details:" "sizing chart"

**Comment by aleksandar-todorovic** [comment]
One important point to make:

If HTML code is a part of the translation, is there anything stopping someone random from redirecting inner links to some third-party site of his choice? If that ever happens, I'm not sure how will Transifex handle it. If it fails to stop something like this, it would take quite a while before somebody spots this abuse, reports it, it gets fixed and finally the code is pulled from Transifex one more time. It could literally take months to fix something as simple as changing the URL while translating a string with HTML code attached.

**Comment by lewisgoddard** [comment]
Yeah, we can't be submitting URLs in with translations, because that would invalidate the entire string, plus translators could redirect stuff they shouldn't be. Just dropping a `>` or a `"` would totally ruin the site from there down.

**Comment by aleksandar-todorovic** [comment]
@lewisgoddard But wait, isn't this already happening in _a lot_ of places? Here's just one example that proves this:

![screenshot from 2015-08-28 00 34 16](https://cloud.githubusercontent.com/assets/4890548/9534900/9874596c-4d1c-11e5-8c08-8752e5a06d5e.png)

I'm pretty sure I saw dozens of these strings that contain HTML code in them.

**Comment by lewisgoddard** [comment]
I wasn't aware of any of the translations containing HTML. I suppose we ultimately need to either separate links out into individual buttons (a pain, and not the best design), or trust translators not to meddle with links, which we are apparently unwittingly doing already.

**Comment by fitojb** [comment]
> or trust translators not to meddle with links
@lewisgoddard Transifex contains checks to ensure links are identical, each project needs to enable those. Besides, why wouldn't you trust your translators? That seems insulting.

**Comment by aleksandar-todorovic** [comment]
@fitojb I'm a translator myself, so I kind of understand why you're saying that this could be considered to be insulting, but think of it this way:

I'm translating to Bosnian, you're translating to Spanish. If there's a third person interested in translating the website to Dutch (I'm just using Dutch as an example), we have no understanding of what's happening in the Dutch translation team. A person of interest might join that third team and change the HTML code without me, you, Lewis nor Daniel knowing it. As I stated in my previous comment, it could possibly take months before that error gets noticed and fixed and the person of interest could benefit from that error by redirecting link to his own possibly malicious website.

If, like you said, there's a Transifex option that could make sure that this isn't going to happen, I'm all for turning it on and making sure that HTML code stays as it is supposed to be.

**Comment by lewisgoddard** [comment]
@fitojb Exactly as @aleksandar-todorovic said, changing this HTML code could potentially create security flaws on pages where people are entering their payment details. Blindly allowing people who often have little to no review to modify that is not acceptable.

To be clear, very few people can push to this repository themselves, and even those that can (like me and @danrabbit) do so via pull requests that are reviewed by at least 1 other individual.

It isn't that we don't trust translators, it's that we don't trust anyone, not any lone individual anyway.

**Comment by lewisgoddard** [comment]
> Transifex contains checks to ensure links are identical, each project needs to enable those.

I have only recently been given access to the administration side of Transifex, and have little experience with it. Where would I find such settings?

**Comment by lewisgoddard** [comment]
Is this fixed now? I think I changed something in a merge and forgot to mention this bug.
https://github.com/elementary/mvp/blob/master/lang/en/store.json
It sure looks fixed.
