### ISSUE TITLE
Avatar image on blog needs a mini positioning fix

### ISSUE THREAD

**Issue by rgbskills** [elementary/mvp#819]
.note-item .avatar img {
    border-radius: 2px;
    width: 40px;
    height: 40px;
    margin: 0; (fix)
}

**Comment by btkostner** [comment]
Can confirm.
Before:
![before](https://cloud.githubusercontent.com/assets/3385679/9533564/b73343cc-4cc7-11e5-9a53-36d5a287bfb9.png)
After:
![after](https://cloud.githubusercontent.com/assets/3385679/9533569/bceedf6a-4cc7-11e5-954f-eec1c21a639b.png)

**Comment by anatooly** [comment]
blog.elementary.io base on Tumblr service not on this repo.

**Comment by lewisgoddard** [comment]
True, but there isn't a better place to file this at the moment. I'm going to ping @cassidyjames and @danrabbit because I don't have access right now.

**Comment by cassidyjames** [comment]
All set
