### ISSUE TITLE
Typos in the German version of the landing page

### ISSUE THREAD

**Issue by Novanoid** [elementary/mvp#820]
* Music tab in the carousel: "blitz-schnell" should be "blitzschnell"
* Midori tab in the carousel: "läd" should be "lädt"
* Column about advertisement at the very bottom of the page: "Werbe-deals" should be "Werbedeals", "[...]wir sammeln keine sensible und persönliche Daten ein." should be "[..]wir sammeln keine sensiblen und persönlichen Daten ein". In fact, the whole column would sound much better in my opinion by rephrasing it to "Wir machen keine Werbedeals und sammeln keine sensiblen und persönlichen Daten. Unser Einkommen stammt direkt von unseren Nutzern."
* Column about safety at the very bottom of the page: A comma is missing after "Software" and it should be "das" U.S. Department of Defense, but again the whole sentence sounds strange in my opinion. Much better would be: "Wir setzen auf Linux: Dieselbe Software, mit der unter anderem das U.S. Department of Defense und die Bank of China betrieben werden."

**Comment by Novanoid** [comment]
I just noticed that the translation is available on Transifex and most of the issues mentioned above have already been fixed there. The only thing left was part of the second bullet point which I just corrected there.

**Comment by danrabbit** [comment]
Closing this report, since as you said translations are done through Transifex :)
