### ISSUE TITLE
Update Midori screenshot

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#831]
Midori 0.5.11 with headerbar is out

**Comment by aleksandar-todorovic** [comment]
So, something like this with a bit of cropping I presume? 

![screenshot from 2015-08-30 18 56 20](https://cloud.githubusercontent.com/assets/4890548/9568421/dcc71496-4f48-11e5-9e6f-fb641fe7e5cc.png)

**Comment by danrabbit** [comment]
Sorry I went ahead and grabbed one. I usually use lp:screenshot-tool since it takes app screenshots without the background
