### ISSUE TITLE
Files app crashing

### ISSUE THREAD

**Issue by yuriivan** [elementary/mvp#832]
Files app is crashing when you are transfering data (copying or moving files) and you try to open another app, such as Software Updater or Software center. Sometimes it crashed on opening another window of Files app.

It does not give you an error message. It just disappears from the screen and stops the data transfering process.

I'm using eOS Freya. My system is and was updated at the moment of those crashes. Kernel 3.16.0-46 running x64 on an AMD machine. 

My linux runs in an ext4 partition on a ssd and I was copying data from a ntfs partition to a ext4 one. It also crashed while I was copying from a ntfs to another ntfs partition.

I don't do dual boot. I just use elementary. All those copies that crashed were made on spinning drivers that were mounted as part of /media/(user)/(drive label) tree automatically by Files app.

**Comment by lewisgoddard** [comment]
Unfortunately, this is not the place to file bugs with files. That can currently be done at https://bugs.launchpad.net/pantheon-files/+filebug

I am curious as to where linked to here in such a way as to cause this confusing?

**Comment by yuriivan** [comment]
Sorry. It was the first hint in "get envolved" page. I confess i didnt read
