### ISSUE TITLE
/docs/code doesn't redirect like it should

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/mvp#838]
There is an `index.php` in `/docs/code` that is supposed to initiate a redirect, but it isn't for some reason. I think we need to change `nginx.conf` to have:

```
location /docs/ {
        try_files $uri $uri/ /docs/_mdr/index.php?$args;
}
```

**Comment by gamerlv** [comment]
Nginx config files has been updated. The index.php files now properly redirects users to the correct page.

**Comment by lewisgoddard** [comment]
@gamerlv Are those changes reflected in the `nginx.conf` in this repository?
