### ISSUE TITLE
I can't boot into my system after a fresh install for 0.3.1 in UEFI mode.

### ISSUE THREAD

**Issue by laichiaheng** [elementary/mvp#842]
There were no such problem in 0.3, why does it become this way??

http://i.imgur.com/EOfgLzV.jpg

So I am forced to give up UEFI mode, and go back to Legacy mode now.....

Please fix this....

My bug report: https://bugs.launchpad.net/elementaryos/+bug/1492256

**Comment by aleksandar-todorovic** [comment]
Why the hell did you create an issue if you have already submitted a bug report on Launchpad? This repository is only for the website-related issues.

**Comment by lewisgoddard** [comment]
As @aleksandar-todorovic unpolitely put it, this issue tracker is only for problems with the actual elementary.io website, _not_ the operating system itself. Usually I would tell you to file a bug, but as you already have there's not much else to do.
