### ISSUE TITLE
"Learn more" in Midori description(Meet our apps section) is badly visible

### ISSUE THREAD

**Issue by Liberus** [elementary/mvp#846]
See screenshot, Windows 10, Chrome Version 45.0.2454.85 m
![learn_more](https://cloud.githubusercontent.com/assets/919198/9771862/6fec705e-5741-11e5-8f2f-8db43f637b75.png)

**Comment by lewisgoddard** [comment]
Confirmed, we're too reliant on it being above the mountain line.

![screenshot from 2015-09-09 20 28 28](https://cloud.githubusercontent.com/assets/831389/9771979/6009b4b8-5731-11e5-83cd-99bd4ef56e12.png)

**Comment by danrabbit** [comment]
This is definitely a problem with the responsiveness of the page. There shouldn't be a case where the layout reflows like that and we aren't changing over to the gradient background
