### ISSUE TITLE
Chrome: Holding middle mouse button on home page allows horizontal scrolling

### ISSUE THREAD

**Issue by mplesec** [elementary/mvp#847]
Pressing and holding the middle mouse button anywhere on the gives the ability to scroll horizontally, issue exists in Chrome, maybe some other browsers (not in latest FF and Edge though).

Issue exists because `#carousel` should have `position: relative;` on it as well. The `overflow` property needs to be kept on `#carousel`, however it can be removed on the `body` element.

Chrome version: Version 45.0.2454.85 m

**Comment by lewisgoddard** [comment]
The `position: relative;` on `#carousel` seems to work, but I'm not sure I understand why.

**Comment by mplesec** [comment]
It seems it's just a bug.
http://wiki.orbeon.com/forms/doc/contributor-guide/browser#TOC-Absolutely-positioned-box-inside-a-box-with-overflow:-auto-or-hidden
