### ISSUE TITLE
Midori's default home page is not obviously the internet

### ISSUE THREAD

**Issue by codygarver** [elementary/mvp#853]
According to old launchpad bug Midori should have an official custom homepage

https://bugs.launchpad.net/elementaryos/+bug/1105819

**Comment by cassidyjames** [comment]
To echo my comment on Launchpad, the default homepage in the OS is `start.elementary.io`, so this page would need to be served up there.

**Comment by cassidyjames** [comment]
Also, like the capnet-assist page, I believe this page should not include tracking of any sort.

**Comment by lewisgoddard** [comment]
I suppose I need to ask the design group what we need here, just a placeholder for now? Or is it not worth it just to have an empty page?

**Comment by lewisgoddard** [comment]
@danrabbit Should we have a super simple "You're on the internet!" page like over at #814 ?

**Comment by danrabbit** [comment]
I'm going to close this for mvp. We should just set the homepage to Google or DuckDuckGo.
