### ISSUE TITLE
Custom Amount placeholder in Spanish website

### ISSUE THREAD

**Issue by kmorope** [elementary/mvp#854]
![image](https://cloud.githubusercontent.com/assets/3497950/9905743/5a583e98-5c4c-11e5-940a-e30c219521f5.png)

The width of these input has a fixed size and hides the placeholder in spanish site

**Comment by lewisgoddard** [comment]
I swear this was solved previously, so I'll assume this is a regression.
_Fluid width doesn't fit to placeholders, so it isn't an option._
```
.pre-amount {
    color: #333;
    margin-left: 16px;
    margin-right: -16px;
    margin-top: 11px;
    position: absolute;
    pointer-events: none;
    font-size: 14px;
}
```
```
#amount-custom {
    padding-left: 24px;
    padding-right: 16px;
}
```
