### ISSUE TITLE
get-involved page is not translated anymore

### ISSUE THREAD

**Issue by ProsjektX** [elementary/mvp#863]
Seems like this page is not translated anymore since some time, in any language.

**Comment by lewisgoddard** [comment]
@ProsjektX Can you copy and paste the URL you're visiting and maybe include a screenshot?

Translations appear to work fine here, although the top title hasn't been done yet.

**Comment by lewisgoddard** [comment]
![image](https://cloud.githubusercontent.com/assets/831389/9962228/8fff60d6-5e1c-11e5-9e9f-f0e54b8342e3.png)

**Comment by ProsjektX** [comment]
I see now that "es" is one that seems to work on my side as well, but not e.g. "nb
![capture](https://cloud.githubusercontent.com/assets/6444014/9963826/83a0fe6a-5e2d-11e5-9939-c7c451a8b27d.PNG)
", "de", "it", "fr", .... although they are fully translated on mvp.

**Comment by lewisgoddard** [comment]
I assume that this is because they hadn't matched up the last time that translations were pulled in, this should be fixed with a fresh pull.
