### ISSUE TITLE
Add "remove mouse acceleration" button and make mouse settings more adjustable.

### ISSUE THREAD

**Issue by Jarppi01** [elementary/mvp#867]
Removing  mouse acceleration is necessary for gaming and for desktop usage, i think. So please add remove mouse acceleration button that removes mouse acceleration competitively. Also make Cursor speed adjustment slider better, i think that even lowest option is too fast. make it textbox input.

**Comment by fabianthoma** [comment]
This project is about elementary's website, please report bugs about the Operating System on our [launchpad page](https://bugs.launchpad.net/elementary/+filebug) and follow the bug [reporting guide](https://elementary.io/docs/code/reference#reporting-bugs)
