### ISSUE TITLE
Create a warrant canary

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#874]
Was asked somewhere else

For reference: https://www.eff.org/deeplinks/2014/04/warrant-canary-faq

**Comment by cassidyjames** [comment]
Tumblr's:

> As of the date of publication of this report, we have never received a National Security Letter, FISA order, or any other classified request for user information.

I like that, combined with something about no backdoors, perhaps on the Privacy page? i.e.:

> ### Transparency
> We have not placed any backdoors into our software and have not received any requests for doing so. We have also never received a National Security Letter, FISA order, or any other classified request for user information.
