### ISSUE TITLE
Installation instructions page badly formatted

### ISSUE THREAD

**Issue by XtrmJosh** [elementary/mvp#875]
https://elementary.io/docs/installation#install-on-ubuntu

The installation instructions all appear at the same time for me, making it difficult if not impossible to read any specific instructions as per: http://i.imgur.com/rDDQuI3.png

Running Chromium on Ubuntu w/KDE frontend.

**Comment by lewisgoddard** [comment]
What's your Chromium Version? Would you be able to try that again without the addons, Incognito mode should do it.`chromium --disable-extensions` would also work if that doesn't.

**Comment by thiagoabreu** [comment]
Using Google Chrome + ElementaryOS Freya here. Having the same problem.

Incognito mode made it work fine but `--disable-extensions` did nothing.

**Comment by btkostner** [comment]
try pressing f12, then right clicking the refresh button and clicking "Empty Cache and Hard Reload"

**Comment by XtrmJosh** [comment]
Have tried it without extensions and it works fine, looks to be an interaction with AdBlock - disabling just that makes it work. Kinda popular extension though... Chromium version 45.0.2454.101 here too.

**Comment by thiagoabreu** [comment]
@btkostner that worked for me

**Comment by lewisgoddard** [comment]
Mine works fine with AdBlock and default settings. Could you try again, we've cleared a cache again?

**Comment by lewisgoddard** [comment]
Adblock doesn't upset this on default settings, so I'm going to close. We can't purposefully circumvent the  restrictions people place within there browser.
