### ISSUE TITLE
Need to improve usability of OS download process

### ISSUE THREAD

**Issue by pepeevich** [elementary/mvp#877]
It is a standard case that user firstly download OS image, then he is going to see installation tutorial.

It will be good to take out the installation tutorial link from the installation popup. It can be placed before or after the download button.

**Comment by harveycabaguio** [comment]
Maybe we should just redirect to the installation tutorial? And modify the tutorial page to show context, like a nice banner that says, "while downloading the iso, read the instructions on how to install it below"?

**Comment by btkostner** [comment]
Why not just redirect to the support page?

**Comment by pepeevich** [comment]
IMHO, redirect is not the best way, because some users isn't need in the tutotial (for example they already know how to install the OS). Redirect can irritate  such people.

**Comment by lewisgoddard** [comment]
Since we already link to the installation page in the modal, the only change I would recommend is not closing the modal automatically on download.

**Comment by danrabbit** [comment]
I agree about redirecting to the installation page. I don't think having a dialog that doesn't close when you take action is good.

**Comment by lewisgoddard** [comment]
Is it worth having the link there then?

**Comment by danrabbit** [comment]
If we automatically redirect no, we should remove the link

**Comment by danrabbit** [comment]
Removing "needs design" since we have a design direction:
- [ ] Automatically redirect to installation page
- [ ] Remove installation link from the dialog

**Comment by lewisgoddard** [comment]
I'm not so sure redirecting after download is a good idea, nearly 25% of people click a download twice. Happens more on magnet that http, testing the link maybe? What if I copy the link into a program like transmission, or an email, I can't get to the installation page.

Ultimately, you're not going to want install instructions unless you're downloading, or you're straight up gonna google "[elementary os how to install](https://www.google.co.uk/search?q=elementary+os+how+to+install&oq=elementary+os+how+to+install)".
