### ISSUE TITLE
images in HIG section "iconography" should render on github

### ISSUE THREAD

**Issue by waldyrious** [elementary/mvp#890]
Link: https://github.com/elementary/mvp/blob/master/docs/human-interface-guidelines.md#iconography-iconography

Those images appear broken on github because they were implemented using custom html rather than markdown as is the case with the other images. The reason for this is that they are multiple images that need to be on a single line, when the current css [puts each image on its own line and centers it](https://github.com/elementary/mvp/blob/adefce090d6b1be960005228babd9495e7d3fd09/styles/main.css#L1046-L1049). It should be possible to produce the same effect (multiple images on the same line) using css rather than custom html, and that would make the docs work in markdown format too (the grid may need to be integrated into the png files for the images where they are combined).

/cc @snwh

**Comment by lewisgoddard** [comment]
I'm not entirely sure that's the reason, I think it's because they are SVGs which GitHub delivers as text.

**Comment by waldyrious** [comment]
Ah, good point. In that case, and considering that the other images are PNGs, wouldn't it make sense to convert these as well?

**Comment by lewisgoddard** [comment]
I think if we want real sizes and renders, then PNGs are the way to go. Things that would be SVG in the real world are probably better off left as they are.

**Comment by danrabbit** [comment]
I think they should stay as SVGs to facilitate HiDPI as well. And if any of the icons change, they can be easily updated
