### ISSUE TITLE
Polish national characters missing from the font on website

### ISSUE THREAD

**Issue by michallepicki** [elementary/mvp#899]
Since the website is already available in [polish](http://elementary.io/pl/) I would consider it a bug. Screenshot [here](http://i.imgur.com/r1PjweH.jpg)
Polish characters include: ó ł ć ę ś ą ź ż ń

**Comment by btkostner** [comment]
We are aware of the bug and are working on solutions for it. You can track the status on bug #411.

**Comment by michallepicki** [comment]
Sorry for that, hopefully next reporters will find out it's a duplicate when searching for "polish + font" like me ;)

**Comment by tengwar** [comment]
This is fixed for Raleway, but not for Open Sans. On #411 it says to report these kind of issues separately now.
