### ISSUE TITLE
32-bit uefi support

### ISSUE THREAD

**Issue by idiotzoo** [elementary/mvp#909]
Intel Baytrail Atom systems only support 32-bit uefi despite having a 64-bit CPU. Elementary OS would be a great fit for these low powered systems but currently the 32-bit version doesn't support uefi and the 64-bit version can't be booted with a 32-bit uefi.

**Comment by aleksandar-todorovic** [comment]
This is a repository for the [elementary.io](https://elementary.io). Try submitting your request over [at Launchpad](https://launchpad.net/elementary).

**Comment by KeitIG** [comment]
As @aleksandar-todorovic said, only the issues related to the official website are accepted here.
