### ISSUE TITLE
Grid layout

### ISSUE THREAD

**Issue by rbrs** [elementary/mvp#91]
If you're going mobile first, why not using premade css grid? There are number of options, like [Bootstrap](http://getbootstrap.com/), [Foundation](http://foundation.zurb.com/) or [Skeleton](http://getskeleton.com/) (if more lightweight). Not only it would save some time, but also fix some cross-browser issues.

**Comment by KeitIG** [comment]
We don't want to use third-party libraries except if it is really needed. We probably will create our own grid system.

For cross-browsers issues, I was thinking about normalize.css, but we will see later about that.

**Comment by rbrs** [comment]
Well, in that case you could pick a library and take out things you don't need. Making everything on your own will be just reinventing bicycle.

Of course, the choice is yours, just my two cents ;)

**Comment by KeitIG** [comment]
I let the issue open, we will need a grid sooner or later.

**Comment by danrabbit** [comment]
I'm going to close this issue so we don't just have a bunch of issues open clogging the tracker.

If the time comes where we need a more complex grid system, we'll add one. But at the moment, we don't have a need for one.
