### ISSUE TITLE
User Guide is stupid hard to get to

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#912]
I couldn't find a sane link to the user guide, which is a huge asset. We should probably link to it on the Support page.

I did just find it linked to at the end of the Installation doc, but an item on the Support page itself would probably be good as well.

**Comment by danrabbit** [comment]
Yeah, we could do thirds on the front page and put it in

**Comment by lewisgoddard** [comment]
Dupe of #812?

**Comment by cassidyjames** [comment]
@lewisgoddard yup, it appears so
