### ISSUE TITLE
Explain the Burndown Chart

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#917]
A question I see often is what our development focus is. I think putting the burndown front and center is a great first step, but we still need to explain a bit. At the very least we need to actually link to the miltestone that it mentions

**Comment by cassidyjames** [comment]
How about some copy below, something like,

> This burndown chart shows our progress on the [Loki Alpha 1 milestone](#), which is our current priority. Soon after that milestone is reached, we plan to move to the Loki Alpha 2 milestone.

**Comment by lewisgoddard** [comment]
We have now moved the chart out of focus a little, and it has a (new?) header:

> "Our Progress for The Loki Beta 1 Milestone:"
