### ISSUE TITLE
Link to official elementary code style returns a blank page

### ISSUE THREAD

**Issue by Supermanco** [elementary/mvp#922]
I don't know if it's on purpose, if the document does not really exist or there's another kind of problem. But the following URL returns a blank document (in Chrome Versión 46.0.2490.86 m)

https://elementary.io/docs/code/code-style

**Comment by danrabbit** [comment]
The link should instead be https://elementary.io/docs/code/reference#code-style

is this from somewhere else on our website?

**Comment by Supermanco** [comment]
It's in the README.MD, which appears in the home of the repo.

**Comment by lewisgoddard** [comment]
All fixed.
