### ISSUE TITLE
Quotations are invisible

### ISSUE THREAD

**Issue by pantor** [elementary/mvp#925]
Using Safari 9.0.1 and El Capitan, some quotations on the website are broken:

![bildschirmfoto 2015-11-20 um 23 06 18](https://cloud.githubusercontent.com/assets/1885260/11313187/6ddc3434-8fdb-11e5-940d-e38b2b220f72.png)

![bildschirmfoto 2015-11-20 um 23 06 31](https://cloud.githubusercontent.com/assets/1885260/11313186/6a26f432-8fdb-11e5-8da6-cea8b73d8d68.png)

**Comment by lewisgoddard** [comment]
Does it block social buttons, like like buttons and tweet buttons?

**Comment by pantor** [comment]
In the footer, I can only see the StackExchange icon. Twitter, Reddit, Facebook and Google+ are invisible as well. Are there usually any other social buttons visible?

**Comment by aleksandar-todorovic** [comment]
@pantor Yup. Twitter, Reddit, StackExchange, Google+ and Facebook icons (in that order).

Judging by that, I'm fairly sure that something is blocking social features and blocking the quotes as well because they're actually pre-made tweets. Any privacy addons installed or something?

**Comment by pantor** [comment]
@aleksandar-todorovic You're right, a local add-on blocked all those links to social pages (though it should only block direct like and share buttons). However, not ideal for me, but the website is working fine.

**Comment by lewisgoddard** [comment]
The quotes _are_ share buttons, which is why I thought this was happening. They are "click to tweet" quotes.
