### ISSUE TITLE
Slingshot has a small glitch in dutch

### ISSUE THREAD

**Issue by jjeroennl** [elementary/mvp#927]
![](http://i.imgur.com/aWGaO4Z.png)

"System tools" is "Systeemgereedschap" in dutch which is longer then the maximum width.

**Comment by KeitIG** [comment]
Hello, this repo if for the website issues only, not the operating system. Please have a look at launchpad for reporting bugs.

**Comment by aleksandar-todorovic** [comment]
@KeitIG @lewisgoddard I thought that this is the Slingshot issue too, but then I changed the website language to Dutch and realized that this is the animation issue on the website.

This should be reopened.

**Comment by KeitIG** [comment]
My bad indeed. How is text handled in eOS ? text-overflow: ellipsis or by breaking lines ?

**Comment by lewisgoddard** [comment]
I have shortcuts with two lines of text.

**Comment by KeitIG** [comment]
Ok, I'm assigning myself
