### ISSUE TITLE
Mention No Spying, No Ads (with regards to the OS)

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#93]
This is obvious to us, but I think it sets us apart from other free-as-in-beer products. I think we should make mention of it in our marketing copy, especially since many other companies these days have a revenue model that is either ads or spying or both

**Comment by KeitIG** [comment]
+ showing a link to this repo, and saying the website is only and only based on it.

**Comment by lewisgoddard** [comment]
I think Dan meant the OS, not the website. Technically, the website does now have Google Analytics. A privacy policy would be good.

**Comment by cassidyjames** [comment]
Something along these lines?

> No Spying. No Ads.
> ==================
> 
> We don't make money by selling or aggregating data, we do it by selling software for whatever people are willing to pay. We never collect or use your data for advertisements.

**Comment by davidak** [comment]
Google Analytics is actual spying. Same for Mixpanel. you use this services for free by selling your users data to them.

It is not complicated to host Piwik yourself and for most things it works great. if you do, you can mention that too.

**Comment by aleksandar-todorovic** [comment]
I have to agree with @davidak. If we mention this, we should go all the way, which means that we should change from Google Analytics to Piwik or some other open source alternative (here's a [useful link](http://alternativeto.net/software/google-analytics/?license=opensource)).

And I really think that this would be a great move from a marketing perspective.

**Comment by lewisgoddard** [comment]
@davidak @aleksandar-todorovic As I said earlier, I think this is about *elementary OS* not tracking you in anyway.

The website does need a seperate privacy policy, but that changes very little with a move to Piwik, if anything I think Piwik is worse, it makes people easier to personally identify. It's also a big install that isn't really necessary, Google Analytics is an industry standard.

1. http://trends.builtwith.com/analytics/Google-Analytics
2. http://trends.builtwith.com/analytics/Google-Universal-Analytics

**Comment by aleksandar-todorovic** [comment]
@lewisgoddard I know that Google Analytics is pretty much standard today (I use it in my website too) but I really think that it just shows a bad example. I don't think that supporting privacy in the OS and emphasizing that on the website while sending your user data to a third party while you're reading that is a good solution.

**Comment by davidak** [comment]
@lewisgoddard Windows is also industry standard.  ;)

i don't understand how you can say that Piwik is worse Google Analytics.

You can configure Piwik easily to only save the first, second and maybe also the third octet of the ip address -> 77.21.xxx.xxx
Also you can activate that No Tracking-Headers are accepted. Also you can provide an i-frame on the website where people can opt-out of tracking (of course they get tracked doing that).

Piwik installation is easy, they have a one-click updater for some time now. It only needs PHP and a Database.

http://piwik.org/

you should really not use Google Analytics if you talk about privacy. Google identifys you over multiple devices and combines that with much data from their services! then, they sell it to the nsa and others...

**Comment by lewisgoddard** [comment]
I'm sorry, they _sell_ it to the NSA?

**Comment by lewisgoddard** [comment]
I've changed the title so that this bug is clearly about the operating system and not the website. That discussion should be filed under a separate bug.
