### ISSUE TITLE
Fresh Installation - apt-get update ; apt-get upgrade will breack Files/Dateien

### ISSUE THREAD

**Issue by BastianEpting** [elementary/mvp#950]
Dear guys,

unfortunately an

apt-get update
apt-get upgrade 

on a fresh installation

breaks the file explorer / Dateien. 

This will crash afterwards leaving the system nearly unusable.

Greetings

Bastian Epting

**Comment by embik** [comment]
Please file an issue (with more details!) on the [proper bug tracker](https://bugs.launchpad.net/pantheon-files). This repository only contains the code of elementary.io (the website). Thank you!
