### ISSUE TITLE
Slingshot keeps crashing

### ISSUE THREAD

**Issue by NigelGreenway** [elementary/mvp#951]
I can fix it with `$ killall slingshot-launcher`, but it gets frustrating.

Is there a log I can send with the events around the crash?

**Comment by btkostner** [comment]
Please file an issue (with more details!) on the [proper bug tracker](https://bugs.launchpad.net/slingshot). This repository only contains the code of elementary.io (the website). Thank you!

**Comment by NigelGreenway** [comment]
@btkostner Sorry, I will look at it now.

Thanks
