### ISSUE TITLE
Slingshot behaves strangely around 1366×768

### ISSUE THREAD

**Issue by png2378** [elementary/mvp#952]
Slingshot doesn't adapts horizontally on 1366×768 resolution and it looks ugly ([screenshot](https://cloud.githubusercontent.com/assets/12030908/11688648/edb29c08-9e9e-11e5-9ef2-4d2a12b9a6a0.png)). This screen resolution is very popular and this problem affects many visitors.

**Comment by lewisgoddard** [comment]
It is strange that just above and below that resolution it works as expected.
