### ISSUE TITLE
404 page is blank with Chrome on Windows

### ISSUE THREAD

**Issue by KeitIG** [elementary/mvp#960]
https://elementary.io/something

![capture](https://cloud.githubusercontent.com/assets/1311607/11918838/8b2d92cc-a740-11e5-818b-c181cd46d230.JPG)

```
console trace:

Failed to load resource: the server responded with a status of 404 (OK)
```

**Comment by lewisgoddard** [comment]
That is distinctly not blank for me.

**Comment by KeitIG** [comment]
Added a screenshot

**Comment by lewisgoddard** [comment]
Can you tap F12 and reload that page while under the network tab in the new window?

**Comment by KeitIG** [comment]
Working fine on Firefox and Edge.

![sans titre](https://cloud.githubusercontent.com/assets/1311607/11918873/02eca046-a741-11e5-8a20-17c1e08224b2.png)

**Comment by lewisgoddard** [comment]
I just can't seem to confirm this. I'm using Chrome on Windows 10, same as you. Works with and without HTTPS, different languages, everything.

**Comment by KeitIG** [comment]
Strange, will disable some extensions and see how it goes.

**Comment by KeitIG** [comment]
Ok, that's weird. In private navigation everything works. But even after clearing cache and disable every extensions, in normal mode I get stuck on this empty DOM. May be a very specific case. I'll close it but keep investigating.

**Comment by lewisgoddard** [comment]
Have you checked there are no hidden extensions running? Also, the website is behind CloudFlare, so that could be interfering.
