### ISSUE TITLE
Download button says "Download Freya" even though Freya is never mentioned anywhere else on the page

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/mvp#973]
As is it is right now, its probably confusing to other users. 

They're looking at this elementary website, they want to download this thing but the only thing that looks like a download button says "Download Freya". WTF is that?

**Comment by danrabbit** [comment]
Gonna confirm this. We should really change it to say "elementary OS"

**Comment by lewisgoddard** [comment]
What about the buttons in the modal that say Freya 32 bit and 64 bit.
