### ISSUE TITLE
Don't restrict ubuntu-bug to "elementary supported"

### ISSUE THREAD

**Issue by reubenfirmin** [elementary/mvp#988]
The stock applications are not powerful enough for all users.

For example, shotwell is very rigid about how photos are organized, and thus is incompatible with my 14 year old photo collection, which is neatly organized by folder. Therefore I need to use either gthumb or digikam. Both however have bugs, which I wish to report via launchpad. However, you've crippled ubuntu-bug so that unless it's "core" you don't allow it to work. Please fix.

**Comment by embik** [comment]
As you talked about Launchpad, please open this bug on Launchpad. This repository contains elementary's website (elementary.io) and has nothing to do with the operating system.

**Comment by reubenfirmin** [comment]
So how do I report a bug against ubuntu-bug in elementary specifically? ubuntu-bug ubuntu-bug does not work.

FWIW This was the only "report a bug" link I found from your website. So perhaps your website actually does have an issue.

**Comment by cassidyjames** [comment]
@reubenfirmin you can file your bug at https://bugs.launchpad.net/elementaryos/+filebug.

**Comment by reubenfirmin** [comment]
OK, can you link to that on the web page?

**Comment by lewisgoddard** [comment]
`/get-involved` links to https://bugs.launchpad.net/elementary, which links to that in the corner. Might be worth adding https://bugs.launchpad.net/elementaryos/+filebug on `/support` anyway.

**Comment by lewisgoddard** [comment]
Whoops, this appears to be at #989 now.
