### ISSUE TITLE
disable zooming

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#99]
Since we're designing responsively and with mobile in mind, I think we should disable zooming to avoid things getting weird. Specifically we can do this:

```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
```

**Comment by fabianthoma** [comment]
Yeah, this seems like a good idea.

**Comment by cassidyjames** [comment]
Noooooo never disable zoom on mobile. It's an accessibility feature. Browsers should handle it properly with the meta tag I had in there originally. Chrome is improving this usage in the next release, and I believe the other browser vendors have agreed on the implementation.

http://www.androidpolice.com/2015/01/09/chrome-beta-v40-new-zoom-behavior-makes-fixed-headers-scrollable-less-aggravating/
