### ISSUE TITLE
Unification of the power save settings mainly dealing with playing of videos  (in any player or browser)

### ISSUE THREAD

**Issue by mynameherebro** [elementary/mvp#992]
I've seen this problem looked at and ultimately ignored in almost every type of Linux os. It's something so stupid that to continue to ignore it is fatal to people ever fully adopting  Linux as a serious contender in a media friendly context. This needs to be addressed on a priority level. It's annoying when the best option to fix it is a third party program that is the fix when it the entire os itself that needs to be fixed.

**Comment by aleksandar-todorovic** [comment]
I'll just leave this here: https://bugs.launchpad.net/elementary/+filebug

**Comment by KeitIG** [comment]
About the browsers, I'm aware that Chromium has problems preventing sleep mode, but I don't know if it's an upstream bug for Ubuntu.

Anyway, this is not related to the website. You may need to open an issue on Launchpad instead.
